### ISSUE TITLE
Redefined SWIG identifiers

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#1003]
Foo.hh
```c++
// @trick_parse{everything}
#ifndef FOO
#define FOO
template <class T>
class Foo {
    public:
    int i;
}; 
#endif
```
Bar.hh
```c++
// @trick_parse{everything}
#include "Foo.hh"
#ifndef BAR
#define BAR
namespace onion {
class Bar {
    public:
    ::Foo<double> foo;
};
}
#endif
```
Baz.hh
```c++
// @trick_parse{everything}
#include "Foo.hh"
#ifndef BAZ
#define BAZ
namespace potato {
class Bar {
    public:
    ::Foo<int> foo;
};
}
#endif
```
```
build/home/test/sandbox/SIM_sandbox/models/Baz_py.i:34: Warning 302: Identifier 'Barfoo_template' redefined (ignored) (Renamed from 'Foo< int >'),
build/home/test/sandbox/SIM_sandbox/models/Bar_py.i:34: Warning 302: previous definition of 'Barfoo_template' (Renamed from 'Foo< double >').
```

The identifier is used to refer to the type in the target language. So in Python you can do `foo_double = trick.Barfoo_template()` and get a `Foo<double>`. We currently combine the class and member name to form the identifier, which may not be unique in the presence of namespaces as above. However, I doubt anyone is actually using these identifiers to instantiate template types in Python, so the fact that there is no way to instantiate `Foo<int>` probably isn't an issue. Furthermore, both `Foo<double>` and `Foo<int>` still appear to have been wrapped, as I can access the `foo.i` member from instances of both `onion::Bar` and `potato::Bar` in Python. Leaving the identifier out of `%template()` is a tempting option, but that results in the templates being instantiated only and not wrapped, after which `i` is not accessible within `Foo`. I still think we ought to eliminate the warnings, perhaps by prepending the full path of the scope that the class is defined in to the identifier? That should guarantee uniqueness.

@alexlin0 Thoughts?

**Comment by alexlin0** [comment]
Yes, I agree.  The relevant code is in libexec/trick/convert_swig lines 644-649.

```c++
                        $$new_contents_ref .= "\n#define TRICK_SWIG_TEMPLATE_$class_name${var_name}_template\n" ;


                        my $typedef = "\n#ifdef TRICK_SWIG_TEMPLATE_$class_name${var_name}_template\n" ;
                        $typedef .= "\%template($class_name${var_name}_template) $template_full_type;\n" ;
                        $typedef .= "#undef TRICK_SWIG_TEMPLATE_$class_name${var_name}_template\n" ;
                        $typedef .= "#endif\n" ;
```

Everywhere we use $class_name${var_name} in this block we should replace it with a fully namespace qualified name.
