### ISSUE TITLE
QUESTION: Why can't `trick-CP` parallel Compiling & SWIGing files?

### ISSUE THREAD

**Issue by mlouielu** [nasa/trick#1005]
Hi there,

I didn't dig into the code, but I'm curious why can't `trick-CP` parallel to Compiling & SWIGing files?

For example, when I touch some TRICK_ICG header file, it will let `trick-CP` to re-run all the files. causing something like:

```
Compiling  build/S_source.cpp
Compiling  build/modules/foo/io_foo.cpp
Compiling  build/modules/foo/io_bar.cpp
...
Compiling  build/class_map.cpp
Writing  build/modules/bar/foo_py.i
SWIGing  build/modules/bar/foo_py.i
Compiling  build/modules/bar/foo_py.cpp
...
# Repeat nearly all the files
...
Compiling  build/sim_exe/SIM_test/S_source_py.cpp
SWIGing    build/top.i
Compiling  build/top.cpp
Compiling  build/init_swig_modules.cpp
Linking    S_main_*_.exe
Writing    S_sie.resource
Trick Build Process Complete
```

Is there any way to avoid it, or this is a limitation about the `trick-CP` design? 

Thanks.

**Comment by mlouielu** [comment]
OK, so after digging into `trick-CP`, this is possible.

Just add `-jX` to `$makefileAddArgs` in `trick-CP`:

```
$makefileAddArgs = ' -j8';
```

Cheers :)

**Comment by dbankieris** [comment]
I recommend adding the `-j` flag to your environment via `MAKEFLAGS` rather than editing `trick-CP`.
