### ISSUE TITLE
Just thinking it would be kind of nice if all S_overrides.mk files had some default warngings added to them.

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1016]
```
TRICK_CFLAGS += -Werror -Wall -Wextra -I./models
TRICK_CXXFLAGS += -Werror -Wall -Wextra -I./models
```

Most people like to take an example and use it as a starting point.  A lot of times I just copy and paste things from the last time I did something.  I'm just looking at it as a good opportunity to show a good practices for sims.

**Comment by jmpenn** [comment]
What you say here is true. But this point is made in the Trick Tutorial :
[compiler-flag-recommendations](https://nasa.github.io/trick/tutorial/ATutAnalyticSim#additional-compiler-flag-recommendations)
I don't think ISSUES is necessarily the best place to share this.

**Comment by amishscientist** [comment]
To me trick doesn't provided .cshrc and .profile files any more.  I agree ISSUES isn't the best place for sharing that information it should be shared in the list of files below.  Unless if adding -Wall -Wextra -Werror would break any of the sims from compiling ;-P

` 
[jborland@cabaodaba trick]$ find ./ -name "S_overrides.mk"                                                                                                                      ./test/SIM_parse_s_define/S_overrides.mk                                                                                                                                        ./test/SIM_threads/S_overrides.mk                                                                                                                                               ./test/SIM_test_varserv/S_overrides.mk                                                                                                                                          ./test/SIM_dynamic_sim_object/S_overrides.mk                                                                                                                                    ./test/SIM_test_dp/S_overrides.mk                                                                                                                                               ./test/SIM_demo_sdefine/S_overrides.mk                                                                                                                                          ./test/SIM_test_ip2/S_overrides.mk                                                                                                                                              ./test/SIM_stls/S_overrides.mk                                                                                                                                                  ./test/SIM_default_member_initializer/S_overrides.mk                                                                                                                            ./test/SIM_rti/S_overrides.mk
./test/SIM_test_ip/S_overrides.mk                                                                                                                                               ./test/SIM_alloc_test/S_overrides.mk                                                                                                                                            ./test/SIM_leaks/S_overrides.mk                                                                                                                                                 ./test/SIM_measurement_units/S_overrides.mk                                                                                                                                     ./test/SIM_isystem/S_overrides.mk                                                                                                                                               ./test/SIM_test_abstract/S_overrides.mk                                                                                                                                         ./test/SIM_segments/S_overrides.mk                                                                                                                                              ./test/SIM_demo_inputfile/S_overrides.mk                                                                                                                                        ./test/SIM_exclusion_mechanisms/S_overrides.mk                                                                                                                                  ./test/SIM_test_sched/S_overrides.mk                                                                                                                                            ./test/SIM_test_io/S_overrides.mk                                                                                                                                               ./test/SIM_trickcomm/S_overrides.mk                                                                                                                                             ./test/SIM_threads_simple/S_overrides.mk                                                                                                                                        ./test/SIM_python_namespace/S_overrides.mk                                                                                                                                      ./test/SIM_target_specific_variables/S_overrides.mk                                                                                                                             ./test/SIM_test_dr/S_overrides.mk                                                                                                                                               ./test/SIM_test_templates/S_overrides.mk                                                                                                                                        ./test/SIM_test_inherit/S_overrides.mk                                                                                                                                          ./test/SIM_swig_template_scoping/S_overrides.mk                                                                                                                                 ./trick_source/er7_utils/sims/SIM_grav/S_overrides.mk                                                                                                                           ./trick_source/er7_utils/sims/SIM_ball_L1/S_overrides.mk                                                                                                                        ./trick_sims/SIM_rocket/S_overrides.mk                                                                                                                                          ./trick_sims/SIM_lander/S_overrides.mk                                                                                                                                          ./trick_sims/SIM_satellite/S_overrides.mk                                                                                                                                       ./trick_sims/SIM_sun/S_overrides.mk                                                                                                                                             ./trick_sims/SIM_wheelbot/S_overrides.mk                                                                                                                                        ./trick_sims/SIM_Ball++_L1/S_overrides.mk                                                                                                                                       ./trick_sims/SIM_parachute/S_overrides.mk                                                                                                                                       ./trick_sims/ROS/SIM_ros_subscriber/S_overrides.mk                                                                                                                              ./trick_sims/ROS/SIM_ros_publisher/S_overrides.mk                                                                                                                               ./trick_sims/SIM_sat2d/S_overrides.mk                                                                                                                                           ./trick_sims/SIM_contact/S_overrides.mk                                                                                                                                         ./trick_sims/ODE/SIM_ode_buggy/S_overrides.mk                                                                                                                                   ./trick_sims/ODE/SIM_ode_ball/S_overrides.mk                                                                                                                                    ./trick_sims/Ball/SIM_ball_L3/S_overrides.mk                                                                                                                                    ./trick_sims/Ball/SIM_ball_L1/S_overrides.mk                                                                                                                                    ./trick_sims/Ball/SIM_ball_L2/S_overrides.mk                                                                                                                                    ./trick_sims/Cannon/SIM_cannon_analytic/S_overrides.mk                                                                                                                          ./trick_sims/Cannon/SIM_cannon_jet/S_overrides.mk                                                                                                                               ./trick_sims/Cannon/SIM_cannon_aero/S_overrides.mk                                                                                                                              ./trick_sims/Cannon/SIM_cannon_eulercromer/S_overrides.mk                                                                                                                       ./trick_sims/Cannon/SIM_cannon_numeric/S_overrides.mk                                                                                                                           ./trick_sims/Cannon/SIM_monte/S_overrides.mk                                                                                                                                    ./trick_sims/Cannon/SIM_amoeba/S_overrides.mk                                                                                                                                   ./trick_sims/SIM_msd/S_overrides.mk
`

You have some additional -W in some of the S_overrides.mk files now.


`
[jborland@cabaodaba trick]$ find ./ -name "S_overrides.mk" \| xargs  -n 1 -P 1 awk '/TRICK_C/&&/FLAGS/&&/-W/{print FILENAME; print "   "$0}'                                     
./test/SIM_isystem/S_overrides.mk                                                                                                                                                  TRICK_CXXFLAGS += -Wall -Wextra -I$(MODELS)/my_code -isystem$(MODELS)/third_party                                                                                            ./test/SIM_target_specific_variables/S_overrides.mk                                                                                                                                TRICK_CXXFLAGS += -I$(MODELS) -Wcomment -Werror                                                                                                                              ./test/SIM_target_specific_variables/S_overrides.mk                                                                                                                                $(call FIND_MODEL_OBJECTS, $(MODELS)/one/1 $(PATHS)): TRICK_CXXFLAGS += -Wno-comment                                                                                         ./trick_sims/ROS/SIM_ros_subscriber/S_overrides.mk                                                                                                                                 TRICK_CXXFLAGS += -I../models -I${ROS_HOME}/include -Wno-shadow -Wno-unused-parameter                                                                                        ./trick_sims/ROS/SIM_ros_publisher/S_overrides.mk                                                                                                                                  TRICK_CXXFLAGS += -I../models -I${ROS_HOME}/include -Wno-shadow -Wno-unused-parameter                                                                                        [jborland@cabaodaba trick]$
`
