### ISSUE TITLE
SWIG warning 315: Nothing known about 'identifier'.

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#1025]
```c++
// @trick_parse{everything}

template <class T>
class Foo {
    public:
    int i;
};

template <class T>
class Bar : public Foo<T> {
    public:
    using Foo<T>::i;
};
```
```c++
#include "sim_objects/default_trick_sys.sm"
##include "Foo.hh"

class Sandbox : public Trick::SimObject {
    public:
    Bar<int> bar;
    Sandbox() {}

    private:
    void operator=(const Sandbox&);
};
Sandbox sandbox;

```
```
build/home/test/sandbox/SIM_sandbox/models/Foo_py.i:27: Warning 315: Nothing known about 'Foo< int >::i'.
```

Per the [documentation](http://www.swig.org/Doc2.0/SWIGDocumentation.html#SWIGPlus_nn30), the `%template` directive must be used to inform SWIG of particular template instantiations. `convert_swig` inserts a `%template(Sandbox_bar) Bar<int>;` into `S_source_py.i` so that `Bar<int>` can be wrapped, but it does not instantiate parent class templates such as `Foo<int>`, which is why we ignore [SWIG warning 401](http://www.swig.org/Doc2.0/Warnings.html#Warnings_nn13). I suspect this is because at the point we would need to write parent class instantiations, we no longer have parent class information. Yet another reason to replace `convert_swig` with a clang-based solution.

@alexlin0 In the meantime, should we ignore this warning as well?

**Comment by alexlin0** [comment]
Yes, ignore it!
