### ISSUE TITLE
PDF version of docs

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1029]
Generating a pdf with links from the web documentation would be a nice feature for some of our users.

**Comment by gcc-shivansh** [comment]
Hi, i am interested in solving this issue. Can you give me some guidance on how i could get started?

**Comment by XmatrixZ** [comment]
Hi, i am interested in solving this issue. Can you give me some guidance on how i could get started?

**Comment by spfennell** [comment]
> Hi, i am interested in solving this issue. Can you give me some guidance on how i could get started?

Hi, I am glad you are interested in contributing to our project! All of our documentation is represented by github pages at https://nasa.github.io/trick/

This documentation site is generated from our trick/docs directory. We would like a pdf version of the website, and all hyperlinks should be replaced with clickable pdf indexes.

**Comment by spfennell** [comment]
The tool httrack is successful at downloading our doc pages and preserving all the resources and relative links. It is not a PDF, but instead an offline version of the website, but it may be enough for some users who just need the docs when they don't have a web connection.
