### ISSUE TITLE
io_src files with c++14 features may not compile

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#1036]
From c++ proposal [N3653](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3653.html):

```c++
// @trick_parse{everything}
class Foo {
    struct S { int a; const char* b; int c; int d = b[a]; };
    S ss = { 1, "asdf" };
};
```

Compiling on Centos 8, whose default gcc version is 8.3.1, which supports c++14 by default:
```
In file included from /home/SIM_test/S_source.hh:27,
                 from build/home/SIM_test/io_S_source.cpp:19:
/home/SIM_test/models/Foo.hh:5:21: error: could not convert ‘{1, "asdf"}’ from ‘<brace-enclosed initializer list>’ to ‘Foo::S’
  S ss = { 1, "asdf" };
```
[`PrintAttributes.cpp`](https://github.com/nasa/trick/blob/ab2cfe1a34bfe8fe8edf1098b66c5273c8fa0c03/trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp#L365) adds `--std=c++11` to `TRICK_IO_CXXFLAGS` because ICG produces code that requires at least c++11 to compile and versions of gcc on some supported distributions do not support c++11 by default. Unfortunately, that means even if the compiler supports newer versions of c++, it will only accept c++11-compliant code.

Adding `TRICK_IO_CXXFLAGS += --std=c++14` to `S_overrides.mk` solves the problem, but it would be better if ICG only specified the std when necessary.

**Comment by spfennell** [comment]
related to #1007

**Comment by dbankieris** [comment]
Shame on me for not looking for an existing issue.
