### ISSUE TITLE
Linking libclang-cpp.so causes static global constructors for new command line options to be called, which interferes with ICG's command line options

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1041]
Linking libclang-cpp.so (the new all-in-one clang lib) causes static constructors for new command line options to be called, which interferes with ICG's command line options.

Specifically, the --no-warn cl::opt is created, which has an alias 'W'. This causes our warning flags -Wextra and -Wall to be interpreted as --no-warn. --no-warn can only be added once, so ICG crashes.

Need to find a way to disable or work-around this issue. 

noWarn is defined in this file:
https://llvm.org/doxygen/MCTargetOptionsCommandFlags_8cpp_source.html

Might be some relevant information on this forum:
https://reviews.llvm.org/D75579

Related to issue  
#1009

**Comment by alexlin0** [comment]
OK, I was able to recreate the error.  ICG doesn't need to know about any arguments that start with "-W".  I tested changing this line in ICG's main.cpp and it seems to work.

**From**
```c++
    llvm::cl::ParseCommandLineOptions(argc, argv);
```

**To**
```c++
    std::vector<const char *> filtered_args;
    for ( unsigned int ii = 0;  ii < argc ; ii++ ) {
        if( strncmp(argv[ii], "-W", 2) ) {
            filtered_args.push_back(argv[ii]);
        }
    }
    llvm::cl::ParseCommandLineOptions(filtered_args.size(), filtered_args.data());
```
