### ISSUE TITLE
install guide is very outdated

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1050]
Remove old OS, old notes that are not relevant, add new OS, and make instructions easier to follow.

**Comment by reallydivs** [comment]
I can do it , but just one question is this commit to be made for the README or the website itself.
First timer here.

**Comment by spfennell** [comment]
Hi @reallydivs, thank you for offering to contribute. You would be editing the documentation in the /docs directory. However, I've already started updating the install guide on branch 1048, so most of the changes I want will already be made soon. Are you an experienced Trick user? This is not really a good first issue, because there are caveats about installation that only Trick devs would know about. 

Can I recommend this issue instead?
https://github.com/nasa/trick/issues/1029

If you could find a way to generate a pdf of https://nasa.github.io/trick/ that would be very helpful.

Our doc website is generated from the /docs folder of the repository through github pages (see https://pages.github.com/)

If you would like some other issue recommendations please let me know!

**Comment by reallydivs** [comment]
@spfennell thank you for clarifying, I will start with the pdf generation of the https://nasa.github.io/trick/  and also could you recommend me more issues , would love to solve them.
