### ISSUE TITLE
Trick DP core dumps when trying to read large .mat file

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#106]
Evidence suggests the size of the .mat file is what triggers this issue.  See below for core dump and example file size that caused this issue.  I am reporting this for another user, but if you need more information to replicate, please let me know.

/users/myusername/repos_silver/antares/cev/sims/SIM_mysim/RUN_test
total 511884
drwxr-x--- 1 myusername cev      1420 Aug  7 14:37 ../
-rwxr-x--- 1 myusername cev      8192 Aug  7 15:35 input.py*
-rw-r----- 1 myusername cev      4151 Aug  7 15:35 mc_input.py
-rw-r----- 1 myusername cev      3808 Aug  7 15:43 S_run_summary
-rw-r----- 1 myusername cev      5020 Aug  7 15:43 log_entry_sim_verif.header
-rw-r----- 1 myusername cev     57531 Aug  7 15:43 S_job_execution
-rw-r----- 1 myusername cev    839212 Aug  7 16:01 log_entry_sim_verif.trk
-rw-r----- 1 myusername cev      1123 Aug  7 16:01 send_hs
-rw-r----- 1 myusername cev      2674 Aug  7 16:01 sim_output
drwxr-x--- 1 myusername cev       448 Aug  7 16:03 ./
**-rw-r----- 1 myusername cev 523219564 Aug  7 16:04 matlabdata.mat**

For some reason this file is PREVENTING me form plotting up the results in Trick_DP when using the DP_Products (i.e. DP_entry).
If I remove or rename it then Trick_DP works!

**Error in Trick_DP:
===>>>Launching /users/myusername/repos_silver/antares/../trick13/bin/fxplot /tmp/Session_myusername.xml<<<===
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/users/myusername/....../trick13/bin/fxplot: line 10: 36367 Aborted                 (core dumped) ${FXPLOT} $@**

**Comment by jmpenn** [comment]
Problem and solution are self-evident. Closing issue.

**Comment by alexlin0** [comment]
Use Matlab as the plotter, not Trick.

**Comment by jmpenn** [comment]
Re-Opening. It shouldn't core-dump regardless.

**Comment by alexlin0** [comment]
@ddj116 Did you ever notice how your avatar looks like the Denmark flag?
![index](https://cloud.githubusercontent.com/assets/8008141/9259633/0b5e2b0c-41c8-11e5-9d40-d4c177e40c5b.png)

**Comment by ddj116** [comment]
Yeah, the default avatar didn't really speak to me.  Fixed.

**Comment by alexlin0** [comment]
Closing this issue.  Pointing to koviz as possible solution.
