### ISSUE TITLE
PATH is modified to add /usr/local/bin in configure. Why? And how do we force system tools?

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#1076]
One of our external labs using Trick is experiencing a Trick build problem due to it finding the non-standard gcc and python versions. They traced this to [this line in configure](https://github.com/nasa/trick/blob/master/configure#L2503).

```sh
PATH="/usr/local/bin:${PATH}"
```

Two questions:
1. Why is `/usr/local/bin` added to `PATH` here? This appears to break the users ability to set their environment, then run `./configure` to control which toolset is used.
2. What is the proper way for the user to have trick use the system `/usr/bin/gcc` and other tools when they have a non-standard toolset located int `/usr/local/bin/`?

**Comment by spfennell** [comment]
From issue #780 it seems like this was added only to make sure macOS could find swig. I've changed the configure swig to only add it to the PATH if swig is not specified, and also to add it to the END of the path instead of the beginning.  The built in SWIG finder  function uses the  PATH variable, so we  must modify path to use it. If this is still causing issues with /usr/local/bin at the end of PATH, we may want to replace the built in swig finder function with an in-house function.

**Comment by ddj116** [comment]
@spfennell when this fix is made on `master`, would it be possible to cherry-pick it onto a new sub-release off of `19.0.1`? Either `19.0.2` or `19.0.1.1`, whatever y'all prefer. Ramtares will need this fix and we are currently stuck on `19.0.1` for reasons unrelated to this issue (JEOD compatibility).  If we can't get a patch for `19.0.1` we'll be forced to fork Trick or do some other hack to get past this issue until we can eventually upgrade to Trick 19.2+. Thanks!

**Comment by alexlin0** [comment]
A couple of things.

- Homebrew installs everything in /usr/local.  That is why we add it automatically.
- My mvn (maven) is found in /usr/local/bin.
- Another reason for putting /usr/local/bin before the standard PATH is that most people want the local version of the executable/library to take precedence over what is normally installed on the system.

I suggest adding a configure flag that does not add /usr/local/bin in automatically.  In this case it will be up to the users to add /usr/local/bin in their PATH in the appropriate spot, if at all.

**Comment by spfennell** [comment]
> @spfennell when this fix is made on `master`, would it be possible to cherry-pick it onto a new sub-release off of `19.0.1`? Either `19.0.2` or `19.0.1.1`, whatever y'all prefer. Ramtares will need this fix and we are currently stuck on `19.0.1` for reasons unrelated to this issue (JEOD compatibility). If we can't get a patch for `19.0.1` we'll be forced to fork Trick or do some other hack to get past this issue until we can eventually upgrade to Trick 19.2+. Thanks!

Because this code will be very non-invasive, I will create a patch for minor version 19.0 that adds the new configure option Alex suggested. 

HOWEVER, for anyone reading this, I reserve the right to refuse any (or all) future requests to patch any minor version of Trick  for any reason🙃 👏.

**Comment by dbankieris** [comment]
The precedent is broken! Official minor Trick revisions shall proliferate without bound!
