### ISSUE TITLE
Consider better error message for missing S_sie.resource file

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#1088]
Build a sim, delete its `S_sie.resource`, run it, and you get "Error: S_sie.resource is corrupted or outdated. Cannot add runtime/dynamic allocations. Please rerun trick-CP".  This situation is likely to happen in CI if you forget to specify `S_sie.resource` as an artifact between your build and run jobs. It would be helpful to have a more specific message for when the file is missing entirely. Whatcha think, @spfennell?

**Comment by spfennell** [comment]
Yes, a more descriptive message, and a warning instead of an error since S_sie.resource is not a required file. I'll include it in the Sie patch I'm working on in https://github.com/nasa/trick/tree/1086-tv-dynamic-allocations
