### ISSUE TITLE
QUESTION: How to message_publish to the sim control panel at init

### ISSUE THREAD

**Issue by keithvetter** [nasa/trick#1143]
It looks like message_publish() doesn't send messages to the sim control panel from init jobs.  Is this because init jobs are run before the sim control panel is available?

To try, put a message_publish in the ball L2 sim ball_state_init job.

**Comment by keithvetter** [comment]
I found a work around to get init jobs to print to the sim control panel.  Make a P1 ("initialization") job, and put a sleep in it.  The sleep gives the sim control panel enough time to get health and status messages going before the real init jobs.  It's a hack, but should work.

**Comment by alexlin0** [comment]
message_publish calls are sent to stdout as well as a RUN/send_hs file.  Is seeing the messages in the terminal enough?

**Comment by keithvetter** [comment]
I think the sim may be launched by a script, so the sim control panel is what the user will be looking at, not stdout.  

I think the sleep() may work for them.  I tested it today, and it worked.

**Comment by keithvetter** [comment]
Here is the hack, put this at the top of the S_define:

```cpp
##include <stdio.h>
##include <unistd.h>
class SimControlPanelWaitSimObject : public Trick::SimObject {

  public:

    SimControlPanelWaitSimObject()
    {
        P1 ("initialization") simControlPanelWait();
    }

    void simControlPanelWait()
    {
        int i = 0;
        while (1) {
            char buf[256];
            sprintf(buf, "Wait on sim control = %d\n", i);
            message_publish(0,buf);
            if ( ++i == 5 ) {
                break;
            }
            sleep(1);
        }
    }
};

SimControlPanelWaitSimObject simControlPanelWait;
```
