### ISSUE TITLE
Fix "Argument list too long" error for large trickified libraries and/or long build paths

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#1155]
## The problem

When a trickified library has too many `$(IO_OBJECTS)`, `$(SWIG_OBJECTS)`,  or the build path is of sufficiently large length, this error can occur on the final link  of `$(TRICKIFY_OBJECT_NAME)`:
```
Linking^[[0m    trickified_lib.o
make[1]: execvp: /bin/bash: Argument list too long
```

This has been replicated for the JEOD trickified library in ramtares with an extremely long path to the repository

## The fix

We can change `ld` to use `@file` notation for input which will shorten the recipe length as run in the shell

**Comment by dbankieris** [comment]
Note that `ld` is only used when `TRICKIFY_BUILD_TYPE` is `PLO`. Solutions for `TRICK_CXX` and `ar` are also needed.

**Comment by dbankieris** [comment]
Oh, they all support `@file`. Woohoo!
