### ISSUE TITLE
Variable Server: var_add cant add "<var>.<var>" because its a composite variable in Trick TV

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#1158]
## The error

The sim builds and runs fine, but if you try to access certain JEOD variable paths, you will see this type of error and Trick TV will show `<Invalid Reference>`. We noticed this for variable paths `moon.planet` and `earth.planet`, but there may be others.

<img width="945" alt="Screen Shot 2021-06-07 at 2 37 08 PM" src="https://user-images.githubusercontent.com/3249339/121243340-3ca9a380-c863-11eb-9b77-0dfa3f9374d0.png">

## Details on configuration

I'm seeing this in both Ramtares and Gateway projects. In both projects we build JEOD 3.4 into a library, link against it, and also use the Trickified JEOD library. I do not know if this is replicatable without JEOD or not.  The header file `jeod/models/environment/planet/include/planet.hh` does not change across the trick versions tested, details below.

## The commit range

From my testing, I know this change in Trick TV behavior was introduced somewhere between  `4bba925` (Nov 2020) [where there's no error] and today's `origin/master` [where the above error occurs].  From parsing the `git log` my best guess would be that this change in behavior happened when the creation of the `S_sie.resource` file changed strategy from `./S_main_Linux_4.8_x86_64.exe sie` to the new method.

I couldn't figure out which is the first stable commit with the new methodology, if someone can point me to that I can further narrow the changes that lead to this issue.

## The evidence

Thanks to @dbankieris's suggestion, I was able to confirm that when this error happens it corresponds to the `class name="Planet"` section being missing from `S_sie.resource`.  Here's the top part of that section for trick commit `4bba925`
```
 <class name="Planet">
      <member
        name="name"
        type="char"
        io_attributes="15"
        units="--">
        <dimension>0</dimension>
      </member>
      <member
        name="inertial"
        type="EphemerisRefFrame"
        io_attributes="15"
        units="--">
      </member>
 ...
```

---

FYI @spfennell @dbankieris @alexlin0 @jmpenn -- if you have any suggestions let me know.

**Comment by hchen99** [comment]
OBE by #1652
