### ISSUE TITLE
macOS Redefinition Error

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1163]
We have some Trick users getting a redefinition error on Catalina 10.15.7. I am not having this issue on my Catalina 10.15.7 machine or any of my cloud macOS machines.

In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h:107:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:32:26: error: typedef redefinition with different types ('__darwin_va_list' (aka 'void *') vs '__builtin_va_list')
typedef __darwin_va_list va_list;
^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/stdarg.h:14:27: note: previous definition is here
typedef __builtin_va_list va_list;

**Comment by spfennell** [comment]
Solved. An old version of trick was 'installed' in the system directories, and these artifacts were being linked in and conflicted with the new build.

**Comment by alexlin0** [comment]
The error was found, but this is one of many times this has happened.  Perhaps we should look into how we could prevent this from happening in the future?

**Comment by spfennell** [comment]
This issue can be closed when va_list redefinition errors are no longer present or printed on macOS
