### ISSUE TITLE
Killing trick can create zombie process'

### ISSUE THREAD

**Issue by jwberck** [nasa/trick#1205]
When stopping trick with a ctrl c command, there are lingering processes that continue. This doesn't happen when shutting down properly from the trick GUI, but if you run a debugging tool on trick (gdb) and try to restart or stop it, it can continue to live on as a zombie.

**Comment by jmpenn** [comment]
Pressing Ctrl-C causes the system to send a SIGINT to a running process.
If that signal is not handled by the process, it terminates.

By default Trick, (and some other programs) DO handle the SIGINT signal.
In Trick Ctrl-C is by default, interpreted as toggling the run state (i.e., RUN or FREEZE). It doesn't kill the sim. It only freezes or unfreezes the sim.

I believe there's a way to change this default behavior, but I'll have to look it up.

**Comment by jmpenn** [comment]
https://nasa.github.io/trick/documentation/simulation_capabilities/Executive-Scheduler.html#user-mode-control describes how this works.

**Comment by jmpenn** [comment]
If you believe there is more to be addressed here, please let me know. Otherwise I'm going to close this issue.
