### ISSUE TITLE
Numerous "error: use of undeclared identifier '__builtin_ia32..." errors during make test

### ISSUE THREAD

**Issue by bitblit11** [nasa/trick#122]
When building samples with make test, I see a lot of errors stream by starting with "error: use of undeclared identifier '__builtin_ia32_".  I've seen this before, but the build usually seems to still work.  At least, it completes the build.  What is this?  Is there a gnu tools dependency?

**Comment by alexlin0** [comment]
Which version of Trick is this in?

**Comment by bitblit11** [comment]
Change log says 15.0.beta

**Comment by alexlin0** [comment]
I would suggest updating.  I believe that we have fixed this between your version and the current.
