### ISSUE TITLE
Configure script fails with HDF5 in non-standard location

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#1232]
Running
```sh
./configure --with-hdf5=SOMEWHERE_UNUSUAL
```
will find the header but fail in the linking test.

Trick will add the HDF5 library location to the link path for building the sim:
https://github.com/nasa/trick/blob/c8a29bea0deb2983d3c3c2d28491cbc81e857c1a/share/trick/makefiles/Makefile.common#L150

However, the `-L$(HDF5)/lib` argument isn't present when performing the link test, so the test fails.

This may also be an issue with other libraries, but I have only tried it with HDF5.

**Comment by alexlin0** [comment]
Still finding our bugs, I see.

**Comment by spfennell** [comment]
@iamthad It's fixed but if you need a workaround for an old version, you can add ${HDF5}/lib to LDFLAGS before running configure. You can unset it after if you need to.
