### ISSUE TITLE
Disambiguate python use

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#1250]
Several scripts use /usr/bin/python or other variations that are not explicit to which python version to use. Time to move into the present and set all of the scripts to python3.

**Comment by spfennell** [comment]
Anything in Trick calling python should be using the PYTHON variable set by the configure script, which will generally be python3 on any recent OS releases.

**Comment by spfennell** [comment]
> Anything in Trick calling python should be using the PYTHON variable set by the configure script, which will generally be python3 on any recent OS releases.

To clarify, I think this is the fix for this issue

**Comment by spfennell** [comment]
@alexlin0 Oh I see, you were changing the #!. Nevermind!
