### ISSUE TITLE
`var_server_get_user_tag()` returns garbage on Oracle Linux 8

### ISSUE THREAD

**Issue by dsfenn** [nasa/trick#1260]
Hello,

I recently switched from CentOS 7 to Oracle Linux 8, and since the switch I've been running into an issue with `var_server_get_user_tag()`. It seems to be returning garbage data rather than the expected string.

The following MWE produces the error for me

S_define:
```
/************************TRICK HEADER*************************
PURPOSE:
    mwe for var_server_get_user_tag
LIBRARY DEPENDENCIES:
    
*************************************************************/

#include "sim_objects/default_trick_sys.sm"
```

input.py:
```
trick.var_server_set_user_tag("testing")
temp = trick.var_server_get_user_tag()
print("PRINTABLE:", ''.join([i if i.isprintable() else '*' for i in temp]))
```

I'm using commit `0c207dd5115ab19b36c5d002b8c2360cc853916a` on `master`.

Note: the final line of `input.py` is just replacing non-printable characters with *. Otherwise, the garbage data causes it to crash.

Also, if I insert random `cout` statements in the definition of `var_server_get_user_tag()`, the issue goes away, which looks like a memory issue to me. Specifically, I added this to see the location of the pointer:

```
const char* tagAdd = the_vs->get_listen_thread().get_user_tag().c_str();
std::cout << "User tag address: " << (void *) tagAdd << "\n";
```

I see that `var_server_get_user_tag()` is returning a pointer, and I'm wondering what's happening to the memory at that location after the c++ function returns.

Thanks for your help.

**Comment by spfennell** [comment]
Hi dsfenn,

Yes, good catch. "get_user_tag" returns by value and not by reference. So "the_vs->get_listen_thread().get_user_tag()" is a temporary "pass by value" std::string which can be deallocated whenever it feels like. I'll get a fix out and close this issue ASAP. 

Sorry for the delay, thanks for your patience.

**Comment by dbankieris** [comment]
Might I suggest `get_user_tag_ref` return a `const` reference lest the caller modify `user_tag`?

**Comment by spfennell** [comment]
> Might I suggest `get_user_tag_ref` return a `const` reference lest the caller modify `user_tag`?

Good idea.

**Comment by dsfenn** [comment]
Great--thank you!
