### ISSUE TITLE
AttributeError not being raised in SWIG 4 when making an improper assignment in input processor

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1288]
When making an assignment in the input file, if the member does not exist then an AttributeError is raised and the sim crashes. This AttributeError is not being raised in SWIG 4. Steps to reproduce: make an assignment in an input file to a nonexistent member of a SimObject on a SWIG 4 trick build.

https://github.com/nasa/trick/blob/de914d9fb6098d76da50f368d4bd02c37808dcaf/include/trick/swig/trick_swig.i#L68-L107

**Comment by spfennell** [comment]
They removed the functions we are overloading:

https://github.com/swig/swig/commit/4301fa548d1e4b9a53811d766e86301b9d473d9d

**Comment by spfennell** [comment]
https://github.com/swig/swig/issues/719

**Comment by spfennell** [comment]
This issue can be closed when AttributeErrors are raised in SWIG >= 4 when there is a typo in the input file.

**Comment by alexlin0** [comment]
I ran into this issue yesterday.  I figured out how to fix it.  The change below overrides the __setattr__ function for all classes and calls a function which checks to see if the member variable exists before the assignment is made.  This makes the new SWIG  behave like older SWIG versions.  the _swig_setattr_nondynamic_instance_variable function is provided by SWIG and is similar to what our version of _swig_setattr_nondynamic above is.  If later we need to override _swig_setattr_nondynamic_instance_variable it can be done the same way as above.

```
diff --git a/libexec/trick/convert_swig b/libexec/trick/convert_swig
index 74595770..d208e3d4 100755
--- a/libexec/trick/convert_swig
+++ b/libexec/trick/convert_swig
@@ -669,6 +669,7 @@ sub process_class($$$$$) {
     push @$class_names_ref , "$curr_namespace$class_name" ;
 
     # write the class contents and semicolon to ensure any template declarations below are after the semicolon.
+    $$new_contents_ref .= "\n#if SWIG_VERSION > 0x040000\n\%pythoncode \%{\n    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)\n\%}\n#endif\n" ;
     $$new_contents_ref .= $extracted . ";\n" ;
     # write out the templated variable declaration lines found in this class.
     $$new_contents_ref .= $template_typedefs ;
```
