### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [nasa/trick#13]
I suggest to reuse a higher level build system than [your current make file](https://github.com/nasa/Trick/blob/2fab93da66ba533d846221b43ff4a1f39ee49282/Makefile#L2 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by alexlin0** [comment]
We are working towards using autoconf to replace our custom configure script.  Make currently satisfies our requirements so we don't have a need to switch to a different build system.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.2/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by alexlin0** [comment]
Closing this issue as we have now moved to use autotools.
