### ISSUE TITLE
configure script does not check for clang/llvm

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#130]

**Comment by alexlin0** [comment]
actually it does... I forgot.

**Comment by alexlin0** [comment]
but the check is weak.

**Comment by iamthad** [comment]
Likely related: clang is assumed to live in llvm/bin, which is not the case on e.g. Ubuntu Trusty.

**Comment by alexlin0** [comment]
In Ubuntu Vivid llvm-config --bindir returns /usr/lib/llvm-3.6/bin and clang is present in that directory.  In Ubuntu Trusty llvm-config --bindir returns /usr/lib/llbm-3.4/bin and clang is not present causing the error.  Looks like we need to test to see if clang actually resides in the directory llvm-config --bindir returns.

**Comment by iamthad** [comment]
This might be helpful in testing for LLVM: http://www.gnu.org/software/autoconf-archive/ax_llvm.html#ax_llvm

Is it not possible to simply run `which clang` and/or `which clang++` prior to assuming they are in the LLVM bindir?

**Comment by alexlin0** [comment]
Sometimes people want to specify a different directory so we can't use the which command.  I've put in a patch and it works on our 14.04 machine.

**Comment by iamthad** [comment]
The ICG makefile also makes the same assumption that clang and clang++ live in llvm/bin. It doesn't look at the CLANG environment variable at all.

**Comment by alexlin0** [comment]
I think everything is how we want it now.
