### ISSUE TITLE
Use tsan to check for concurrency issues in a Trick sim

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1307]
Once in a blue moon Trick will crash, possibly because of a data race ( #1290 #964 ).  Build trick and a sim with tsan and see if there is any useful information provided by the tool. Add a section in the docs to describe where to add flags to add the tool to the build.

**Comment by jdeans289** [comment]
tsan has a significant amount of output on any sim, especially around data recording, variable server, and thread shutdown. This is worth a lot more investigation, and will likely require some refactors, but could theoretically get rid of some of these random crashes.
