### ISSUE TITLE
Add Horizontal Navigation Bars, (AKA Breadcrumbs) to Documentation

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1313]
Some pages have them, some don't

**Comment by jdeans289** [comment]
They look like this. Most of the tutorial has them, but the rest mostly doesn't.

<img width="449" alt="Screen Shot 2022-07-27 at 2 15 12 PM" src="https://user-images.githubusercontent.com/15197456/181353869-e3fac382-cb9d-48da-9227-3ca5770d60ef.png">
