### ISSUE TITLE
Feature Request: Add trick_units alias

### ISSUE THREAD

**Issue by matthewelmer** [nasa/trick#1320]
Let `foo` = `**|*i|*o|*io`.
Currently, `trick_io(foo)` and `trick_chkpoint_io(foo)` can be shortened to `io(foo)` and `cio(foo)`, respectively. It would be nice to have the option to shorten `trick_units(foo)` to `tu(foo)` or something similar.

**Comment by alexlin0** [comment]
The trick_units keyword can be omitted.  `(kg)` or `(m/s)` will be interpreted as units.

**Comment by matthewelmer** [comment]
Ah, and because the others have their explicit names, the parser won't get confused. Makes sense, thanks!

If it's any help, this is the part of the documentation I read before making this feature request: https://nasa.github.io/trick/documentation/building_a_simulation/Model-Source-Code#the-inputoutput-specification
