### ISSUE TITLE
Refactor variable server and web server to share code

### ISSUE THREAD

**Issue by jdeans289** [nasa/trick#1333]
The variable server and web server both accept variable server commands, manage sessions, and access sim variables, but they use different codebases to do it. There is some code copy-pasted between them, but lots of small differences that could cause confusion if trying to use the variable server and web server interchangeably. The webserver has much less functionality than the variable server right now, since anything implemented for the variable server must be re-implemented on the webserver side. Refactor the variable and web servers to have a common "middle layer" that manages session variables and performs variable server commands. This will mostly involve separating variable management from socket/connection/thread management in both servers.

**Comment by spfennell** [comment]
Reminder comment that we should close #730 when this is completed.
