### ISSUE TITLE
Trick default configuration should use Trick's Integrators rather than those of er7utils

### ISSUE THREAD

**Issue by jmpenn** [nasa/trick#1340]
By default Trick will be configured to use Trick integrators.

To build Trick with er7utils integrators, configure must be run with the option:

--enable-er7utils=yes

**Comment by spfennell** [comment]
This issue can be worked on in 
[1342-noerinteg-ci-pipeline](https://github.com/nasa/trick/tree/1342-noerinteg-ci-pipeline)
. 
Once the test suite passes on that branch (with trick integrators) we can merge it in.
