### ISSUE TITLE
Remove code that attaches a debugger on segfault in Mac

### ISSUE THREAD

**Issue by jdeans289** [nasa/trick#1382]
Trick has code in sim_services/Executive/Executive_signal_handler.cpp:73 that attaches a debugger and tries to produce a stack trace when a segfault signal is received. On Mac, this does not work. Maybe this worked at some point, but with the recent Mac security changes, this now will just hang, and will sometimes even crash the terminal and require a restart. Since the only effect it has now is slowing down development, it should be removed.

This issue can be closed when:
1. This code is machete'd

**Comment by alexlin0** [comment]
Is there no way to make this work anymore?  It has been useful in the past.

**Comment by jdeans289** [comment]
Possibly? It would definitely take some digging around in the new Mac security stuff. Maybe for now I'll remove it, but open another issue to come back around when I have the bandwidth and look at it.
