### ISSUE TITLE
Missed the two gdb_commands and the move to share/trick directory

### ISSUE THREAD

**Issue by excaliburtb** [nasa/trick#1385]
https://github.com/nasa/trick/blob/e65a0b078362e1cdcb7418867b4b278840baef51/trick_source/sim_services/Executive/Executive_fpe_handler.cpp#L82

**Comment by jdeans289** [comment]
Is this related to #1382 or #1383 ?

**Comment by excaliburtb** [comment]
No.  there was a recent change in the location of `bin/gdb_commands` to `share/trick`. The Executive_signal_handler.cpp file was updated with the new path but the Executive_fpe_handler.cpp file was not.
