### ISSUE TITLE
Should TV use rti_add by default?

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#142]
Should TV use rti_add by default?

**Comment by excaliburtb** [comment]
yes.

**Comment by dbankieris** [comment]
<code>rti_add</code> will need several improvements before it can be a transparent replacement for <code>var_set</code>

- support for types other than <code>long long</code> and <code>double</code>
- support for units
- respect trick_io flags

**Comment by alexlin0** [comment]
The support for units and trick_io flags would make this a bigger change than I wanted.  I'm rejecting and closing this issue.
