### ISSUE TITLE
Why "Nested struct not currently supported (ignored)."

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1421]
Hello,
I am currently trying to build a model with nested structures. However this warning shows up and I dont know what to do `Warning 312: Nested struct not currently supported (ignored).`        
Also i looked up and it is swig related issue but my _swig_ version is _4.0.1_  where it's docs says after version 3 it is supporting the nested structures. Could you help me?

For better understanding, below is an example of my struct in my .h :
```
typedef struct {
     int x;
} S_DATA;

typedef struct{
    S_DATA s1;
    struct{
        void *timePtr;
    }POS_DATA;
}
/*And so on..*/
```

**Comment by jmpenn** [comment]
In your example, I have a couple of comments:

1) The second typedef struct has no name.
2) The following seems cleaner to me and more likely to be supported by SWIG.

```
typedef struct {
     int x;
} S_DATA;

typedef struct{
    void *timePtr;
} POS_DATA;

typedef struct{
    S_DATA s1;
    POS_DATA pos_data;
} ALL_DATA ;
```

Beyond this, I not sure that we can can help.

**Comment by Fjolnirr** [comment]
Hey thanks for your reply,     
1- I just forgot to add name to second typedef struct while commenting sorry about that.       
2- Your version is of course cleaner however, i actually dont write the source code it is a matlab generated code and i dont think i should change the code manually.
