### ISSUE TITLE
QUESTION: Is multiple sim models usage possible?

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1423]
Hello,

I have finished the trick tutorials where a single sim object used throughout the tutorial. However I am planning to use trick with **multiple sim models** communicating each other at each cycle.        
For example;
Lets say we have a **cannon** object and a **ball** object where both of them has their own params. So, the cannon fires the ball and keeps tracking the ball in y direction _**which is depending on the balls current state on height parameter.**_ 

What I am asking is how 2 (or more) different sim objects can be used and communicate among them with trick?

*(I have also started to review the docs. I guess running 2 different sim separately and using variable_server for sending and reading datas is one possible way but I may be wrong)*

**Comment by jdeans289** [comment]
I'm not sure I completely understand your question, but you can have as many models in one sim as you want, and you can organize your code in any way you want. You could use the create_connections method in the S_define to give your sim objects pointers to one another, for example.

**Comment by jmpenn** [comment]
Once you've created instances of the sim objects, you can refer to their internals as normal.
create_connections runs immediately after the object have been instantiated.
Hope this helps

'''C++
/***********************TRICK HEADER*************************
PURPOSE:
    (Cannon Numeric)
LIBRARY DEPENDENCIES:
    ( ... stuff ...)
*************************************************************/

#include "sim_objects/default_trick_sys.sm"
##include "cannon/gravity/include/cannon_numeric.h"

class BallSimObject : public Trick::SimObject {
    public:
    BALL ball;

    BallSimObject() {
        // <Ball Jobs>
    }
}

class CannonSimObject : public Trick::SimObject {

    public:
        CANNON      cannon ;
        BALL*       ball_ptr;
        CannonSimObject() {
        // <Cannon Jobs>
        }
} ;

// *** Create instances of the sim objects 
BallSimObject ballSO ;
CannonSimObject cannonSO ;

IntegLoop dyn_integloop (0.01) ballSO;

void create_connections() {
    
    // *** create_connections runs right after the sim objects are instanciated. 

    // *** example of connecting the objects :
    cannonSO.ball_ptr = &ballSO.ball;         

    dyn_integloop.getIntegrator(Runge_Kutta_4, 5);
}
'''

**Comment by Fjolnirr** [comment]
Thank you guys. That's what i was looking for. 

For anyone else with the same question.
create_connections can be found here in the docs :
https://nasa.github.io/trick/documentation/building_a_simulation/Simulation-Definition-File
