### ISSUE TITLE
Cannot find trick.tlc file used in MATLAB tutorial

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1426]
Hi,
In the FAQ i saw MATLAB can create trick friendly code. And watched the video however, I cannot find trick.tlc file used in MATLAB-Trick tutorial. My question is if trick.tlc exists or should I write one?

**Comment by jmpenn** [comment]
As I think I said in #1438, we don't really know about what Mathworks/Matlab/Simulink folks are doing to create code that works on Trick. You'll simply have to ask them.
