### ISSUE TITLE
var_byteswap mode doesn't work

### ISSUE THREAD

**Issue by jdeans289** [nasa/trick#1439]
When running the variable server in binary mode with byteswap enabled, the values sent are incorrect. The message header, types, and sizes of the variables are swapped correctly, but the values themselves are either not byteswapped or completely incorrect. The culprit is [trick_bswap_buffer](https://github.com/nasa/trick/blob/master/trick_source/trick_utils/comm/src/trick_bswap_buffer.c#L17), which appears to have been built to swap the entirety of a struct, or maybe just assumes an older structure of the ATTR that doesn't always apply anymore. This function either doesn't do anything, swaps garbage memory, or segfaults. 

This issue can be closed when:
1. Byteswap mode is fixed
2. The BinaryByteswap test in SIM_test_varserver is enabled and passing
3. Additional unit or integration tests are written as necessary

**Comment by alexlin0** [comment]
Hmm, I created my own fix as well and created a pull request based on the old variable server code.  I guess we can delete mine if it isn't needed.

**Comment by alexlin0** [comment]
Let's continue this conversation to #1514
