### ISSUE TITLE
Unit tests failing on the Mac.

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#144]
The X11 library directory moved in El Capitan.  Adjust for it.

**Comment by alexlin0** [comment]
In the long term we need to do this in the configure script and it's output.

**Comment by mtnmts** [comment]
Hi Alex,
does NASA accept pull request on these projects in case anyone wants to help and fix bugs/issues or implement new features?.
or is there no unified policy and it is per project?.

Thanks.

**Comment by alexlin0** [comment]
There is no unified policy.  Our project is willing to accept pull requests.  Please create one and we'll take a look at it.
