### ISSUE TITLE
QUESTION: How to order simulation jobs according to the simObject we created?

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1442]
Hello,

I want to know how can I order jobs? Here, the loop I want to execute; _(Outputs and inputs handled inside the source)_
- I want to send outputs of CannonSimObject to BallSimObject
- After that execute the BallSimObject 
- Then send outputs of BallSimObject to CannonSimObject
- Finally execute the CannonSimObject
- Repeat every 0.01 seconds.

**Basically, I want to run `cannon_step` before `ball_step` throughout the simulation.**

I have something like this below in my S_define:      
```
/***********************TRICK HEADER*************************
PURPOSE:
    (Cannon Numeric)
LIBRARY DEPENDENCIES:
    ( ... stuff ...)
*************************************************************/

#include "sim_objects/default_trick_sys.sm"
##include "cannon/gravity/include/cannon.h"

class BallSimObject : public Trick::SimObject {
    public:
    BALL ball;
    CANNON* cannon_ptr;

    BallSimObject() {
        // <Ball Jobs>
       ("initialization") ball_initialization(&ball, cannon_ptr);
       (0.01, "scheduled") ball_step(&ball, cannon_ptr);
    }
}

class CannonSimObject : public Trick::SimObject {

    public:
        CANNON      cannon ;
        BALL*       ball_ptr;
        CannonSimObject() {
        // <Cannon Jobs>
       ("initialization") cannon_initialization(&cannon, ball_ptr);
       (0.01, "scheduled") cannon_step(&cannon, ball_ptr);
        }
} ;

// *** Create instances of the sim objects 
BallSimObject ballSO ;
CannonSimObject cannonSO ;

void create_connections() {
    // *** create_connections runs right after the sim objects are instanciated. 

    cannonSO.ball_ptr = &ballSO.ball;      
    ballSO.cannon_ptr = &cannonSO.cannon;   
}
```

**Comment by jdeans289** [comment]
Job phasing: https://nasa.github.io/trick/documentation/building_a_simulation/Simulation-Definition-File#job-phasing
Job ordering: https://nasa.github.io/trick/documentation/building_a_simulation/Simulation-Definition-File#specifying-scheduled-loop-job-class-order

**Comment by Fjolnirr** [comment]
I have tried the ordering and it is working well. But I didn't know that we could do this: _(changing the "scheduled" with any string resulting as job_class I thought user defined job_classes should be defined somewhere else first.)_
```
(0.01, "ball2cannon") ball_step(&ball, cannon_ptr);
// ...
(0.01, "cannon2ball") cannon_step(&cannon, ball_ptr);
// ...
job_class_order{
    cannon2ball,
    ball2cannon,
    scheduled
};
```
However I get this **warning** :         
`|L   2|2023/01/31,09:47:48|ubuntuVm| |T 0|0.000000| Warning: Job trick_vs.vs.copy_data_scheduled of job class "automatic_last"is not handled by any scheduler`

And this is the phasing way and it is also working without warnings;
```
P2 (0.01, "scheduled") ball_step(&ball, cannon_ptr);
// ...
P1 (0.01, "scheduled") cannon_step(&cannon, ball_ptr);
// ...
```

If the warning is not important we can close this issue.

**Comment by jmpenn** [comment]
The reason you're getting a warning is that neither "ball2cannon", or "cannon2ball" names a valid job class.
