### ISSUE TITLE
variable server and arrays

### ISSUE THREAD

**Issue by stephenmontgomerysmith** [nasa/trick#1444]
In older versions of trick, if I send the variable server:
trick.var_add("sim.array")
and sim.array has type double[10], then the output is
0	0,0,0,0,0,0,0,0,0,0

But more recently the output is
0	0

Is this a feature or a bug?  Could we go back to the older behavior?

An example of an older version is 19.2.2.

**Comment by jdeans289** [comment]
Hi, thanks for pointing this out. This appears to be an unintended consequence of a recent change. We'll get a fix out soon, I'll let you know here.

**Comment by jdeans289** [comment]
This should be fixed on the master branch now, let me know if you get a chance to test it out!

**Comment by stephenmontgomerysmith** [comment]
Thank you.  It is working for me.

________________________________
