### ISSUE TITLE
Redundant Python aliases

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#145]
SIM_*/trick/sim_services.py has a lot of entries like the following:

```python
def attach_units(*args):
    return _sim_services.attach_units(*args)
attach_units = _sim_services.attach_units
```

The final assignment renders the function definition useless, right? We should eliminate this redundancy and keep only the alias.

**Comment by alexlin0** [comment]
I've looked to where this code is.  This code is auto-generated by swig, not us.  I doubt we can do anything about it.  Sorry.  Ready to close
