### ISSUE TITLE
Arrays of typedef'ed named structs cause SEGFAULTs on Python access

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#146]
``` c++
typedef struct FooStruct {} Foo;
typedef struct {} Bar;

class Baz {
    public:

    struct FooStruct fooStruct;
    struct FooStruct fooStructs[2];

    Foo foo;
    Foo foos[2];

    Bar bar;
    Bar bars[2];
};

Baz baz;
```

``` python
# input.py
print baz.fooStruct       # OK
print baz.fooStructs[0]   # OK
print baz.foo             # OK
print baz.foos[0]         # SEGFAULT
print baz.bar             # OK
print baz.bars[0]         # OK
```

**Comment by alexlin0** [comment]
I tested this with SWIG 2.0.10 and I get a segfault.  Using 3.0.8 the segfault goes away. But even using 3.0.8, the type information for foos is not as complete as the other print statements.  There isn't much else we can do in Trick... if I close my eyes long enough this problem goes away, right?

**Comment by alexlin0** [comment]
Too old and too rare of a case.  Closing this issue not fully resolved.
