### ISSUE TITLE
VS_COPY_SCHEDULED fails unexpectedly when using custom job class order

### ISSUE THREAD

**Issue by cameronbracco** [nasa/trick#1460]
When specifying a [custom job class order](https://nasa.github.io/trick/documentation/building_a_simulation/Simulation-Definition-File#specifying-scheduled-loop-job-class-order), the documentation states that all job classes "between automatic and automatic_last inclusive" are open for re-assignment.

If a user does not explicitly include the `automatic_last` job class in their custom job class order, variable server clients attempting to use  `VS_CODE_SCHEDULED` will fail to receive any data and an error will be printed in the simulation process:
```
Warning: Job trick_vs.vs.copy_data_scheduled of job class "automatic_last" is not handled by any scheduler
```

The default job class for this copy mode is set at https://github.com/nasa/trick/blob/master/share/trick/sim_objects/default_trick_sys.sm#L459.

Is there a reason to not use the `end_of_frame` job class to avoid this issue?

If the use of `automatic_last` intentional, I would recommend updating the documentation for [copy mode scheduled](https://nasa.github.io/trick/documentation/simulation_capabilities/Variable-Server#end-of-main-thread-execution-copy-mode--trickvscopyscheduled-or-1) to include a warning note, and if not, I would propose changing the default job class assigned.

**Comment by jdeans289** [comment]
`VS_COPY_SCHEDULED` has to be an automatic job class because its cycle is not necessarily the same as the executive cycle. If you would like the copy to align with the frame, use `VS_COPY_TOP_OF_FRAME`.

This is definitely a bug, I'll look into it and hopefully patch it soon and follow up here. Until then, `VS_COPY_TOP_OF_FRAME` should be unaffected by this issue.

**Comment by jdeans289** [comment]
This should now be resolved on master.
