### ISSUE TITLE
Broken links in How-To-Guides

### ISSUE THREAD

**Issue by ivanperez-keera** [nasa/trick#1478]
All links in the How to guides TOC file are broken (at least on Github).

To reproduce the error, go to:
https://github.com/nasa/trick/blob/master/docs/howto_guides/How-To-Guides.md

and click on:

"[How to Containerize Trick with Docker](https://github.com/nasa/trick/blob/master/docs/howto_guides/How-To-Containerize-Trick-with-Docker)"

It should take you to:

https://github.com/nasa/trick/blob/master/docs/howto_guides/How-To-Containerize-Trick-with-Docker.md

but instead takes you to the path without the `.md` extension:

https://github.com/nasa/trick/blob/master/docs/howto_guides/How-To-Containerize-Trick-with-Docker

which returns a 404.

The links are broken for two independent reasons:
1. Not having an extension in the filename (i.e. `.md`). This applies to all links.
2. Pointing to `/trick` instead of `/trick/docs`. This applies only to the links to:
    - [Input File Quick Reference](/trick/not_referenced/Input-File-Quick-Reference)
    - [How do I create a model library to save compilation time?](/trick/documentation/building_a_simulation/Trickified-Project-Libraries)

A quick fix to (2) would be to replace `/trick` with `..` in the links, which fixes the issue at least on github.

**Comment by spfennell** [comment]
@ivanperez-keera the docs are not meant to be viewed from the github source browser. They are hosted at [https://nasa.github.io/trick](https://nasa.github.io/trick). You can git to these docs easily by clicking any of the links or the logo in the readme on the home page of the repo. All of the links in How-To-Guides will work from [https://nasa.github.io/trick/howto_guides/How-To-Guides](https://nasa.github.io/trick/howto_guides/How-To-Guides)

**Comment by ivanperez-keera** [comment]
Thanks for the clarification.
