### ISSUE TITLE
HDF5 Library Installed in Non-Default Location Causing Link Error

### ISSUE THREAD

**Issue by genti337** [nasa/trick#1481]
On an M1 Mac, the `hdf5` library was installed in a non-default location so the `--with-hdf5` option was used during the configuration step as seen below.

```
./configure --with-llvm=/Users/jmgentil/llvm13-aarch64/ --with-udunits=/opt/homebrew/Cellar/udunits/2.2.28 --with-hdf5=/opt/homebrew/Cellar/hdf5/1.12.2_2
```

This caused an issue during the compile because `-lsz` link did not exist.  I was able to resolve this issue by removing `-lsz` from [Makefile.common](https://github.com/nasa/trick/blob/8be3e30f7aaaceeb3f9c64813b6c9bc0399e4b2c/share/trick/makefiles/Makefile.common#L151) on line 151.

**Comment by hchen99** [comment]
Thanks for reporting this. Wondering if you've tried the latest hdf5 version 1.14 (`brew install hdf5` should install 1.14) and still need to remove `-lsz`. Tried `brew install hdf5@1.10` then configured trick with --with-hdf5, didn't experience any issue, however, I am on intel though. `brew install` doesn't have hdf5@1.12 for some reason. hdf5 package should come with szip. We'll try to test on M1 to see what happens.

**Comment by hchen99** [comment]
According to user comment https://github.com/nasa/trick/issues/1716#issuecomment-2133856078 , no need to remove `-lsz` if configuring hdf5 as `--with-hdf5=/opt/homebrew` on M1 Mac. Let us know if it doesn't work for you.
