### ISSUE TITLE
make fails on Deb11: No java compiler is provided.

### ISSUE THREAD

**Issue by mmcbroom** [nasa/trick#1490]
I get the following build error on Debian 11 for trick 19.5.1.  Note that  ./configure runs without error, which confirms that openjdk-11-jdk was installed properly.  
Also, I've confirmed java and javac are installed:

 javac -version
javac 11.0.18
[mmcbroom@ah-mmcbroom-l:/mathworks/devel/sandbox/mmcbroom/cinc_balsa/build/Test_System/Mains/EGI_main] ...                              % java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
[mmcbroom@ah-mmcbroom-l:/mathworks/devel/sandbox/mmcbroom/cinc_balsa/build/Test_System/Mains/EGI_main] ...                              % javac -version
javac 11.0.18

Here is the error. Attached are logs of make and configue.   Any ideas how to resolve?

== Trick data_products make complete ==
make[1]: Leaving directory '/mathworks/devel/sandbox/mmcbroom/Trick/trick-19.5.1/trick_source/data_products'
make[1]: Entering directory '/mathworks/devel/sandbox/mmcbroom/Trick/trick-19.5.1/trick_source/java'
Building java application...
[ERROR] COMPILATION ERROR : 
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project trick-java: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[config.log](https://github.com/nasa/trick/files/11310951/config.log)
[build.log](https://github.com/nasa/trick/files/11310952/build.log)

**Comment by jdeans289** [comment]
It looks like the `java` in your path points to a Java runtime environment, not OpenJDK. Make sure you have a JDK installed and pointed to by your system path, or by including the `--with-java=[directory]` flag on the configure step.

**Comment by mmcbroom** [comment]
Thanks for your quick response.

I tried:  ./configure --with-java=/etc/java-11-openjdk

I get a warning from configure:  WARNING: unrecognized options: --with-java

I also tried adding /etc/java-11-openjdk to system path.  In both cases, i get the same error as stated above.  Any other suggestions?

THanks.
Mark.

**Comment by jdeans289** [comment]
Sorry, the `--with-java` option was incorrect on my part.  Try setting your `JAVA_HOME` environment variable 

https://nasa.github.io/trick/documentation/install_guide/Install-Guide#environment-variables
