### ISSUE TITLE
QUESTION: Would it helpful to modify the monte carlo tutorial page?

### ISSUE THREAD

**Issue by garshaam** [nasa/trick#1502]
The tutorial is generally consistent and builds on itself to keep each section short and self contained. I am wondering if it would be helpful to modify the [monte carlo page](https://nasa.github.io/trick/documentation/simulation_capabilities/UserGuide-Monte-Carlo) in some of the following ways to keep that pattern:

-Base the test on the cannon_numeric simulation instead (or use the exact same cannon_analytic as before)
-Cut out redundant material showing a plot of one curve/test.
-Rename files to stay consistent (input.py vs test.py)

The page is alright as-is but if it would be helpful to modify it I can submit a revision. I am a bit new to open source projects so let me know if I am approaching this incorrectly.

**Comment by jdeans289** [comment]
Sure! We would appreciate the contribution. To make a contribution, fork the project, make your changes, and submit a pull request. We will review it and collaborate with you to incorporate your changes.

**Comment by jdeans289** [comment]
Closed by #1511 

Thanks again for your contribution!
