### ISSUE TITLE
trick run summary enhancement for memory used

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1504]
trick run summary enhancement for memory used.  It would be nice if the run summary told us how much RAM a sim used.  That could better help us size sim host for simulations to run on. 

From this 
`
SIMULATION TERMINATED IN
  PROCESS: 0
  ROUTINE: Executive_loop_single_thread.cpp:98
  DIAGNOSTIC: Reached termination time

       SIMULATION START TIME:        0.000
        SIMULATION STOP TIME:      300.000
     SIMULATION ELAPSED TIME:      300.000
        ACTUAL CPU TIME USED:        0.499
       SIMULATION / CPU TIME:      600.747
     INITIALIZATION CPU TIME:        0.129
`

To This
`
SIMULATION TERMINATED IN
  PROCESS: 0
  ROUTINE: Executive_loop_single_thread.cpp:98
  DIAGNOSTIC: Reached termination time

       SIMULATION START TIME:        0.000
        SIMULATION STOP TIME:      300.000
     SIMULATION ELAPSED TIME:      300.000
        ACTUAL CPU TIME USED:        0.499
       SIMULATION / CPU TIME:      600.747
     INITIALIZATION CPU TIME:        0.129
        SIMULATION RAM USAGE:    1,000.003 TB 
`

**Comment by jdeans289** [comment]
This is reasonable, we'll keep you posted.
