### ISSUE TITLE
trick-upgrade script

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1505]
It would be nice if there was a way for trick to recursively check( ether git bisect style or by trick version) a sim and it's runs for flat line deltas.  We might need to make a little json file to tell trick what runs and data files to check, but I think that would be very useful in helping groups upgrade and easy for projects to run this as a CI job once a month.   This would allow trick developers to better generate crash reports when a trick change might effect simulation compilation or a run time crash.

**Comment by sharmeye** [comment]
This sounds like you are asking Trick to include a validation button for any and all previous versions of Trick, and that sounds like something that is better handled by the user of the sim and not the architects of the toolkit.

I'm sure you'll agree, upon reflection.

**Comment by sharmeye** [comment]
I feel that perhaps you have not reflected long enough

**Comment by amishscientist** [comment]
You are absolutely right @sharmeye I don't know what I was even thinking.   I know what I need to do now.  https://youtu.be/79DijItQXMM

**Comment by amishscientist** [comment]
Just so you know after you change your mind about this I'm going to install one of these in your cube https://www.amazon.com/dp/B083W4Y6N8
