### ISSUE TITLE
PAPI performance counter enhancement 

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1506]
While tricks frame logging helps you with the amount of time a job may have taken it would be nice if we had a better way to align the work trick is doing with cpu counter registers.  I would highly recommend the PAPI api over trick trying to talk to the registers directly.   A lot of time when I have an over run in a sim I have to figure out if the sim is being asked to do the same amount of work from frame to frame.  Getting access to the cpu register that holds the instruction count could provide some insight into this problem. https://icl.utk.edu/projectsdev/papi/docs/de/d04/papiStdEventDefs_8h_source.html PAPI_TOT_INS

**Comment by jdeans289** [comment]
https://opensource.guide/how-to-contribute/

**Comment by amishscientist** [comment]
It's in the queue right after I finish this [one](https://github.com/rocky/remake/issues/126).
