### ISSUE TITLE
QUESTION: dependencies for older releases of Trick

### ISSUE THREAD

**Issue by cordovaTX** [nasa/trick#1507]
I have Trick 17. I can ./configure alright, but when I make, I get:

Building Trick GUIs...
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/jcommon-1.0.23.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/jopt-simple-4.8.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/hamcrest-core-1.3.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/jfreechart-1.0.19.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/jfreesvg-2.1.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/fontbox-2.0.11.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/bsaf-1.9.2.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/junit-4.12.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/pdfbox-2.0.11.jar; zip END header not found
error: error reading /home/lcordova/code/packages/trick/libexec/trick/java/lib/swingx-1.6.1.jar; zip END header not found

I think maybe I'm using the incorrect version of java for this Trick version. How can I figure what version to use?

**Comment by jdeans289** [comment]
This doesn't look like a Java version issue. Maybe try re-cloning or a `git clean -xdf` and rebuilding from scratch.

**Comment by cordovaTX** [comment]
That had been the first thing I tried.

**Comment by sharmeye** [comment]
I suspect what's happening here is that hard-coded paths in Trick 17 for these java dependencies are no longer valid.  These issues are resolved in Trick 19.

**Comment by cordovaTX** [comment]
This is fixed now. This is a problem that was fixed in later versions of Trick. I got the fix from looking elsewhere on this website.

- cd /trick/libexec/trick/java/lib;
- make clean                         // Remove all the jar files
- vi Makefile                        // Convert all http to https
- cd /trick
- make clean
- ./configure
- make
