### ISSUE TITLE
Trick log messages written on separate thread flag enhancement

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1508]
On AA2 Alex gave us a way for trick to write the messages out on a separate thread. But it wasn't very intuitive on how to turn that feature on.  

Looking at our old AA2 input files It looks like this is what we had to put in to make it do it. 

`

trick.message_unsubscribe(trick_message.mcout)
trick.message_unsubscribe(trick_message.mdevice)
trick_message.mtcout.init()
trick.message_subscribe(trick_message.mtcout)
`

**Comment by sharmeye** [comment]
This seems reasonable, and we will implement this as time allows.
