### ISSUE TITLE
Build metrics

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1509]
It would be nice if trick gave out some build metrics. On the different phases of the trick build.  That might give simulation builds a better idea of how to speed up their build times.

**Comment by jdeans289** [comment]
Are there specific metrics that you would like to see?

**Comment by amishscientist** [comment]
It would be nice to know how much of the build time was spent doing trick things like ICGing files and making swig files vs compiling. I don't really remember all the things that trick-CP is doing. 

In the past I have used tools like the swig version of ccache https://www.swig.org/Doc4.1/SWIGDocumentation.html#CCache for speeding up builds because it caches both the swig files and the object files unlike the normal ccache. and tools like remake https://bashdb.sourceforge.net/remake/ to profile the actual make recipes time.    In most cases to know how long a build takes people just wrap the build with a /usr/bin/time -v to get how long the build took and what was the cpu usage, but getting incite into what a user can do to speed up a build is often hard.

**Comment by jdeans289** [comment]
We're looking at refactoring the build process. This is the sort of thing we may address at that time.
