### ISSUE TITLE
add a legit time variable

### ISSUE THREAD

**Issue by lordmundi** [nasa/trick#151]
So many external utilities need to use simulation time.  It really seems like there should be a variable to hold the time without causing every external utility to have to get two variables and divide them to get time.  This is a request to add a variable to hold the current sim time in it so that utilities that get variables over the variable server but don't easily give you a way to post-process the data can still get and use the sim time.

**Comment by alexlin0** [comment]
The time tics we use is the legit time.  It may not be human friendly, but it is faster and more accurate than a decimal representation of the time you're asking for.  I've had a debate with myself if I should a decimal variable representation of the time be included with Trick.  I've always concluded that we don't need it in the executive.  But maybe we can add a variable in the variable server that each variable server thread updates.  I'll have to think about it a bit.

**Comment by alexlin0** [comment]
Added some documentation to the wiki about the new "time" parameter available through the variable server. https://github.com/nasa/trick/wiki/Variable-Server#adding-a-variable

**Comment by lordmundi** [comment]
awesome... thanks for looking at this.

so, i'm a little confused about what exactly it returns.  You mentioned
"This time marks the simulation time at the start of the variable server's
task to copy variables."  Can you give me an example of what that means?
I'm guessing that 99% of people will want the simulation time.  Are there
cases where this will be different from the simulation time?

FG

**Comment by alexlin0** [comment]
Since the variable server is not in the main thread, time could advance on the main thread while the variable server thread is doing it’s work.  I’m just pointing out that I snapshot the simulation time at the beginning of the process of copying variable values.  It’s no different than what happens with the integer number of tics.

Alex

**Comment by lordmundi** [comment]
ahh... ok, so it IS sim time... you're just saying that the particular
value you get should be homogenous with all the values in that set...
meaning they are all consistent at that time.  Or, at least if is set to
synchronous... Correct?  If so, that is perfect.

FG

**Comment by alexlin0** [comment]
Yes, that is correct
