### ISSUE TITLE
Connan support

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1510]
It would be nice if trick could help work with Connan support.   [Connan](https://conan.io/) is a C++ package manager.   I think this would help reduce the number of submodules simulations tend to carry in their repos.   The issue is that Connan works with make and cmake but since trick builds the makefile I don't know if this can be done just in the S_overides file because of package headers that trick would need to pull down to parse.

**Comment by sharmeye** [comment]
The current Trick build process doesn't currently support interfacing with this type of system.  Additionally, no other users asking for this capability.

If requests of this nature become more frequent (from other, distinct, separate people - no astroturfing amishcientist), we will revisit the idea of implementing support for package managers like this in the future.
