### ISSUE TITLE
NameError: name 'trick' is not defined

### ISSUE THREAD

**Issue by pbhuter** [nasa/trick#1512]
I have worked through the cannon tutorial several times, trying different things, but always get the following error:

> NameError: name 'trick' is not defined

The things I have tried are:

1. Rebuild Trick
2. Start from scratch and redownload and rebuild Trick

I get the above error regardless, but when I include the input.py `trick.stop(5.2)`, Trick terminates the run with the following:

> SIMULATION TERMINATED IN
  PROCESS: 0
  ROUTINE: IPPython.cpp:139
  DIAGNOSTIC: Input Processor error

Without including the input.py, Trick runs indefinitely (makes sense with no stop time), but still mentions the 'trick' is not defined problem.

**Comment by jdeans289** [comment]
Can you provide more information on your OS, Python version, and SWIG version? Did you see errors during the build process?

**Comment by brownzach125** [comment]
Could you add this to the top of you input.py
```python
import sys
print(sys.path)
import trick
```
Which directory are you running from?

**Comment by pbhuter** [comment]
When I added those two lines, the error output was printing that it was trying to run things in Python 3.8. I uninstalled Python 3.8 and 3.9, and ran everything again, and it ran just fine. I'm not sure if Trick saw 3.8 first or what, but after uninstalling all other versions of Python, the Tutorial sim runs fine with Python 3.11.
