### ISSUE TITLE
Variable Server byteswapping crashes the sim

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#1513]
If you select the var_binary_nonames (or var_binary) and var_byteswap options on a variable server client, the code will byteswap too much data and will crash the sim.

**Comment by jdeans289** [comment]
This is a known issue ( #1439 ), and there is a fix rolled in with other major refactors of variable server on the branch [variable-server-refactor-beta](https://github.com/nasa/trick/pull/1493). It hasn't been pulled into master yet, but will be eventually.

**Comment by jdeans289** [comment]
Resolved with #1514
