### ISSUE TITLE
way to list python files that are processed in input stream

### ISSUE THREAD

**Issue by lordmundi** [nasa/trick#152]
often times when debugging where to put a change in the input stream when many different input files are included, you aren't sure which files to modify (for example, you want to change the real-time frame and you grep in the input files in the customer's sim and find 3 different files that set real-time frame but you aren't sure which one is being used in the currently running sim, or which one is included last).  

It would be helpful to have a way to query a running sim to know which python input files were used for the current running sim.  This could be either a button on the sim control panel or a sim variable that has all the strings in a list, or both.  If the files were shown in the order the files were imported it would be even more useful.

**Comment by alexlin0** [comment]
Would this work for you?

You can run the sim with the -d option to show all input file lines as they would be processed.

```bash
S_main.exe RUN_dir/input.py -d
```
This is very verbose, showing each line as it is executed including printing each iteration through loops.  I suggest redirecting the output to a file.  The sim does not run when the -d option is used, it only prints the input file and exits.

Underneath Trick uses the python <code>sys.settrace</code> function to create the -d printout.  You can use the settrace function in your sim input file to print input file lines and run the sim.

```python
# turn on debugging line by line printouts
sys.settrace(trick.traceit)
# lines in my_function will be printed as it creates a new scope
my_function()
# lines in the same scope as the settrace function will not be printed
a = 1
b = 2
# turn off debugging
sys.settrace(None)
```
Note: the settrace function will only start printing when a new local scope is entered, see above.

**Comment by lordmundi** [comment]
well, i don't have a specific use case in mind, so I'm sure that will be
helpful for folks looking for this.  In my particular case, I wasn't really
in a position to debug where lines were coming from, I just needed to get
some input added in quickly.  So, I was really referring to more of a
generic capability that folks could use from the sim control panel without
making any mods to the sim.  But, I understand that it might not be easy to
do.

Just a thought.

FG

**Comment by alexlin0** [comment]
Many new input files are moving to using modules. Yea!  I found this stackoverflow question that shows various ways to list out the modules loaded.  I tried a couple of the suggested answers and they do work.

http://stackoverflow.com/questions/4858100/how-to-list-imported-modules
