### ISSUE TITLE
Send_hs clock resolution enhancement 

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1521]
It would be nice if send_hs showed more resolution of the time in it's log messages

`|L   0|2023/06/12,13:32:42|cabaodaba| |T 0|0.000000| time =     0.00 , position =     5.000000 ,     5.000000`

It would be nice if the time showed in the log message was at least the same resolution as gettimeofday.  A computer can do a lot in a second so it is helpful to have a better understanding of the time between messages.

**Comment by jdeans289** [comment]
Sure would be

**Comment by amishscientist** [comment]
One can only dream https://github.com/nasa/trick/blob/bbe9768a30b2211ad1ead28927a52302b781190c/trick_source/sim_services/Message/MessagePublisher.cpp#L56

Maybe one day it will change to a get time of day call instead.  If we really want dream someone might even make some room in the header buffer for it https://github.com/nasa/trick/blob/bbe9768a30b2211ad1ead28927a52302b781190c/trick_source/sim_services/Message/MessagePublisher.cpp#L49
