### ISSUE TITLE
Trick View uses field of 32 zeros for integer and unsigned integer types

### ISSUE THREAD

**Issue by miltondean** [nasa/trick#1522]
In Trick version 17.4.0, the Value field for int and unsigned int types will display 32 digits of zero for the value zero.  For all of the other data types (i.e., float, double, unsigned short, unsigned char, signed short, signed char, long long int, long long unsigned int) the Value field will only show the minimal size required.  This seems like a bug.  When a user inserts a value into the Value field, if they don't remove all of the zeros, the leading 0 will indicate the value should be in Octal which in most cases is not what the user intended.  Updating the Value field display for uint32_t and int32_t to no longer display leading zeros will fix this issue.

![image](https://github.com/nasa/trick/assets/51464082/6f78fb2e-c196-42b2-ac04-8c4497a212f4)

**Comment by sharmeye** [comment]
I believe updating to Trick 19 will fix this for you, please let us know if that is not the case.  Trick 17 has not been maintained in some time.
