### ISSUE TITLE
QUESTION: Adding time varying boundary conditions to the input.py file

### ISSUE THREAD

**Issue by simtheverse** [nasa/trick#1526]
Is it possible to set sim variables via the input.py to follow a time series? For example, instead of just making an event that assigns a variable with a value at a time, it sets a variable each frame according to a predefined time series, perhaps like a ramp on a variable, or a sine wave or chirp, or sequence of steps etc. The idea is that the boundary conditions are loaded in during sim initialization from a separate database that has the definition for the simulation scenarios.

Thanks in advance!

**Comment by jmpenn** [comment]
I'm having trouble understanding exactly what you mean. Do you have some time series data (perhaps in a file) that you want to read into your sim, at specified times?

**Comment by simtheverse** [comment]
That is right. Can the variable server drive one of the sim variables from time series data? Is this something I can specify in the input.py file? (Perhaps any function calls that can accomplish: at sim time=100s, play time series data of [filename.csv (or perhaps data defined inline as a data structure)] on variable [trick.model.sim.variable1])

**Comment by alexlin0** [comment]
Users have done this using a periodic job, but not through the input file.  The job reads the next set of data from a file and set the variables.

**Comment by jmpenn** [comment]
Yep, like Alex said. I would write an initialization job to open the file, and then a scheduled job to read the values from the file and set the appropriate variables.

**Comment by simtheverse** [comment]
Ok thank you. I don't want it to be a permanent fixture of the simulation however. How would you suggest defining these jobs post compilation? I would like to have an upstream tool define if/when/which timeseries plays on a per run basis.

**Comment by jmpenn** [comment]
Perhaps you could write a variable server client ( perhaps in written in Java or Python) to 1) open and read  values from a file , and 2) connect to you sim and set the values at specific times. We have lots of examples of how to write variable server clients that get and set values. Start with the tutorial (section 11). Also look at the variables server clients for the example sims.

**Comment by simtheverse** [comment]
Thank you John and Alex for your insights. That gives me something to get started. If I could request a feature, it would be defining cyclic jobs via the python interpreter. Possibly just being able to change the internal parameters of the job from the python interpreter could be useful too (say I define a job with the behaviors of playing a time series in the S_define, and then in python at run time turn that job on/off and set which data to read and at what frame to start)

**Comment by sharmeye** [comment]
Well, from the input file you can turn jobs on and off, and if you set the path of the data to be read in a variable, you can update that from the input file as well.  Defining cyclic jobs from the input file is not functionality we intend to implement.
