### ISSUE TITLE
c++ instances allocated via MemoryManager do not call destructors when deleted

### ISSUE THREAD

**Issue by excaliburtb** [nasa/trick#1529]
Similar to https://github.com/nasa/trick/issues/1301 but for a different reason. I found that if I declare a c++ class using memory manager (i.e. TMM_declare_var_s for my specific test), the alloc_info instance that gets allocated to track it always has the allocation set for TRICK_ALLOC_MALLOC. Since that enum `TRICK_ALLOC_MALLOC = 0`, it's either a mistake and is just resulting to the default.. OR, allocations are intentionally tracked as MALLOC instead of TRICK_ALLOC_NEW for some reason. git grepping through the code, I see no attempt to set the alloc_type to anything except for the DataRecordGroup. So, it doesn't matter which API I use, Trick will never treat it as anything other than a malloc.

**Comment by sharmeye** [comment]
Thanks, we'll look into this and let you know.

**Comment by jmpenn** [comment]
It looks like we might have just overlooked adding  "alloc_type = TRICK_ALLOC_NEW"
in the two occurrences where we set "language = Language_CPP" in :

void* Trick::MemoryManager::declare_var(TRICK_TYPE type,std::string user_type_name, int n_stars, std::string var_name, int n_cdims, int *cdims); 

,in MemoryManager_declare_var.cpp.

I'll add this, and test to ensure that it works as intended.

**Comment by jmpenn** [comment]
Specifically, my proposed fix is:
In [MemoryManager_declare_var.cpp](https://github.com/nasa/trick/blob/master/trick_source/sim_services/MemoryManager/MemoryManager_declare_var.cpp)

After line 48, add:
TRICK_ALLOC_TYPE alloc_type;

After lines 128 & 141, add:
alloc_type = TRICK_ALLOC_NEW;
144: alloc_type = TRICK_ALLOC_NEW;

After line 158, add:
new_alloc->alloc_type = alloc_type;

**Comment by excaliburtb** [comment]
that looks good to me

**Comment by jmpenn** [comment]
Complication: It looks like the generated io_src allocation routine sometimes calls calloc, and sometimes it calls new. Need to do more digging.

**Comment by excaliburtb** [comment]
hmm.. isn't there a io_src_*_destruct routine that gets generated? can't we use those?
