### ISSUE TITLE
Trick_utils CMakeLists adds var_binary_parser as subdirectory

### ISSUE THREAD

**Issue by irowebbn** [nasa/trick#1531]
https://github.com/nasa/trick/blob/bbe9768a30b2211ad1ead28927a52302b781190c/trick_source/trick_utils/CMakeLists.txt#L29

`var_binary_parser` doesn't have a CMakeLists.txt., so this will cause a CMake error.

**Comment by jdeans289** [comment]
Thanks for pointing this out. You're correct that should not be here. Our CMake build is not currently working and is unsupported. We will address this when/if we revive the CMake build.
