### ISSUE TITLE
Trick deletes `log_data.py` if it's in a RUN_* directory

### ISSUE THREAD

**Issue by mcmuffin6o** [nasa/trick#1542]
Trick keeps deleting my `log_data.py` when I put it in my RUN_* directory. How do I prevent this?

**Comment by jdeans289** [comment]
When is the deletion happening? At trick-CP time, or make clean?

I would hypothesize that Trick is at some point doing something like `rm log_*` to clean out old logfiles and your script is getting caught in that. Does the same problem occur if you change the name?

**Comment by jdeans289** [comment]
The data recording utilities in Trick remove all files in the output directory matching `log_*`. Our suggestion is to change the name of the file.

**Comment by jdeans289** [comment]
Yeah, I agree that it's not ideal, but data logging filenames are based on a user-supplied variable, so there isn't an obvious simple solution to this. Maybe we could match on extensions. We have a refactor of some parts of data recording utilities underway, we will keep this problem in mind. Thank you for bringing it tor our attention!
