### ISSUE TITLE
Memory leaks in dllist.c

### ISSUE THREAD

**Issue by dandexter** [nasa/trick#1559]
File: trick_source/trick_utils/trick_adt/src/dllist.c

Line: 270
Issue: In function DLL_InsertBefore*(), if the 'pos' and 'list' variables are null then the function returns before freeing 'newpos' that was just allocated resulting in a memory leak.
FROM:
```c++
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
if (pos == NULL && list == NULL) {
    fprintf(stderr, "List and Position are NULL");
    return NULL;
}
``` 
TO:
```c++
if (pos == NULL && list == NULL) {
    fprintf(stderr, "List and Position are NULL");
    return NULL;
}
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
``` 

----------
Line: 302
Issue: In function DLL_InsertAfter*(), if the 'pos' and 'list' variables are null then the function returns before freeing 'newpos' that was just allocated resulting in a memory leak.

FROM:
```c++
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
if (pos == NULL && list == NULL) {
    fprintf(stderr, "List and Position are NULL");
    return NULL;
}
``` 
TO:
```c++
if (pos == NULL && list == NULL) {
    fprintf(stderr, "List and Position are NULL");
    return NULL;
}
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
``` 

----------
Line: 379
Issue: In function DLL_AddHead*(), if the 'list' variable are null then the function returns before freeing 'newpos' that was just allocated resulting in a memory leak.
FROM:
```c++
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
if (list == NULL) {
    fprintf(stderr, "List is NULL");
    return NULL;
}
``` 
TO:
```c++
if (list == NULL) {
    fprintf(stderr, "List is NULL");
    return NULL;
}
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
``` 

----------
Line: 412
Issue: In function DLL_AddTail*(), if the 'list' variable are null then the function returns before freeing 'newpos' that was just allocated resulting in a memory leak.
FROM:
```c++
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
if (list == NULL) {
    fprintf(stderr, "List is NULL");
    return NULL;
}
``` 
TO:
```c++
if (list == NULL) {
    fprintf(stderr, "List is NULL");
    return NULL;
}
DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));
```

**Comment by jmpenn** [comment]
I agree that there is a problem here, but it's not that the malloc needs to be moved. It's that the printf() and return statements inside the NULL checks are in fact **impossible** to reach. So, the error messages can never be printed.

Case of DLL_InsertBefore :
If (pos != NULL && list != NULL) is TRUE (line 264), 
then it's impossible for (pos == NULL && list == NULL) to be TRUE on 268.

The solution here is to remove the second if-block, and copy the printf() statement to just before the return() statement at the bottom.

So, the code should change FROM:
```
DLLPOS DLL_InsertBefore(DLLPOS pos, void *data, DLLIST * list)
{
    if (pos != NULL && list != NULL) {
        DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));

        if (pos == NULL && list == NULL) {   // POINTLESS
            fprintf(stderr, "List and Position are NULL");
            return NULL;
        }   

        newpos->info = data;
        if (pos->prev == NULL) {
            newpos->next = list->head;
            newpos->prev = NULL;
            list->head = newpos;
            pos->prev = newpos;
        } else {
            pos->prev->next = newpos;
            newpos->prev = pos->prev;
            newpos->next = pos;
            pos->prev = newpos;
        }   
        return newpos;
    }   
    return (NULL);
}
```

TO
```
DLLPOS DLL_InsertBefore(DLLPOS pos, void *data, DLLIST * list)
{
    if (pos != NULL && list != NULL) {
        DLLPOS newpos = (DLLPOS) malloc(sizeof(DLLNODE));

        newpos->info = data;
        if (pos->prev == NULL) {
            newpos->next = list->head;
            newpos->prev = NULL;
            list->head = newpos;
            pos->prev = newpos;
        } else {
            pos->prev->next = newpos;
            newpos->prev = pos->prev;
            newpos->next = pos;
            pos->prev = newpos;
        }   
        return newpos;
    }  
    fprintf(stderr, "List and Position are NULL");
    return (NULL);
}
```

The logic problems, and solutions are much the same for the remaining cases.

**Comment by jmpenn** [comment]
I've been writing some unit tests for dllist.c (doubly-linked list) in trick_utils/trick_adt. I've found and fixed numerous, serious bugs.  **I find it difficult to believe that anyone has been using this.** I'll spend a little more time to see whether it can be turned into something of value, but If it takes too long, I think I'm going to delete it.

**Comment by jmpenn** [comment]
Ok, Its looks like someone is using part of it, so I won't delete it, and I'll continue writing unit tests, and debugging it.
