### ISSUE TITLE
Overlapping source and destination in sprintf calls.

### ISSUE THREAD

**Issue by dandexter** [nasa/trick#1562]
File: trick_source/data_products/EQParse/eqparse_fillno.c
Line: 60
Issue: The source and destination buffers overlap for the snprintf() call. See http://www.gnu.org/software/libc/manual/html_mono/libc.html#Formatted-Output-Functions
```c++
snprintf(num, sizeof(numstr), "%s%c", num, ch);
``` 
-----
File: trick_source/data_products/fermi-ware/XY.c
Line: 4481
Issue: The source and destination buffers overlap for the sprintf() call. See http://www.gnu.org/software/libc/manual/html_mono/libc.html#Formatted-Output-Functions
```c++
sprintf(tempeq,"%s(%.12lf)",
    tempeq,
        curves[cnum].points[
            commonPtIndex[rrindex][tcnum]].y) ;
``` 
-----
File: trick_source/data_products/fermi-ware/XY.c
Line: 4488
Issue: The source and destination buffers overlap for the sprintf() call. See http://www.gnu.org/software/libc/manual/html_mono/libc.html#Formatted-Output-Functions
```c++
sprintf(tempeq,"%s%.12lf",
    tempeq,
        curves[cnum].points[ 
            commonPtIndex[rrindex][tcnum]].y);
```

**Comment by dandexter** [comment]
What's the plan for getting this fixed?

**Comment by sharmeye** [comment]
The fermi-ware files are not maintained by Trick, they are just included for convenience for the users.  For EQParse, this is pretty low impact on Trick as a whole so is not a particularly high priority.
