### ISSUE TITLE
swig-generated code won't compile on gcc 8.X with -Werror due to -Wstringop-truncation

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#1565]
First noticed when trying to build some Trick-based models with gcc 8.X, the warning signature appears in the SWIG-generated `*_py.cpp` files which looks like this:

```
build/<path>/math_utils_py.cpp:7133:22: warning: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying 10 bytes from a string of the same length [-Wstringop-truncation]
               strncpy(buff, "swig_ptr: ", 10);
               ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```
The code in question looks like this:
```c++
            if (ndoc) {
              char *buff = ndoc;
              strncpy(buff, methods[i].ml_doc, ldoc);
              buff += ldoc;
              strncpy(buff, "swig_ptr: ", 10);  // <-- this is the line that causes the warning
              buff += 10;
              SWIG_PackVoidPtr(buff, ptr, ty->name, lptr);
              methods[i].ml_doc = ndoc;
            }
```
In our project we use `-Werror -Wextra` which makes this warning fatal. We've been doing this for some time, but under `gcc` 4.8.5 this doesn't produce the warning, we only noticed it when moving to `gcc` 8.3.0.  Our workaround is to just also include `-Wno-stringop-truncation` with `-Werror` in `TRICK_CXXFLAGS`. 

I talked with @jdeans289 briefly about this and she said it'd be helpful to write up the details in an issue so it can be referenced later.

**Comment by sharmeye** [comment]
Thanks, we'll have to dig into this to see what it's actually complaining about.  This might be one of a whole host of gcc 8.x issues, so perhaps this will be resolved with a bunch of other issues at once.  We'll get looking and let you know.

**Comment by hchen99** [comment]
Tried on rocky8 with gcc 8.5.0, swig 3.0.12, and the latest Trick as of 4/10/24. Didn't seem to get the warning message. Please let us know if this is still an issue.

**Comment by ddj116** [comment]
Can confirm that with `gcc` 8.5.0 and `clang` 16 this issue has disappeared. This must have only been present for older versions of clang which we were using back in 9/2023. Closing issue, thanks!

**Comment by hchen99** [comment]
> Can confirm that with `gcc` 8.5.0 and `clang` 16 this issue has disappeared. This must have only been present for older versions of clang which we were using back in 9/2023. Closing issue, thanks!

Thanks for confirming. Good to know all the details. I also tested with clang 16.
