### ISSUE TITLE
Overloading of MemoryManager::delete_var() easily leads to unexpected result

### ISSUE THREAD

**Issue by dandexter** [nasa/trick#1567]
The Memory Manager delete_var() API is overloaded to take two different forms of a pointer:
```c++
int Trick::MemoryManager::delete_var (void *address);
int Trick::MemoryManager::delete_var (const char *var_name);
``` 

Because both arguments are pointers this can lead to a very unfortunate and difficult to debug situation if you do not explicitly cast the address of a pointer to 'void *'.

Below is an example of where I ran into this issue with the ExecutionConfigurationBase class that has a string variable of type 'char const *'.  If you forget to explicitly cast the 'S_define_name' address pointer to 'void *' the delete_var() API will take the pointer to be a pointer of a named Trick variable instead because it is of type  'const char *. Passing the address to 'S_define_name'  will compile just fine both with and without 'void *' so this mistake can not be found at compile time because of how the API was designed.

Since this code is in the destructor I would get a Trick memory manager error at simulation shutdown and the message would say it could not delete the sim-object because it does not exist and silently fail when it tried to delete a name that was actually a point to an address. This type of problem is very difficult to debug.

You do not have the API problem with the c-code because you add either a '_a' or '_n' to denote the API for either address or name making the calls explicit.
```c++
void TMM_delete_var_a(void* address);
void TMM_delete_var_n(const char* var_name);
``` 
Since the problem is with the c++ API I would recommend using std::string for the name case instead so that that can be cause at compile time. Another recommendation Is to made the function names unique like was done for the c-code (i.e. adding  '_a' or '_n')  Otherwise, debugging this is very difficult as the Trick MemoryManager silently fails when it treats an address pointer as a variable name.

Example:
```c++
public:
   char const *S_define_name; /**< @trick_units{--}
      Full path name in the S_define for this ExecutionConfiguration instance. */

ExecutionConfigurationBase::~ExecutionConfigurationBase()
{
   if ( this->S_define_name != NULL ) {
      if ( trick_MM->is_alloced( const_cast< char * >( this->S_define_name ) ) ) {

         // Works: Simple c-style cast to 'void *'
         trick_MM->delete_var( (void *)this->S_define_name );

         // Just pass the pointer as is without casting to 'void *'.
         // Trick memory manager error at shutdown.
         // MemoryManager:ERROR:Cannot delete variable "THLA.ExCO" because it doesn't exist.
         //trick_MM->delete_var( this->S_define_name );
      }

      this->S_define_name = NULL;
   }
}
```

**Comment by dandexter** [comment]
Thanks for addressing this. It looks like the variable name string in the delete_extern_var function call is being passed in by value. Have you considered passing the variable name string by reference so that a copy of the string is not created resulting in better performance. Also, if the variable name string is not going to be modified then making it const would also be good.

```c++
// FROM:
int delete_extern_var(std::string var_name);

// TO:
int delete_extern_var(std::string const &var_name);
```

**Comment by sharmeye** [comment]
Maybe we'll tackle those extra performance improvements on the next pass.  As is, I'm closing this one as resolved.
