### ISSUE TITLE
make javadoc broken

### ISSUE THREAD

**Issue by alexenos** [nasa/trick#159]
> make javadoc
make[1]: Entering directory `/home/dgarner/Projects/trick/trick_source/java'
make[1]: *** No rule to make target `javadoc'.  Stop.
make[1]: Leaving directory `/home/dgarner/Projects/trick/trick_source/java'
make: *** [javadoc] Error 2

I had to create a javadoc target in the trick_source/java/makefile that just pointed to all for it to complete successfully.

**Comment by alexlin0** [comment]
Closing this issue because the documentation builds now.
