### ISSUE TITLE
In my humble opinion there are two kinds of overruns

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1591]
The first kind of overrun occurs when the jobs overruns and the second when JOB_trick_real_time.rt_sync.rt_monitor when the rt_nap over sleeps causing an overrun.  While both of these are still effected by the Linux fair scheduler.  It would be help to tell users when they have job overruns so they can address them much quicker.  We know how to address the rt_nap over runs by turning off the nap and running the main thread on an isolated cpu.  It does require root to isolated cpus which makes it a much harder thing for an average user to do on a box to check quickly.

**Comment by hchen99** [comment]
This issue is addressed by #1643 and #1644.

**Comment by sharmeye** [comment]
In my humble opinion, starting an issue with the phrase "In my humble opinion" is the best way I can think of to get an issue auto-closed with prejudice.

With all humility,
The Trick Team
