### ISSUE TITLE
Using environmental variable in S include

### ISSUE THREAD

**Issue by simtheverse** [nasa/trick#1596]
Hello, are environmental variables supported in paths for S includes? I haven't been able to get it to build with them.

```
Parsing    S_define
S_define:33:10: fatal error: ${HLA_FEDERATION_FILES_PATH}/S_modules/THLA_interface.sm: No such file or directory
 #include "${HLA_FEDERATION_FILES_PATH}/S_modules/THLA_interface.sm"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Error in S_define. Exit!
```

**Comment by alexlin0** [comment]
Environment variables are not supported.  Add the path to TRICK_SFLAGS in the S_overrides.mk.  SFLAGS acts like CFLAGS for S_define files.

`TRICK_SFLAGS += ":${HLA_FEDERATION_FILES_PATH}"`

Change your include line to

`#include "S_modules/THLA_interface.sm"`
