### ISSUE TITLE
interrupt the loop and continue where it left off

### ISSUE THREAD

**Issue by tastangh** [nasa/trick#1597]
Hello,
I am making a NASA trick real-time simulation. On the NASA trick side, I take the data coming from the vehicle with simulation, process it in my algorithms, and send it back to the vehicle. In order to ensure synchronization and real-time, I keep my simulation waiting until the data arrives in the first frame after initialization, but when my vehicle software sometimes does not work and I want to press the freeze button in the meantime, I cannot make it continue from the while loop by putting an interrupt in the while loop, doing freeze, and then click the start button. Is there any solution to this issue? Can the while loop be stopped within the task using freeze during a single task outside the main task loop and continue from the same place?

![trick](https://github.com/nasa/trick/assets/54810017/388348cd-cf97-453b-9790-de3418ad3b1a)

**Comment by alexlin0** [comment]
Sorry, but there is no mechanism to freeze and resume at the same point during the while loop.  You can make your ReadData routine a blocking read so that it will not return until you have received data.  That is probably the closest behavior to freezing at that point.

**Comment by tastangh** [comment]
When it freezes while waiting for data during the while phase, I cannot shutdown and I close the trick with sudo losf - i: port number and sudokill PID command every time. Is there a solution to this?

**Comment by alexlin0** [comment]
Try the trick-killsim command.
