### ISSUE TITLE
Compile time error in include/trick/Event.hh

### ISSUE THREAD

**Issue by dandexter** [nasa/trick#1601]
Latest version of Trick in the repo: [80f341f]
Apple clang version 15.0.0 (clang-1500.0.40.1)
MacOS 13.6.1, Intel

In file included from /Users/ddexter/projects/Trick/trick/include/trick/files_to_ICG.hh:10:
include/trick/Event.hh:206:39: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
struct CompareEventPtrs : public std::binary_function<Trick::Event *, Trick::Event *, bool> {
                                 ~~~~~^~~~~~~~~~~~~~~
                                      __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^

**Comment by alexlin0** [comment]
I've seen this too.  binary_function is being deprecated.  This struct and functionality will need to be replaced.

**Comment by hchen99** [comment]
Please see #1578

**Comment by sharmeye** [comment]
We addressed this in a recent commit, please let us know if the current master branch doesn't solve this problem for you.
