### ISSUE TITLE
Multiple Issues with Ubuntu install

### ISSUE THREAD

**Issue by bturrie** [nasa/trick#161]
The biggest issue is that the instructions for Ubuntu refrence 14.10 which is no longer supported.

In the LTS version 64 bit 14.04 the following was necessary
 
1. Normally Ubuntu does not enable root access you must either add a root password

sudo passwd root

then enter the new root password

or proceed all commands with sudo

2. The command to install java is incorrect. It should be:

sudo apt-get install openjdk-7-jdk

3. We needed to add symlinks in /usr/lib/lvm-3.4/bin to clang and clang++ as follows:

 sudo ln -s /usr/bin/clang /usr/lib/llvm-3.4/bin/clang
 sudo ln -s /usr/bin/clang /usr/lib/llvm-3.4/bin/clang
 
 4. curl was not installed on stock our system. We needed to add:
 
 sudo apt-get install curl
 
 5. It seemed that the gcc and g++ flag settings were needed on this  64 bit Ubuntu system to avoid errors like this in Make:
 
 /usr/lib/gcc/x86_64-linux-gnu/4.9/include/adxintrin.h:45:12: error: use of undeclared identifier '__builtin_ia32_addcarryx_u64'
 
 The missing vector functions should be available with msse2, setting the flags it did not seem to help eliminate the make errors. 
 
6.  The tutorial says to start by running the install_user script. but there is no such script. Perhaps that's because of the make errors and perhaps there's another issue.

Upgrading to Ubuntu 15.04 (14.10 is out of support and upgrades are not permitted) did not help

Here's the configure script I used:

cd ~/Desktop/Trick/trick-master
#!/bin/bash
TRICK_CC="/usr/bin/gcc"
TRICK_CPCC="/usr/bin/g++"
CFLAGS="native"
CXXFLAGS="xvector"
sudo ./configure --with-llvm=/usr/include/llvm --prefix=/usr/local

**Comment by alexlin0** [comment]
Thanks for the input.  

I updated the install instructions to use sudo.  I added curl to the list of packages to install. And I fixed the apt-get command for openjdk.

I have a symbolic link on my 15.05 system from /usr/bin/clang to ../lib/llvm-3.6/bin/clang.  I can't remember if my system did this for me, or did I do this manually and forgot that I did.  I need to investigate.

In 15.04 the clang version (3.6) does not display the errors that clang 3.4 did.  The errors are not fatal to Trick's operation.  We're telling users to update clang to remove those errors.

The install_user script was removed.  We need to update the documentation to reflect this.

**Comment by alexenos** [comment]
I too had to create sym links for clang a similar place

**Comment by alexlin0** [comment]
For Ubuntu 15.04 I added instructions to use clang 3.6.  Installing all of the packages listed in the wiki will install the symbolic link to clang.

Ubuntu 16.04 is coming out later this month, 16.04 presents a new set of challenges with clang.

The tutorial is currently being updated to be part of the wiki and is being tracked under #217 .  We are updating the content to match how to use Trick today, a lot has changed since the tutorial was last edited.

I'm ready to close this issue.  If there are no comments within a reasonable amount of time I will close it.

**Comment by alexlin0** [comment]
OK, I'm closing this issue now.
