### ISSUE TITLE
QUESTION: How can i start making changes on trick source code?

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1610]
Hello,

I would like to add a small feature to trick source but I am not sure where to start. 
It takes lots of time to make the trick as mentioned in installation guide and I don't think that for every bit of change requires full make of the trick(or is it?). 
I wonder, how your development environment looks like and what is your approach to debug and develop?

**Comment by hchen99** [comment]
Thanks for being willing to contribute. Every change goes through make. Please use our install guide for trick environment setup. People submit PRs with the changes made and we'll review to determine whether to accept the requests.

**Comment by Fjolnirr** [comment]
Which IDE do you recommend? How can I debug the source code? any suggestions would be great help to me.
