### ISSUE TITLE
QUESTION:  Are there any database and visualization software you can recommend for simulation?

### ISSUE THREAD

**Issue by tastangh** [nasa/trick#1615]
Hi Everyone,

I am making a NASA trick real-time simulation. I want to write all the data in the real-time simulation (such as the pos[] values in the tutorial) to the database in real time and visualize these values in real-time from Grafana. In this way, I aim to visually follow the values in the vehicle simulation I made. Are there any database and visualization software you can recommend for this process?

Best Regards,

**Comment by hchen99** [comment]
Check out koviz at https://github.com/nasa/koviz that works with Trick logged data directly and I heard it has real-time feature or it's been in development. Trick itself also comes with Data Products that allows visualization of Trick recorded data as you might already know through command "trick-dp"

**Comment by sharmeye** [comment]
As for visualization tools, we don't have any preferred software.  Oftentimes visualization tools use variable server connections to drive visualizations states from the sims.
