### ISSUE TITLE
Question : How to round trick view value

### ISSUE THREAD

**Issue by tastangh** [nasa/trick#1616]
Hello everyone,
I am making a real-time simulation. During this simulation, I observe the data via trick_view. While observing the data, I want to see the data rounded to the nearest value, for example, I want the values ​​in the example below to appear on the view screen as 77.51, 7.44, 43.30, 29.03. While making this request, I want the variable type in the header or the data type used in my algorithm not to be changed, that is, it should be calculated as 77.50927363870733 in my algorithm and simulation, but it should appear as 77.51 on the view screen. Is there a way to do this easily?
![tastangh](https://github.com/nasa/trick/assets/54810017/1b43d384-e98a-4da8-9398-d2d3d22261a0)

best regards,

**Comment by hchen99** [comment]
I don't believe so.
