### ISSUE TITLE
Confused about debugging the trick source code 

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1619]
Hello,

I would like to develop a feature for Nasa Trick software according to my needs where I need to record datas to MongoDB on sim run time. Just like DataRecord service records data to .csv. I will use this data to real-time plot on a react based frontend. I have developed C++ project for mongodb connections and crud operations but I am not sure how can I implement it to trick. I don't know how to debug trick source code.  My working environment is Ubuntu 22.04 and I am using Vscode(with makefiletools extension). 

What I have tried so far is:

1. I wasn't able to use cmake to build source code. So I am using make.
2. I thought about attaching to the process. Created an S_main_Linux_11.4_x86_64.exe file from cannon_analytics example and tried to attach it. But my debug points (even though they are called in an input file such as dataRecord.add_variable()) are not entered. However when I shutdown the S_main_Linux_11.4_x86_64.exe my debugger waits for me to step in. 

I am very confused about whether I am wrong about the debugging approach or am I facing IDE's environment settings or debugging issues. But I am able to debug my other C++ projects with the current settings.

I have looked through the documentations but I could not resolve the issue by myself. Would you help me to find out how can I debug Nasa Trick source?

**Comment by tastangh** [comment]
Hello everyone,

I am developing a code that writes simulation values ​​to influxdb and visualizes the data in Grafana. I could not debug the trick source code in VsCode either. If you solve the problem, I would be happy if you write it as an answer.

**Comment by GITburakdeniz** [comment]
Hi, I have been trying to debug the NASA Trick source for a while. On my other C++ projects, I use GDB for debugging which can be used for breakpoints but for NASA Trick can't figure out how to debug. I planned to develop a new feature for NASA Trick to use in simulation time but couldn't add the feature to the source.

@Fjolnirr @tastangh @  If you can figure out how to debug, Could you share it with me?

**Comment by Fjolnirr** [comment]
I have managed to debug whole trick code. Trick sources(services), trick ICG, and simulation model source codes. 
I will explain what you need to do to debug trick step by step.

1. First you need to add this lines to the `Makefile` of the trick located at `trick/Makefile` 
``` 
CXX = g++
CXXFLAGS = -std=c++11 -g
```
2. `./configure` and then `make` the trick at TRICK_HOME dir. (You can use make -j8 for faster compilation time)     

3. You need to have simulation like `SIM_cannon_analytic` (I have used the one located in `trick/trick_sims/Cannon/SIM_cannon_analytic`

4. Open `S_overrides.mk` and paste this lines:

```
TRICK_CFLAGS += -I../models -I/home/backend/trick/trick_source -g 
TRICK_CXXFLAGS += -I../models -I/home/backend/trick/trick_source -g 
```

5. In terminal,  use `trick-CP -g` command:      
`backend@backend-VirtualBox:~/trick/trick_sims/Cannon/SIM_cannon_analytic$ trick-CP -g`

6. Open vscode at TRICK_HOME dir.

7. Create a launch.json file. This is for attaching to process on launch.     
```
{
"version": "0.2.0",
    "configurations": [
        {   
            "name": "(gdb) Launch SimExe",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/trick_sims/Cannon/SIM_cannon_analytic/S_main_Linux_11.4_x86_64.exe",  
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",  
            "additionalSOLibSearchPath": "${workspaceFolder}/lib",
            
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]            
        }
    ]
}
```
8. make sure you have makefile tools extension installed.
9. In extension editor, select launch target  `"${workspaceFolder}/trick_sims/Cannon/SIM_cannon_analytic/S_main_Linux_11.4_x86_64.exe"`
10. Open "Run&Debug" menu.
11. select your launch in this case mine was "(gdb) Launch SimExe"
12. place your break points all over your model source, or trick sources.
13. Finally, click the Start Debugging(F5) button.

This is how I have managed to debug trick source and my own model sources. I hope it works for you guys as well. If trick people approve I can turn this answer into tutorial.

**Comment by hchen99** [comment]
Thanks for all the details. Trick does have a couple of docs listed below as examples that contain info on debugging need although not how to use a specific IDE such as vscode to debug. We'll discuss whether to add an IDE specific tutorial as there are various ways. 

- [Tooling and Sanitizers](https://nasa.github.io/trick/developer_docs/Tooling-and-Sanitizers.html) - "-g" flag
- [Input File Quick Reference](https://nasa.github.io/trick/not_referenced/Input-File-Quick-Reference.html) - Debugging section lists how to attach a debugger and set the debugger command in the input file
- [Building & Running a Trick-based Simulation](https://nasa.github.io/trick/tutorial/ATutAnalyticSim.html#listing_8_s_overrides.mk) - shows a different way to add additional recommended compiler flags as an example in addition to use S_overrides.mk
