### ISSUE TITLE
Mention TRICK_SWIG_EXCLUDE in documentation

### ISSUE THREAD

**Issue by Codym48** [nasa/trick#1622]
I see `TRICK_SWIG_EXCLUDE` in my Trick sim and in this repository, but I don't see it in the documentation at https://nasa.github.io/trick/documentation/building_a_simulation/Environment-Variables.html or https://github.com/nasa/trick/blob/master/docs/documentation/building_a_simulation/Environment-Variables.md

Recommend updating that documentation to clarify the purpose of `TRICK_SWIG_EXCLUDE` and how it relates to other environment variables like `TRICK_EXCLUDE` and `TRICK_ICG_EXCLUDE`, which I believe are captured in https://github.com/nasa/trick/issues/392

**Comment by hchen99** [comment]
Thanks for pointing this out. We'll get this added
