### ISSUE TITLE
More rusage info added to the end of the run summary output enhancement 

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1643]
It would be useful to add the ru_nivcsw (involuntary context switches) to the end of run summary.  These occur mainly when you are using the Linux default scheduler( the fair one) when it things you have run long enough and involuntary pulls your process off the the cpu to let another process run.  This happens even if you have idle cpus on the box.  The rt_nap is on by default in real time sims because this helps with the Linux fair scheduler.  In most cases we have to move the main thread to an isolated cpu to get lower latency on the box because Linux in a soft real time operation system which can't make any guarantees on when a process will run or return to run.  Users often don't have common access or need root to machines that have isolated cpus or real time kernels. This would at least give users some idea of how much the Linux scheduler is contributing to there overruns.  

I would break it up now and have number of involuntary context switches for init and for run.   That way a user could take the number of run time involuntary context switches and sub tracked that from their number of overruns.  While that it is not exactly  true.  In my opion this would do two things 

1. It would provide at least some kind of ball park of the problem to the user.
2. Give a user some idea of what the OS tweaking we do can fix. 

But if I was implementing this I would probably just add everything thing from the rusage structure to the output. Except for the ones that are no longer being maintained in Linux. https://man7.org/linux/man-pages/man2/getrusage.2.html 
 struct rusage {
               struct timeval ru_utime; /* user CPU time used */
               struct timeval ru_stime; /* system CPU time used */
               long   ru_maxrss;        /* maximum resident set size */

               long   ru_minflt;        /* page reclaims (soft page faults) */
               long   ru_majflt;        /* page faults (hard page faults) */

               long   ru_inblock;       /* block input operations */
               long   ru_oublock;       /* block output operations */

               long   ru_nvcsw;         /* voluntary context switches */
               long   ru_nivcsw;        /* involuntary context switches */
           };

**Comment by amishscientist** [comment]
It might be more useful to break up the context switch stats into Init and run. One it will give you slightly better numbers for the run portion. Two it might help provide some insight for someone looking to speed up their init.

**Comment by hchen99** [comment]
> It might be more useful to break up the context switch stats into Init and run. One it will give you slightly better numbers for the run portion. Two it might help provide some insight for someone looking to speed up their init.

Good point and also can be consistent with CPU time used
