### ISSUE TITLE
Add documentation for running real-time #737

### ISSUE THREAD

**Issue by ababyprogrammer** [nasa/trick#1650]
### Hi

Add documentation to detail how to run Trick sims in real-time on one wiki page. This includes setting the software frame, setting process priorities, setting root privilege, processor and memory locking, real-time clock selection, itimers, isolating the processor in the OS, and possibly moving interrupt handling.

**Good luck!**

**Comment by amishscientist** [comment]
While it might not be all on a single page a lot of this basic information is in the trick documentation.  For running real time there are a lot of factors to take into consideration. The big trade off is configuring things to improve latency over throughput.  In most cases you are just making the OS and your sim run more consistent.  A lot OSs have tuning guides to help with this process.  I can tell you this from my experience the smaller the real time frame the more you will have to learn about your OS.

**Comment by ababyprogrammer** [comment]
### Hello 

Thanks for your help.
