### ISSUE TITLE
new default sie generation misses trickified libs

### ISSUE THREAD

**Issue by excaliburtb** [nasa/trick#1652]
Trick switched to using ICG to produce the default S_sie.resource file which means it cannot include a trickified library resources.

the crux of the problem is that the trick-ICG generated build/classes.resource file is for the current build only and doesn't have a way to add the trickified/build/classes.resource from that lib. Maybe a variable list of resource files could be passed to that generation script and added via the make rules in trickify.mk?

**Comment by hchen99** [comment]
We'll look into this.

**Comment by hchen99** [comment]
Not sure if you tried to run `./S_main_xxx sie` and see both `build/classes.resource` and `trickified/build/classes.resource` in `S_sie.resource`?

**Comment by excaliburtb** [comment]
yes, if we use the old memorymanager method for creating S_sie.resource, the data is there because it doesn't rely on those classes.resource files

**Comment by hchen99** [comment]
Currently the S_sie.resource is generated after cp by combing build/classes.resource, build/top_level_objects.resource, and sim_services_classes.resource (in share) into a single file. I believe it used to run sim once to generate sie resource. Issue #947 states the reason for a different way of generating it (or maybe there are other related issues). But I guess we could add classes.resource from trickidfied build directory (if the script knows the path) to the script so the S_sie.resource can have both build/classes.resource and trickified/build/classes.resource after cp instead users need to run "S_main_xxx sie" if they want trickified classes in sie. We'll discuss to address this issue

**Comment by hchen99** [comment]
@excaliburtb put an update to the branch for this issue. Please give it a try with your trickified setting and let us know if see any issues.
