### ISSUE TITLE
swig generates a set method for a public reference with private copy constructor and assignment operator

### ISSUE THREAD

**Issue by excaliburtb** [nasa/trick#1653]
As the title says:

swig is generating a setter for a reference in the S_define but the referenced type has a private unimplemented copy constructor and assignment operator:

See the following example sim:
(removed as it had an error. See comment below for updated example sim.)

Error produced is:
```
build/home/tbrain/test_code/SIM_test_nocpyref/S_source_py.cpp: In function ‘PyObject* _wrap_VehicleOneSimObject_aliasTestObject_set(PyObject*, PyObject*)’:
build/home/tbrain/test_code/SIM_test_nocpyref/S_source_py.cpp:16120:40: error: ‘VehicleOne& VehicleOne::operator=(const VehicleOne&)’ is private within this context
   if (arg1) (arg1)->aliasTestObject = *arg2;
                                        ^~~~
In file included from /home/tbrain/test_code/SIM_test_nocpyref/S_source.hh:84,
                 from build/home/tbrain/test_code/SIM_test_nocpyref/S_source_py.cpp:3845:
/home/tbrain/test_code/SIM_test_nocpyref/include/VehicleOne.hh:24:17: note: declared private here
    VehicleOne & operator= (const VehicleOne &);
                 ^~~~~~~~
make: *** [build/Makefile_swig:65: build/home/tbrain/test_code/SIM_test_nocpyref/S_source_py.o] Error 1
```

This could be a swig issue but confirmation would be nice.

**Comment by hchen99** [comment]
If extending all the way up to sim objects in S_define, then should not produce error
https://nasa.github.io/trick/documentation/building_a_simulation/Model-Source-Code.html#noncopyable-objects

**Comment by excaliburtb** [comment]
oh yes, I had that in the original sim with the issue. Let me resubmit the example with the sim object class also private constructor and assignment operator

**Comment by excaliburtb** [comment]
[nocpyref.zip](https://github.com/nasa/trick/files/14378416/nocpyref.zip)

**Comment by hchen99** [comment]
SWIG 4.2?

**Comment by excaliburtb** [comment]
redhat 8 standard swig install of 3.0.12

**Comment by excaliburtb** [comment]
looks like we can do a workaround of using:

```
##ifdef SWIG
%immutable;
##endif
     VehicleOne & aliasTestObject;
##ifdef SWIG
%mutable;
##endif
```

but obviously it would be better if swig or Trick (whoever is to blame) didn't require it.

**Comment by hchen99** [comment]
Ok, when I was testing, didn't test member initializing with constructor so didn't see the error. I saw the error with folloing:

class VehicleOneSimObject : public Trick::SimObject{
public:
   VehicleOne testObject;
   VehicleOne & aliasTestObject;
   VehicleOneSimObject() : aliasTestObject(testObject)
   {
   }
...
But works if moving testObject and aliasTestObject to before public: as following:
class VehicleOneSimObject : public Trick::SimObject{
   VehicleOne testObject;
   VehicleOne & aliasTestObject;
public:
   VehicleOneSimObject() : aliasTestObject(testObject)
   {
   }

**Comment by hchen99** [comment]
> looks like we can do a workaround of using:
> 
> ```
> ##ifdef SWIG
> %immutable;
> ##endif
>      VehicleOne & aliasTestObject;
> ##ifdef SWIG
> %mutable;
> ##endif
> ```
> 
> but obviously it would be better if swig or Trick (whoever is to blame) didn't require it.

Good to know about the workaround. S_source_py.cpp is auto generated by SWIG, so I'd say because swig requires it ;-)

**Comment by sharmeye** [comment]
The workaround mentioned above is the official guidance offered by SWIG itself for this issue, so I'm going to close this as "not Trick's fault."

**Comment by dbankieris** [comment]
Looks like this might be a SWIG [bug](https://github.com/swig/swig/issues/2866).
