### ISSUE TITLE
QUESTION: I would like to know if we can attend or participate in any NASA Trick Source or Simulation Software Development training program?

### ISSUE THREAD

**Issue by GITburakdeniz** [nasa/trick#1655]
Hello,

I would like to know if we can attend or participate in any NASA Trick Source or Simulation Software Development training program. 

We are a simulator development team. We want to use the NASA Trick development environment. Since Trick software is a trusted and powerful simulation development framework, it takes some time to learn and make changes because it is a large-scale and complex project. For this reason, we would like to purchase NASA Trick source code development training program, if available, to speed up our development process.

**Comment by sharmeye** [comment]
Unfortunately we don't provide training sessions or programs for Trick.  Our documentation is pretty thorough, and we strongly suggest completing the tutorial in full, as that covers the vast majority of functionality developers need to learn.  Also, feel free to send us questions or issue here as usual.

**Comment by GITburakdeniz** [comment]
Thank you for your reply.
