### ISSUE TITLE
variable server restart issues

### ISSUE THREAD

**Issue by excaliburtb** [nasa/trick#168]
Two things can happen that seem to cause very bad things.

1.a.) The variable server for preload_checkpoint pauses the list of variable server threads in that it doesn't write data. However, if there is a new connection requested there is nothing to ensure the new vs connection is handled properly during restart. 

1.b.) Additionally, if there is a VS command during restart, the thread will attempt to process the request. Shouldn't commanding as well as writing data be paused?

2.) The input processor restart restores the python variables reference to sim variables. It uses the PyRun_SimpleString directly rather than ip_parse. This allows the possibility that a variable server connection will call ip_parse at the same time. This might cause a "Fatal Python error: GC object already tracked" error.

**Comment by alexlin0** [comment]
The fix I just pushed suspends accepting of new clients and suspends all variable server threads for the duration of checkpoint loading.  This should resolve all of the issues you mentioned.  But that also means that the clients must be able to wait indefinitely for a response from the sim while the sim is reloading a checkpoint.
