### ISSUE TITLE
CentOS/RHEL 7 build isn't consistently using C++11

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#1695]
Some files in the CentOS/RHEL 7 CI build aren't being built with C++11.

See, for example, [this job](https://github.com/nasa/trick/actions/runs/8711349695/job/23895251162?pr=1694).

This command doesn't include `-std=c++11`:
```
/usr/bin/g++  -isystem/__w/trick/trick/trick_source -isystem/__w/trick/trick/include -isystem/__w/trick/trick/include/trick/compat -DTRICK_VER=19 -DTRICK_MINOR=8 -fpic -I/usr/include/udunits2 -DUSE_ER7_UTILS_INTEGRATORS  -c ScheduledJobQueue.cpp -o object_Linux_4.8_x86_64/ScheduledJobQueue.o
```

EDIT: It actually looks like the files being built with C++11 are in the minority and the `TRICK_CXXFLAGS` are being overridden on a per-directory basis, e.g., https://github.com/nasa/trick/blob/master/trick_source/sim_services/MonteCarlo/Makefile#L6

**Comment by sharmeye** [comment]
Closing since this doesn't appear to be an outstanding issue
