### ISSUE TITLE
Cannot demonstrate a map in variable server

### ISSUE THREAD

**Issue by fzehraa** [nasa/trick#1706]
Hi! I have a string to pointer map in my simulation code. it is like 
map<string, myclass*>
I want to show myclass objects and theirs parameters in variable server. But it says:
"Variable Server: var_add cant add "dyn.object.myclass" because its an STL variable."
Is there a way to show a map's elements in variable server? If not, what approach would you suggest for me?

**Comment by hchen99** [comment]
STL variables are not visible to variable server as stated at https://nasa.github.io/trick/documentation/simulation_capabilities/STL-capabilities.html. 
There are different ways to accomplish this for instance, having trick memory manager to create an array of an object with the key and value of the map as its attributes.
