### ISSUE TITLE
Proposal: Google Summer of Code project relating to Trick

### ISSUE THREAD

**Issue by mohawkjohn** [nasa/trick#171]
Hi there,

I work at Intuitive Machines, which makes extensive use of Trick (thanks!), and I'm also the director of the SciRuby Project, which has participated in the last few Google Summers of Code.

I was thinking it might be a good summer project for a student to create a Ruby interface for Trick:
https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2016-Ideas#ruby-api-for-nasas-trick-simulation-environment

I'm happy to mentor for this project, but wanted to see how you felt about it. I wouldn't want to have someone spend three months coding something that you weren't interested in merging.

Cheers,
John

**Comment by alexlin0** [comment]
Thank you for the offer, but maintaining one interface language is quite enough for us to handle.  So at this time I am not interested in merging in another Interface.

**Comment by mohawkjohn** [comment]
Would that be the case even if you had someone who was willing to maintain the Ruby interface for you?

**Comment by alexlin0** [comment]
Trick has the capability for users to insert alternative scripting interfaces.  We even do it ourselves with our alternative c++ compiled input file.  See the sim_object in our [default_sim_object.sm](https://github.com/nasa/trick/blob/362366b908b37227be96f5d2ff9227a52fbd71c3/share/trick/sim_objects/default_trick_sys.sm#L311-L319) file and the [class](https://github.com/nasa/trick/tree/362366b908b37227be96f5d2ff9227a52fbd71c3/trick_source/sim_services/JITInputFile) underneath it.

**Comment by mohawkjohn** [comment]
Thanks! I'll have a look.
