### ISSUE TITLE
Webserver Documentation - port shall be number not string

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1715]
Webserver Documentation update required at this page : https://nasa.github.io/trick/documentation/web/Webserver 

In this line `web.server.port = "8890"` port is written as string but it should be a number. You may want to correct this.
When written in string it generates a random port.

correct usage should be like  `web.server.port = 8890`

**Comment by hchen99** [comment]
Thanks for reporting this. Will get this corrected to avoid confusion.
