### ISSUE TITLE
how to use json in nasaTrick

### ISSUE THREAD

**Issue by fzehraa** [nasa/trick#1725]
Hi! I'm attempting to read data from a JSON file to update my object's state. I've tried including and adding different libraries for this task, but none of them seem to be working. Could you help me out?

**Comment by sharmeye** [comment]
This is a very case-specific issue with your sim implementation.  Trick has no native support for JSON parsing, so you'll likely need to investigate why your system doesn't have the right packages installed.  If you need help, perhaps you might consult https://www.w3schools.com.
