### ISSUE TITLE
JIT input files and code coverage

### ISSUE THREAD

**Issue by garyt2** [nasa/trick#1736]
Noticed that a sim built with code-coverage flags `-fprofile-arcs -ftest-coverage` will not run a JIT-input file, it cannot load the generated .so file.

Is there a workaround?

**Comment by hchen99** [comment]
Interesting...will do some testing and get back.

**Comment by hchen99** [comment]
Can give it a try as following:

- add `-fprofile-arcs -ftest-coverage` to `.so` target in Makefile.input in `jitlib` directory. 
- `make -f RUN_cpp_input/jitlib/Makefile.input` for instance
- Run sim with a python input file that contains `trick.jit_run`

**Comment by garyt2** [comment]
That is looking like it has potential.  Here's the build process that seems to work from a pristine state:

- build sim with coverage flags
- run the JIT input file to generate the jitlib folder, this run will fail but will populate the jitlib area.
- Edit the `RUN_xxx/jitlib/Makefile.input_config` file to replace:
  - 	`/usr/bin/g++ -shared -o $@ $< ` with
  -	`/usr/bin/g++ -shared -fprofile-arcs -ftest-coverage -o $@ $< `
- remove the .so file that was previously generated in the failed run (`RUN_xxx/jitlib/libinput_config.so`)
- re-make the .so file`make -f RUN_xxx/jitlib/Makefile.input_config`
- Re-run the sim with the JIT input file.

So that's a bit cumbersome, but it seems that, if the modified Makefile could be copied in instead (in place of the default Makefile) for sims that are compiled with coverage flags, then the necessity to edit the default Makefile, remove the original .so, and re-make might be avoided.

Is there a way to identify a build-with-coverage, and conditionally identify which Makefile to populate jitlib with?

**Comment by hchen99** [comment]
Yeah, the workaround takes some manual work. Current JIT input code doesn't generate .so target with trick or trick system CXXFLAGS like for .o target and it doesn't check if build-with-coverage. We'll look into this to make needed update such as to update trick code to have coverage flags for .so in jitlib Makefile if jit input is built with coverage.

**Comment by hchen99** [comment]
@garyt2 [PR1745 ](https://github.com/nasa/trick/pull/1745)this PR allows users to use TRICK_LDFLAGS to have flags for linking shared library for jit input. Instead of having Trick to check whether the sim is compiled with code coverage flags, it gives the flexibility to have whatever flags needed for shared library. So, if you add `TRICK_LDFLAGS += --coverage` or `TRICK_LDFLAGS += -fprofile-arcs -ftest-coverage` to S_overrides.mk for your case, the shared library should be loaded correctly.
