### ISSUE TITLE
Centos 7 End of Support

### ISSUE THREAD

**Issue by cazlo** [nasa/trick#1737]
According to https://endoflife.date/centos, Centos 7 was released approximately 10 years ago, on 2014-07-07. It's support cycle is ending in 2 days, on 2024-06-30.

According to this project's developer documentation, it is the linux configuration which causes the most issues:
https://github.com/nasa/trick/blob/37e273a024af43a4824ce7132f81d1a20c07e2a0/docs/developer_docs/CI.md#L34

> Of these, Centos7 is the oldest and causes the most issues. 

Given this context, it seems prudent to officially bring trick Centos 7 CI/runtime out of support.

**Comment by hchen99** [comment]
Since CentOS 7 has reached its end of life as you mentioned, mirrorlist.centos.org is no longer working, which is posing an issue for our CI. We are looking into addressing the CI issue. In the meantime, we knowledge the validity of your suggestion. Thank you!

**Comment by sharmeye** [comment]
We have addressed the issue in CI, but this is going to be the last time we fix any CentOS 7 issues.  We can no longer actively support CentOS 7 for the reasons mentioned above.
