### ISSUE TITLE
QUESTION: Best way to execute a job ONCE

### ISSUE THREAD

**Issue by alecsuggs** [nasa/trick#1748]
I am looking for a way within my SimObject C++ source code to execute a job only one time when conditions are met. I am looking for a similar implementation to what <event>.manual_fire() would do but in the C++ source code rather than in the input file.

**Comment by Fjolnirr** [comment]
```
#include "trick/Event.hh"
#include "trick/EventManager_c_intf.hh"
```

Include this headers to your source code. **Event.hh** will allow you to create new events that you can set its name cycle set tics ( trigger time ) and activate.(This will allow you to create custom event) After creating an event use `event_manager_add_event(yourEvent);` which is from the **EventManager**. 
Just check the headers for more details.

But if you are looking for something simpler `#include "trick/exec_proto.h"` this header would be better. For example you can on/off a job you defined in S_define using this : `exec_set_job_onoff(const char * job_name , int instance_num, int on) ;`

Check these headers and you probably achieve what you are asking for. Good luck!

**Comment by Fjolnirr** [comment]
You can check this example we made https://github.com/rendayigit/SampleTrickModel/blob/main/models/modelX/modelX.cpp#L41

**Comment by jmpenn** [comment]
Fjolnirr has the right idea. Also see:
https://nasa.github.io/trick/howto_guides/Realtime-Best-Practices#disable-unused-jobs-in-trick-sims
