### ISSUE TITLE
Allow option to execute shell environment setup script in Slave sim shell

### ISSUE THREAD

**Issue by jasonlharvey** [nasa/trick#1765]
Trick Master/Slave requires the user's default shell to include trick/bin in $PATH, because one of the things the slave sim's shell command does is call trick-gte TRICK_HOST_CPU, which fails and kills the slave sim if trick-gte isn't found in the default path.

We don't like including Trick in our default shell, because we have multiple projects needing to use different Trick installs and versions, and having a default Trick inevitably creates conflicts with some project.  This is what we call 'environment-less'.  Since we don't want to have to include Trick in our default shell, then slave sims can't run.  We also don't want to have to create an alias to trick-gte in our default shell, since this can cause conflict with a specific version of trick-gte that we might need to run.

We usually have a shell script for each project that sets up the environment variables needed for that project, run only when we need it.  This includes setting environment variables that a sim may need, but also sets TRICK_HOME and appends $TRICK_HOME/bin to PATH.  It would be nice if we could tell Trick to call that same script first-thing in the slave shell.  I would suggest adding a new parameter to the Master class that holds the path/filename of the optional script to run when the slave shell is first opened, and before trick-gte and the sim executable are called.  Barring that idea, we just need some way to be able to specify multiple environment variables in the slave shell, without relying on ssh's built-in SendEnv stuff, since that's usually disabled for security.

**Comment by hchen99** [comment]
We'll discuss this request.

**Comment by hchen99** [comment]
`trick-gte TRICK_HOST_CPU` is for automatically figuring out slave S_main_name such as `S_main_Darwin_23.exe`. If S_main_name is given when making the interface for a slave such as `new_slave.S_main_name = "./S_main_Darwin_23.exe"`, even `trick-gte` can't be found, the slave sim should run.  Since if S_main_name is already defined, trick would not need to use `trick-gte` to figure out the S_main_name anymore. Although, you'd see `trick-gte: command not found` on your screen. 

If adding a new parameter for holding the optional script, assuming you'd set the filename in your input file. Then you could just set to run the script before setting up the interface for the slave in the input file. Don't see much of the advantage in terms of specifying the script filename vs. calling the script from the input file. 

Not sure though:
_We usually have a shell script for each project that sets up the environment variables needed for that project, run only when we need it._ Does it mean you already call the script in the input file or manually run the script when needed?

**Comment by jasonlharvey** [comment]
The slave's shell environment that we need is unique to the slave sim, and we can't use that same environment for the master sim.  Therefore we can't modify the master's shell environment from the master's input file without breaking the master sim.  Also, i don't think the master's environment variables carry over into the slave's shell anyway; if it did, then the slave shell would already find trick-gte in its $PATH.  The slave shell appears to be a fresh, default shell with only the users's  default .cshrc or .bashrc settings. 

To answer your question, we manually run the script when needed to set up the shell for a particular project.  We don't do it from the sim's input file.  The custom shell env is usually needed to build the sim as well as run it, so it's usually set up before the sim build, and that's another reason why calling it from the input file isn't enough.

**Comment by hchen99** [comment]
You're correct. Calling the env script before new instance of `trick.SlaveInfo()` wouldn't help after `ssh <machine_name>`. So, you are asking to have a new variable for the optional env script for SlaveInfo class ( master interface to Slave) and add to run the env script right after `ssh` command for SlaveInfo startup. Or something else?

**Comment by jasonlharvey** [comment]
That's right.  It's the first thing that runs in the slave's ssh (after the default .cshrc or .bashrc, etc.), and before the trick-gte call.  I see Trick builds a big command string to send to the ssh: it contains the trick-gte call, cd to the sim folder, execute the sim .exe with the input file, add extra command line args to the sim, etc.  In that big string, right before the trick-gte TRICK_HOST_CPU, we could invoke the optional script as a 'source path/filename', etc.  Allow for it to be in a different folder than the sim folder, as specified by the user-supplied path/filename.  Allow the path to be relative to the sim folder, or an absolute path.  I think 'source' -ing it would be best so we don't have to worry about whether it's got the executable flag set on it in file permissions.

**Comment by hchen99** [comment]
Please give it a try with `1765-allow-optional-env-setup-in-slave-sim-shell` branch to see if it works for you. The new variable name is `remote_shell_config_file`. Try to set something like for instance: `new_slave.remote_shell_config_file = "./myshell.sh"`. `remote_shell_config_file` can be relative to the sim folder or an absolute path.

**Comment by jasonlharvey** [comment]
It seems to be working.  It's cd-ing to the sim folder before sourcing the remote_shell_config_file, so if the called file has any cd's in it to source secondary scripts, then it has to remember `pwd` and cd back to it at the end.  That's ok and might be a good thing so the source file can know which sim folder we're running from if needed.

**Comment by jasonlharvey** [comment]
Yes having trick cd back to the sim folder after the remote_shell_config_file runs is a good idea.

**Comment by hchen99** [comment]
Updated and please let us know if you see any issue.

**Comment by jasonlharvey** [comment]
The update works, I see it cd-ing back to the sim folder regardless of where the sourced script exits.
