### ISSUE TITLE
Sub second information would be useful in send hs message time stamps.

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#1768]
It would be nice if send_hs showed more resolution of the time in it's log messages

|L   0|2024/06/12,13:32:42|cabaodaba| |T 0|0.000000| time =     0.00 , position =     5.000000 ,     5.000000

It would be nice if the time showed in the log message was at least the same resolution as gettimeofday. A computer can do a lot in a second so it is helpful to have a better understanding of the time between messages.

Right now trick is throwing away the sub second part of the time stamp.  So when uses need it they are having to make an additional call to the clock for the information that trick is throwing it away.  It is because the date format command trick is using to convert it to a calendar time doesn't use the info.   My recommendation would be to just make a new column for the sub second part of the time stamp. 

To look like this
|L   0|2024/06/12,13:32:42|0.013550|cabaodaba| |T 0|0.000000| time =     0.00 , position =     5.000000 ,     5.000000

**Comment by hchen99** [comment]
Thanks for the details. Will look into this

**Comment by sharmeye** [comment]
This is reasonable, and it seems like something that would help with sim performance profiling.

Future issues that begin with the phrase "It would be nice if" will be rejected out of hand with extreme prejudice.  And you did twice this time.

**Comment by hchen99** [comment]
@amishscientist please give it a try with the branch to see if it's what you're looking for. Utilized `hh:mm:ss.xx` format and `xx` are in seconds
