### ISSUE TITLE
Trick debug_pause debug_counter no longer works

### ISSUE THREAD

**Issue by miltondean** [nasa/trick#1805]
In the Trick 13 instruments.debug_pause.debug_counter works correctly.  When set to a non-zero value, the simulation should enter Step mode.  Every time the Step is selected from the Sim Control panel, the debug_counter decrements and when it hits 0, the Step mode ends and the the simulation continues as normal.
In Trick 17, instruments.debug_pause.debug_counter was updated to be trick_instruments.debug_pause.debug_counter, and it appears an error was introduced into this processing so that it no longer works.

**Comment by hchen99** [comment]
Thanks for bringing this to our attention. We'll look into this.

**Comment by sharmeye** [comment]
I just looked, and I can't even find a reference to debug_counter in Trick 17.  Can you give us more information?

**Comment by miltondean** [comment]
***@***.***

So, looking at our copy of the Trick17 code, it looks like this attribute was added by one of our team (who has since retired).

It looks like he added it in the DebugPause class:
***@***.***

And the processing was updated in debug_pause:
***@***.***

So, it looks like we ‘customized’ the DebugPause and after looking at this code for a bit, I realized it is working as expected.

The use case for the debug counter is :

  1.  First put your sim in to Step Mode.
  2.  With Trick TV up and running, say you need to hit that Step button on the Sim Control panel 100 times, well if you bring up the debug_counter and set it to 100,

Then the sim will execute 100 cycles in debug mode.  Saves you finger from having to hit “Step” 100 times and runs the exact number of cycles you want.



This code does seem to work as expected, so please close this issue.  We will add our customized code in the Trick 19 version that we are migrating to.



FYI, if you like this addition, maybe you can change the Issue to a future enhancement.



Milton Dean
All-Points LLC
OrionSim Software Development
***@***.******@***.***>
(281) 333 – 6070  (desk)
(281) 235 – 5687  (cell)
[2560x1440_Artemis-Mark-Full-Color_65]






From: Sean Harmeyer ***@***.***>
Sent: Tuesday, November 19, 2024 11:14 AM
To: nasa/trick ***@***.***>
Cc: Dean, Milton W (US N-ALL POINTS LOGISTICS) ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [nasa/trick] Trick debug_pause debug_counter no longer works (Issue #1805)


I just looked, and I can't even find a reference to debug_counter in Trick 17. Can you give us more information?

**Comment by sharmeye** [comment]
Thanks for getting back to us, we'll go ahead and close.
