### ISSUE TITLE
DRE Issues on RedHat 7.2

### ISSUE THREAD

**Issue by ajfear** [nasa/trick#186]
I recently updated to the 15.1 release from an old 15.0 release and everything has compiled fine. I think there may now be an issue with Java as now when I try to run dre i receive:
Error: Could not find or load main class trick.dre.DreApplication

Switching back to the 15.0 release that I was using before is now giving me the same error. I think this may be caused by some Java package issues when I updated my RedHat packages?

**Comment by alexlin0** [comment]
If your java version changed then you will indeed get that error.  On some RHEL systems multiple java versions are installed and available.  Do this command to see which java the system is currently using and what your alternatives are:
```
alternatives --display java
```

**Comment by alexenos** [comment]
I've had similar issues for installed Trick Java applications, and I found the trick.jar permissions were too restrictive. I could fix it quickly with:

sudo chmod a+r /usr/local/libexec/trick/java/dist/trick.jar

**Comment by ajfear** [comment]
Currently I have java-1.8.0-openjdk (and -devel, -headless) installed. I also have tried using the -oracle packages in addition to 1.7.0. I'm not quite sure why this just started happening with dre. It also does not appear to be a permissions issue as other Trick GUIs work (trick_dp, trick_qp).

**Comment by ajfear** [comment]
It appears to have been the way that the bin/dre script was written. It looked as though the way the script was written to call java was different than some of the other GUIs. I copied trick_dp and changed it to open the trick.dre.DreApplication class and the GUI opens correctly. Cause is still unclear.

**Comment by alexlin0** [comment]
Although I could not recreate the error, I've changed the startup script of dre to match trick_dp.
