### ISSUE TITLE
trick comm byteswap functions can't handle sizes above 65536 bytes

### ISSUE THREAD

**Issue by lordmundi** [nasa/trick#187]
When trying to do a tc_write_byteswap on a large structure, I got a seg fault.  Looking at tc_write_byteswap.c (and tc_read_byteswap.c), it looks like there is a hard-coded size for the swap buffer of 65536 bytes.

I rewrote a test with this structure and it also caused it to seg fault:

struct big_array_struct {
    unsigned int big_array[20000];
};

Assuming the cause of the seg fault is the fixed size "swap" buffer in those functions, my suggestion is to make the size dynamic.  To avoid constant resizing as different size structures come into the function, i would advise making a static buffer which is increased to the incoming structure only when it isn't big enough.  I think after relatively few calls it would settle to a size large enough to accommodate all of the structures being written.

**Comment by alexlin0** [comment]
Hmm, that static swap space isn't thread safe either.  I'll have to think about the best way to fix this.

**Comment by lordmundi** [comment]
alex, i had a thought on this that might be easy.  Could a solution be a new version of the function call where the calling function provides the buffer to use?  That way, the caller could ensure it is big enough for whatever they are doing, and also since the caller would maintain their own buffer it would be thread safe and wouldn't require a static.

to preserve the old interface, you might provide a new function call with a suffix to suggest they are thread safe, and in the backward compatible version, you just call the the thread safe version with a pointer to your static buffer you were using before.

just a thought.

**Comment by alexlin0** [comment]
OK, I think I have an answer.  I will use pthread specific data to store a resizable buffer for each thread.  And I'll probably use your first suggestion to resize the buffer when a new bigger size is required.  Will try and work on it this week.
