### ISSUE TITLE
Remove doxygen documentation now housed on wiki

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#189]
We need to remove the documentation which will slowly become out of date in our doxygen documentation as it is now housed in our wiki.

**Comment by iamthad** [comment]
Are you planning to cease using Doxygen entirely? It'd be helpful to continue using it so that projects using Trick can link to it: https://www.stack.nl/~dimitri/doxygen/manual/external.html

**Comment by alexlin0** [comment]
We do plan to keep using doxygen, but to use it for what it was designed for documenting code, not as a "text file to html converter".  We have a lot of text that sit in text files we were using doxygen to convert to html.  We have put this text in our wiki now and no longer need doxygen to process it.  The text files are redundant now and I'll be removing them.

**Comment by iamthad** [comment]
Good to hear. Thanks for the clarification.
