### ISSUE TITLE
Split test sims and fun sims into separate directories.

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#191]
We have the fun sims and the boring test sims together.  We need to split them up.

**Comment by jmpenn** [comment]
commit 9e481703a1075b76757c086a66acb827b4d7ad98

**Comment by jmpenn** [comment]
commit 486cc107843403331716e19341843d2b2b15ef5f
mv helios models to SIM_sun/models/Sun

**Comment by jmpenn** [comment]
commit 0a401893880e5ef4e151d706ba3bf28254525f1b
move parachute models to SIM_parachute and fix up S_overrides.mk

**Comment by jmpenn** [comment]
commit 950e319c1bf03f64836ee0f69b42f2275f5a13b7
move Satellite models to SIM_satellite and fix graphics makefile

**Comment by jmpenn** [comment]
commit 54a4b57dbefd7688976939fa24a52b70a48319d0 
Update README and various other tweaks to SIM_wheelbot

**Comment by alexlin0** [comment]
All sims moved to our satisfaction.
