### ISSUE TITLE
Trick_qp problem with plotting large number of data points

### ISSUE THREAD

**Issue by kjbledsoe** [nasa/trick#204]
I use trick_qp for plotting my data. Some of my files have a lot of data points. When I plot from those files, I can only get a couple of plots to come up; trying to make too many (by which I mean more than one or two, depending on how many curves I have on a plot) makes the program choke. The same data with a lower log rate and correspondingly lower number of data points is handled just fine -- I can make about as many plots as I want. 

The truly weird thing is that when I close trick_qp, all of those plots it choked on and refused to show suddenly appear.

Also odd is that no one else on the system is having the same problem as I am. I suppose it's possible that their files don't have as much data or a high sampling rate. That's the only thing I can think of.

Any ideas? Is there some limit to what trick_qp can handle?

**Comment by alexlin0** [comment]
Which version of Trick are you using, is it a released version or the trunk?  Also are you using the default plotting tool, the "java" plotter?  I know that the default java plot package that we use by default does slow down significantly if you try to plot a lot of points.  You may want to try the gnuplot alternative and see if that can handle your data.

**Comment by kjbledsoe** [comment]
I'm using Trick 13.5. I'd guess it's a released version, though I'd have to ask the guy who manages the cluster. I'm using Fermi for plotting -- I need features that gnuplot doesn't seem to have.

**Comment by alexlin0** [comment]
So if you are still having problems, can you tell me how many data points we are talking about?  How high of a frequency are you recording and how many variables are in the log file?
