### ISSUE TITLE
Changes is Tutorial

### ISSUE THREAD

**Issue by urroner** [nasa/trick#217]
Here are some suggested changes for the Trick Simulation Environment User Training Materials.  It goes up to and includes section 7.
[Trick_Tutorial_Problems-1.pdf](https://github.com/nasa/trick/files/203131/Trick_Tutorial_Problems-1.pdf)

**Comment by alexlin0** [comment]
we'll get on it.

**Comment by urroner** [comment]
Thanks.

**Comment by alexlin0** [comment]
I'm going to reopen this issue so we can refer to it as we update the tutorial.

**Comment by urroner** [comment]
Sounds great.

Between learning QT and Trick, I’m scrambling.

I hate bothering you with this question, but are there any examples online of using C++ headers in Trick.  I’ve been trying to figure out how files are organized on github, but haven’t been able to do it yet.  I’ve started reading the user manual, but I haven’t been able to make it through section 3.1 yet.

Lynn R. Svedin
NASA
NE-C4
Kennedy Space Center, FL 32899
Phone - 321-867-2970
Email - lynn.r.svedin@nasa.gov<mailto:lynn.r.svedin@nasa.gov>

Blood makes one related., but Trust  and Loyalty makes one family.

**Comment by CTLaChance** [comment]
@jmpenn Can this issue be closed, or would you like to keep it open as you refine the tutorial?

**Comment by urroner** [comment]
It can be closed.

Thanks.

Lynn R. Svedin
NASA
NE-XM
Kennedy Space Center, FL 32899
Office Phone - 321-867-2970
Email - lynn.r.svedin@nasa.gov<mailto:lynn.r.svedin@nasa.gov>
Blood makes one related... but Trust  and Loyalty makes one family.
________________________________
