### ISSUE TITLE
Update / Rewrite the Trick Tutorial

### ISSUE THREAD

**Issue by jmpenn** [nasa/trick#241]
The Trick Tutorial is getting very out of date and contains numerous problems. It needs A rigorous rewrite.

**Comment by mzieg** [comment]
I made a couple tweaks directly to the Tutorial Wiki, but I also had these issues which I wanted to confirm before posting:

4.3.1
* had to #include "cannon/include/cannon_proto.h" in SIM_cannon_integ/models/cannon/src/cannon_deriv.c

4.3.2
* had to #include "cannon/include/cannon_proto.h" in SIM_cannon_integ/models/cannon/src/cannon_integ.c
* had to #include <string.h> in SIM_cannon_integ/models/cannon/src/cannon_integ.c to define NULL (using MacOSX 10.11.5)

4.3.3
* had to comment-out cannon_analytic() in cannon_proto.h, else trick-cp failed with:`
  Final link   S_main_Darwin_15.exe
  Undefined symbols for architecture x86_64:
    "_cannon_analytic", referenced from:
        _wrap_cannon_analytic(_object*, _object*) in swig_python.o
  ld: symbol(s) not found for architecture x86_64`

4.3.5
* should say whether the dyn_integloop.getIntegrator() call should go before, after, or replace existing contents (assuming before)

**Comment by jmpenn** [comment]
Thanks. I'll look over these.

**Comment by jmpenn** [comment]
I added all of your fixes as-is except for the second item under 4.3.2.  For that I think a better fix is to #include <stddef.h> which occurring to POSIX is supposed to define NULL. Thanks Again!
