### ISSUE TITLE
unintended performance issue with integ_loop at end of scheduled job classes

### ISSUE THREAD

**Issue by excaliburtb** [nasa/trick#243]
The move of "integ_loop" class scheduled jobs to the end of the schedule loop has unintentionally negatively impacted simulation performance. By moving integ_loop after system_advance_time, it has effectively become an end_of_frame job.

The problem is that the signal for child threads to start their work is effectively in top_of_frame and the wait for child threads to complete is in system_advance_time. The impact of the move is that the integ_loop jobs will only run after waiting for the child threads and, therefore, will not run parallel to the other threads.

**Comment by alexlin0** [comment]
I am aware of this consequence.

We made this change so scheduled jobs would run as the frame started.  You can get the previous behavior by adding a job class list order in the S_define file.  The below list should give you the previous job ordering.

```
job_class_order {
  integ_loop,
  automatic,
  random,
  environment,
  sensor,
  sensor_emitter,
  sensor_reflector,
  sensor_receiver,
  scheduled,
  effector,
  effector_emitter,
  effector_receiver,
  automatic_last,
  logging,
  data_record,
  system_checkpoint,
  system_advance_sim_time,
  system_moding
} ;
```

**Comment by alexlin0** [comment]
I'd like to close this issue if the above is acceptable.

**Comment by excaliburtb** [comment]
I'm not sure it is "acceptable". Consider the following:

I think, in order to do what you really want, you'd have to split the advance time and the AMF sync so that you can advance main thread exec time, integ_loop, then AMF sync. It seems like a possible fix too now that each thread has it's own sim time and scheduler.

integ_loop can be so costly that losing the ability to run it in parallel (by default) seems like a step backwards. Just my opinion...

**Comment by alexlin0** [comment]
OK, I've been looking at the code.  I can maximally parallelize the threads by moving the sync point as you suggest.  I'm going to have to create another job class to do it but it's not too hard.
