### ISSUE TITLE
Trick View: update to handle udunits

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#262]

**Comment by alexlin0** [comment]
I am removing the 16.0 milestone.  The long term goal of reading the udunits xml files and extracting the units out of that is not necessary for the 16.0 release.  The units currently offered in TV is adequate for now.

**Comment by dbankieris** [comment]
Not sure why this was closed. TV still isn't synchronized with udunits.

**Comment by dbankieris** [comment]
udunits grammar is described [here](https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2lib.html#Grammar). The units are defined in [XML files](https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2.html#Database). A complete implementation would parse a units string according to the grammar and determine all valid conversions for each unit therein according to the XML files.

**Comment by dbankieris** [comment]
Looks like there might be a Java implementation of udunits: https://www.unidata.ucar.edu/support/help/MailArchives/netcdf-java/msg00148.html
