### ISSUE TITLE
Monte carlo AttributeError's caused by bad configuration still returns zero in master sim

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#269]
We are seeing this in trick 13.2.1 but I have replicated this in SIM_monte in the latest trick, simply make this change to see the issue:

Change any definition of `trick.MonteVarRandom`'s first argument to be an attribute that doesn't exist, for example change line 42 in `SIM_monte/RUN_test/gauss.py` to:
```
var3 = trick.MonteVarRandom("dyn.baseball.foobar",trick.MonteVarRandom.GAUSSIAN)
```
The result is that the master stdout/stderr produces the following error, one for each slave instance:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
AttributeError: Type CANNON_AERO does not contain member foobar.
```
However, the master process still returns zero:
```
Speedup (sum of CPU time / total time): 0.92
Efficency (speedup / num slaves): 92.41%
bash-4.2$ echo $?
0
```
The same is true for the ```trick.MonteVarFile()``` usage.  Since the process still returns zero, we cannot automatically detect this failure when running monte carlo in a continuous integration framework.

**Comment by ddj116** [comment]
@alexlin0 I just tested the latest state and the master sim still returns zero even though I get new prints saying "Bad Input"

**Comment by alexlin0** [comment]
Oh, you need the monte carlo master to return a non zero if any slave fails.  I only worked on the slave returning non zero to the master.

**Comment by ddj116** [comment]
Tested it and works great.  Thanks!
