### ISSUE TITLE
 Add Memory Manager STL unit tests

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#27]
Using the ball sim, the sim should run for a bit and take a checkpoint.  then continue for a bit, reload the checkpoint and continue to the end.  The results should be the same at the end.

**Comment by alexlin0** [comment]
Instead of using the ball sim we discussed doing the following.

1. Basic type checkpoint/restart is covered by Memory Manager unit tests
2. We need to create Memory Manager STL unit tests

**Comment by jmpenn** [comment]
This has been addressed by #1355.
