### ISSUE TITLE
configure script doesn't check for clang headers

### ISSUE THREAD

**Issue by lordmundi** [nasa/trick#287]
I was installing Trick 17 and got the configure script to successfully complete after making a link for llvm-config to llvm-config-3.5.

But on the very first file it tried to compile it failed saying:

`ClassTemplateVisitor.cpp:6:39: fatal error: clang/Basic/SourceManager.h: No such file or directory`

Installing the package "libclang-3.5-dev" fixed the issue (since I have clang 3.5)

**Comment by alexlin0** [comment]
Yeah, it's looks like you are right.  We check for the existence of the llvm executables and libraries but not the header files.

**Comment by lordmundi** [comment]
as an aside, you may want to add a check for libz-dev also.  I noticed one of the example sims failed to build because it couldn't find "-lz"

**Comment by alexlin0** [comment]
So which sim needed -lz?

**Comment by lordmundi** [comment]
hmm... i can't remember, but running this makes me think all of them?

```
trick_sims> find . -iname S_source.cpp | xargs grep -ins -- '-lz'
./SIM_Ball++_L1/build/S_source.cpp:1260:    local_env["TRICK_EXEC_LINK_LIBS"] = " -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm -ludunits2 -lrt -lm -ldl -lz";
./SIM_wheelbot/build/S_source.cpp:1213:    local_env["TRICK_EXEC_LINK_LIBS"] = " -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm -ludunits2 -lrt -lm -ldl -lz";
./SIM_sun/build/S_source.cpp:1215:    local_env["TRICK_EXEC_LINK_LIBS"] = " -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm -ludunits2 -lrt -lm -ldl -lz";
./SIM_satellite/build/S_source.cpp:1219:    local_env["TRICK_EXEC_LINK_LIBS"] = " -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm -ludunits2 -lrt -lm -ldl -lz";
```

**Comment by alexlin0** [comment]
Hmm, I have -lz explicitly in TRICK_EXEC_LINK_LIBS to link to every sim, but I don't think we use it.  I may remove the library from the link instead.

**Comment by lordmundi** [comment]
When would zlib normally be used in a sim? For comm or something? My guess
is that some other library you'd want to use would depend on it, like hdf5
or something like that.

FG

**Comment by alexlin0** [comment]
I'm sure it was needed by some included library at some point in time, but I cannot find anything that requires it anymore, not python or hdf5, or anything else we normally include.

**Comment by excaliburtb** [comment]
I saw it once when trying to get a clang/llvm version to work. the final link for ICG complained about missing -lz

**Comment by alexlin0** [comment]
OK, ICG does require it.  I'll add a check in the configure script for -lz.
