### ISSUE TITLE
tc_init is not thread-safe

### ISSUE THREAD

**Issue by excaliburtb** [nasa/trick#289]
There's a file-scoped global in tc_init.c that makes the initialization call not thread-safe. 

static struct sockaddr_in s_in;

It doesn't even look like it needs to be global....

**Comment by alexlin0** [comment]
Umm, hmm.  I did that back in 2013 and I have no idea why.

**Comment by excaliburtb** [comment]
Looks like there are several cases of file-scoped globals in the various tc_init variations.

**Comment by jmpenn** [comment]
Ok it looks like that the struct that sockaddr is pointing to doesn't need to be kept around after the bind, so changing s_in back to a local variable should be fine. After verifying this Alex Lin ( being a twit) went and made the change.
