### ISSUE TITLE
Trickified Project Libraries

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#309]
Let's see if we can come up with a generic way to build a project's `io_*` and `py_*` code into a library so sims can link against that instead of compiling all that generated code all the time.

**Comment by alexenos** [comment]
I the JSC ER7 folks implemented something like this for JEOD. One thing I found with their implementation is that the SIE resource was effectively unavailable

**Comment by dbankieris** [comment]
For anyone who's following this, there's also a sweet [wiki page](../wiki/Trickified-Project-Libraries).
