### ISSUE TITLE
ICG exclude of class member variables now defines incorrect memory offsets in io_src

### ISSUE THREAD

**Issue by alexenos** [nasa/trick#311]
The new implementation of io_src generation leads to incorrect variable reference in the variable server if class member variables are hidden from ICG with the use of #ifndef TRICK_ICG. The ICG exclude prevents the autogeneration of the io_src to correctly calculate the memory offsets for class instances within the executable memory. I believe the major change was the autogeneration/autodetermination of the offset at the time of writing of the io_src, instead of utilizing the size_of function and determining the offsets at compile time.

As of commit 8c8c7130b40fd5d4c32f70a7b44cebd29fb802db

**Comment by alexlin0** [comment]
Yes, you are correct, we told users in the past to use #ifndef TRICK_ICG to exclude things in Trick.  This is when ICG would run into trouble trying to parse something.  These days ICG is much more capable,  Would it be possible to remove the #ifndef TRICK_ICG in your code now and let ICG parse it?

I would be sad if I had to revert this change.  The change that did this allows Trick to manipulate protected/private variables without the use of friends.

**Comment by alexenos** [comment]
The short answer is no.

Are you saying the TRICK_ICG exclusion is effectively deprecated functionality? My issue here is that Trick is no longer internally consistent when supporting ICG exclusion and a correct memory map of the simulation executable, which the variable server depends upon. 

If ICG exclusion (at least of class member variables) is deprecated functionality, then I have a couple of template-based ICG issues to post.

**Comment by alexenos** [comment]
Also, JEOD 3.2 has class member variables that are TRICK_ICG excluded. Presumably this will be fixed in a future release, but it pains me to maintain a patch to JEOD.

**Comment by alexlin0** [comment]
I will see what I can do to restore the old behavior.

As a test, I removed of all #ifndef TRICK_ICG in JEOD classes and was able to build and run SIM_dyncomp successfully.

If you have some troublesome templates please post them, we want to make sure we can process them correctly.
