### ISSUE TITLE
Bad units specification [dB]

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#312]
It looks like udunits doesn't like decibels as a unit. This is a regression from previous Trick, which supported it.

**Comment by alexlin0** [comment]
Yes, there is some discussion in udunits development about dB missing.

We can't convert dB to anything in Trick.  I can add dB back as an accepted unit, but will convert it to "1" for udunits.

If udunits in the future decides to define dB differently I will remove my conversion.
