### ISSUE TITLE
Variable Server could not find variable related to trick_sys.sched

### ISSUE THREAD

**Issue by sonicyang** [nasa/trick#315]
I got the following Errors upon running any simulation built with trick 17.0.4.

`Variable Server could not find variable trick_sys.sched.sim_start.`
`Variable Server could not find variable trick_sys.sched.terminate_time.`
`Variable Server could not find variable trick_sys.sched.time_tic_value.`
`Variable Server could not find variable trick_sys.sched.time_tics.`
`Variable Server could not find variable trick_sys.sched.mode.`

On Version 17.0.2 everything worked fine.
This can be reproduced with the tutorial Cannon projects.

Environment I used: 
- Tirick 17.0.4 and master branch
- Ubuntu 16.04.1
- Dependencies install following the installation guide, instead I use Orcale java 8

**Comment by alexlin0** [comment]
Yes, I get the same errors.
