### ISSUE TITLE
Is "error_tol" in the regula_falsi structure ever set?

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#319]
This should default to a small value like 1.0e-15.  We currently cannot find it being set anywhere.

**Comment by jmpenn** [comment]
The REGULA_FALSI type is a  typedef'ed C-struct defined in regula_falsi.h. It has no "constructor".
In the cannon simulations, the CANNON structure defines a REGULA_FALSI member called "rf".
The entire REGULA_FALSI member of CANNON is initialized in function cannon_default_data() in file cannon_init.c Specifically, the error_tol member is initialized as : **C->rf.error_tol = 1.0e-9 ;**

**Comment by jmpenn** [comment]
Bottom line is: currently, it must be explicitly initialized sim "default_data" or "initialization"  code.
