### ISSUE TITLE
Library dependencies not found in Trick 15

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#325]
We have at least 2 cases where library dependencies are not found.

```
--------------------------------------------------------------------------------------------------
   Library Dependency Definition Approaches                  RESULT
--------------------------------------------------------------------------------------------------
 1.  Specify path/to/file.o        in another .hh file     undefined reference to file.o functions
 2.  Specify path/to/src/file.cc   in another .hh file     WORKS
 3.  Specify path/to/file.o        in another .cc file     WORKS
 4.  Specify path/to/src/file.cc   in another .cc file     undefined reference to file.o functions
```

**Comment by dbankieris** [comment]
In my opinion, we should stop automatically looking in `src` and `include` directories and always require the actual path. Also, users should specify the actual file extension, not `.o`. Following the compiler's convention will cause less confusion and require less specialty code that only works when users choose specific (if common) directory names.

**Comment by ezcrues** [comment]
I agree with Derek but you are going to break a lot of code.
