### ISSUE TITLE
Smartmatch is experimental in Perl 5.10

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#329]
`get_lib_deps.pm` emits the following warning:
`Smartmatch is experimental at libexec/trick/pm/get_lib_deps.pm line 189`

**Comment by CTLaChance** [comment]
This issue references [this line of code.](https://github.com/nasa/trick/blob/841473583c7c3e6e6c691bf4aa4f1bf864ef2c6e/libexec/trick/pm/get_lib_deps.pm#L189)

http://blogs.perl.org/users/mike_b/2013/06/a-little-nicer-way-to-use-smartmatch-on-perl-518.html

According to the link above, it appears that we can suppress the warning manually. Alternatively, we can stop using smartmatch and replace it with the following [match::smart.](http://search.cpan.org/~tobyink/match-simple-0.010/lib/match/smart.pm)

**Comment by CTLaChance** [comment]
@dbankieris I'm not getting this warning when recompiling Trick or the test suite. I can't tell if this fix 100% works. How are you getting this warning?

**Comment by CTLaChance** [comment]
Attempting to compile a simulation using trick-CP is what causes this warning to appear. 

Replacing ~~ with |M| requires users to install the match::smart module as it does not come with the Perl core.

Entering "use experimental 'smartmach';" at the top of the perl script will suppress the warning from displaying, but it doesn't really fix _the problem_ of using deprecated functionality.

**It ain't broke.**
