### ISSUE TITLE
Makefile hardcoded directory in it

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#340]
The gtest headers are probably in a default search location. Do we really need to accommodate non-standard installations?

`trick_source/sim_services/DataTypes/testing/makefile`

**Comment by jmpenn** [comment]
The code in the Datetypes directory is not currently being used by Trick. It is still under development.
Therefore it doesn't really matter that it has a temporary hardcoded directory in the makefile. I'll take it out when the time comes that this code is actually integrated with Trick.
