### ISSUE TITLE
Could not find libxml development headers on Mac OS X

### ISSUE THREAD

**Issue by mohawkjohn** [nasa/trick#347]
I can't seem to configure TRICK on Mac OS X 10.12 (Sierra):

```
checking for main in -lxml2... yes
checking libxml/tree.h usability... no
checking libxml/tree.h presence... no
checking for libxml/tree.h... no
configure: error: could not find libxml development headers
```

**Comment by jmpenn** [comment]
You shouldn't need to install libxml2 from Brew. I'm pretty sure It comes with the Xcode command line tools, which you will get by running  ```$ xcode-select --install```. Please give that a try and let me know if that fixes the problem for you.

BTW: I'm running Trick on macOS 10.12.1 Sierra.

I think the documentation isn't clear on libxml2. I'll take a look and fix.

Regards

**Comment by jmpenn** [comment]
This seems to confirm where libxml comes from.
http://stackoverflow.com/questions/33770087/libxml2-installation-onto-mac

Regards

**Comment by jmpenn** [comment]
Updated install doc with a warning about libxml2. Not merging pull request.
