### ISSUE TITLE
Couldn't find an io_src_sizeof_ function for typestd::__cxx11::basic_string[io_src_sizeof_std____cxx11__basic_string()]

### ISSUE THREAD

**Issue by mohawkjohn** [nasa/trick#352]
I get this warning with Trick 15.2.3 (which I seem to need to use in order to get JEOD 3.1 to work, but hopefully upgrading to JEOD 3.2 later today). I'm not totally sure it's a Trick warning, but I can't find anything like it on Google.

There are a whole bunch of them.

```
MemoryManager:WARNING:(/home/mohawkjohn/axiom/io_src/io_S_source.cpp:5040): Couldn't find an io_src_sizeof_ function for typestd::__cxx11::basic_string[io_src_sizeof_std____cxx11__basic_string()].

MemoryManager:WARNING:ATTRIBUTES for type "std____cxx11__basic_string" not found.

MemoryManager:WARNING:(/home/mohawkjohn/axiom/io_src/io_S_source.cpp:5143): Couldn't find an io_src_sizeof_ function for typestd::__cxx11::basic_string[io_src_sizeof_std____cxx11__basic_string()].

MemoryManager:WARNING:ATTRIBUTES for type "std____cxx11__basic_string" not found.

MemoryManager:WARNING:(io_src/io_IntegLoopSimObject.cpp:70): Couldn't find an io_src_sizeof_ function for typestd::__cxx11::basic_string[io_src_sizeof_std____cxx11__basic_string()].

MemoryManager:WARNING:ATTRIBUTES for type "std____cxx11__basic_string" not found.

MemoryManager:WARNING:(/home/mohawkjohn/axiom/io_src/io_S_source.cpp:2033): Couldn't find an io_src_sizeof_ function for typestd::__cxx11::basic_string[io_src_sizeof_std____cxx11__basic_string()].

MemoryManager:WARNING:ATTRIBUTES for type "std____cxx11__basic_string" not found.
```

If I look at line 5143 of `io_S_source.cpp`, I see:

```
void init_attrDeploySimObject() {

    int i __attribute__((unused)) = 0 ;
    static int initialized_1337 ;
    if ( initialized_1337 ) {
            return ;
    }
    initialized_1337 = 1 ;

    Trick::MemoryManager * mm ;
    std::string next_attr ;
    mm = trick_MM ;
    attrDeploySimObject[i].offset = offsetof(DeploySimObject,name) ;
    next_attr = std::string(attrDeploySimObject[i].type_name) ;
    mm->add_attr_info(next_attr , &attrDeploySimObject[i], __FILE__ , __LINE__ ) ; // <----
    i++ ;

    attrDeploySimObject[i].offset = offsetof(DeploySimObject,id) ;
    attrDeploySimObject[i].size = sizeof(int) ;
    i++ ;

    attrDeploySimObject[i].offset = offsetof(DeploySimObject,TrvDeploy) ;
    next_attr = std::string(attrDeploySimObject[i].type_name) ;
    mm->add_attr_info(next_attr , &attrDeploySimObject[i], __FILE__ , __LINE__ ) ;
    i++ ;


    ATTRIBUTES temp_attr ;

    next_attr =  "Trick::SimObject" ;
    mm->add_attr_info( next_attr , &temp_attr , __FILE__ , __LINE__ ) ;
}
```
(I've indicated the line with a `<----`.)

Curiously, the other file it mentions (`io_IntegLoopSimObject.cpp`, line 70) does not exist.

Do I have a library mismatch or something? What should I be looking for?

Thanks!

**Comment by mohawkjohn** [comment]
FYI, this error occurs with JEOD 3.2 also.

**Comment by mohawkjohn** [comment]
Possibly related to #285.

**Comment by mohawkjohn** [comment]
Best I can tell is an STL type is being treated as if it's a user-defined type. I looked at the libcstd++ shared object on my computer using readelf, and it doesn't seem to have any kind of sizeof on basic_string. I ended up commenting out both the warnings.

**Comment by alexlin0** [comment]
This is actually related to #214.  Up to now we only fixed this issue in 17.  We will have to back port this to 15.

**Comment by mohawkjohn** [comment]
Roger that. Thanks.

**Comment by alexlin0** [comment]
@mohawkjohn It appears you are running a very recent OS which Trick 15.2.3 is not ready for.  Or you are using a newer gcc version.  If you need to use Trick 15.x with these new  versions, you should clone the repository and use the Trick 15.3.dev branch.  Or you can wait until we make a 15.3 release, which should be soon, assuming no big issues are uncovered.
