### ISSUE TITLE
Makefiles should infer TRICK_HOME

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#358]
I am so tired of having to set TRICK_HOME to build a Trick subdirectory. All Trick makefiles can determine TRICK_HOME relative to themselves. I will slowly add logic to every makefile that thwarts my attempts to build environmentlessly.

**Comment by abrogley** [comment]
I think this most recent commit broke my build. When I attempt to build on ubuntu 16.04 without previously setting TRICK_HOME, I get this error:

```
ln -s -f swig_Linux_5.4_x86_64 swig_Linux_5.4_x86_64_test
make[1]: Leaving directory '/path/to/trick/trick_source/trick_swig'
ar crs /path/to/trick/lib/libtrick_pyip.a /path/to/trick/trick_source/sim_services/InputProcessor/object_Linux_5.4_x86_64/*.o  /path/to/trick/trick_source/trick_swig/object_Linux_5.4_x86_64/*.o 
make[1]: Entering directory '/path/to/trick/trick_source/er7_utils/integration/abm4'
Makefile:2: /path/to/trick/trick_source/share/trick/makefiles/Makefile.common: No such file or directory
Makefile:3: /path/to/trick/trick_source/share/trick/makefiles/Makefile.tricklib: No such file or directory
make[1]: *** No rule to make target '/path/to/trick/trick_source/share/trick/makefiles/Makefile.tricklib'.  Stop.
make[1]: Leaving directory '/path/to/trick/trick_source/er7_utils/integration/abm4'
Makefile:180: recipe for target '/path/to/trick/trick_source/er7_utils/integration/abm4' failed
make: *** [/path/to/trick/trick_source/er7_utils/integration/abm4] Error 2
```

It looks like it is trying to find `share` within `trick_source`. A bungled relative path might have done that.

If I undo this commit it builds fine.

**Comment by dbankieris** [comment]
@abrogley Sorry about that. Turns out this change wasn't as trivial as its predecessors. It's been reverted for now via ed5a5426b14853b6b2f9490055c965a548934103.
