### ISSUE TITLE
S_overrides.mk is included twice when building

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#360]
`S_overrides.mk` is directly included in `SIM_*/makefile`, which also includes `Makefile.sim`, whose `all` target calls `$(MAKE) -f build/Makefile_src`, which _also_ includes `S_overrides.mk`. Because exported variables are communicated to sub-makes, this double include results in any exported variables to which `S_overrides.mk` appends being appended to twice.

This issue was revealed by the introduction of support for Trickified libraries, which necessarily do something like:

`TRICK_USER_LINK_LIBS += -Wl,whole-archive myTrickifiedLib.a -Wl,-no-whole-archive`

Repeating that option forces the linker to link all symbols in the library twice, which results in a redefinition error for every symbol.

I think we can avoid including `S_overrides.mk` in `build/Makefile_src` by exporting a few more variables that we don't already. However, users will no longer be able to add prerequisites to targets  defined only in`build/Makefile_src` in their `S_overrides.mk`. I didn't see anything in jeod, but pong is using `$(S_MAIN)`. @alexlin0 is there any reason `all` would be an inferior target?

**Comment by alexlin0** [comment]
These changes removed the ability to attach additional dependencies to $(S_MAIN).  We need that capability.

**Comment by dbankieris** [comment]
Oops. I didn't mean to close this with that last commit.

**Comment by CTLaChance** [comment]
@dbankieris @alexlin0 What's the status of this issue? Can it be closed or is development still ongoing?
