### ISSUE TITLE
trick_qp chokes on log_frame* and log_timeline* on realtime runs with frame logging

### ISSUE THREAD

**Issue by rmaglothin** [nasa/trick#362]
I'm using Trick 15.2.3 on CentOS 6.8, Oracle JDK 1.8.0_66. 

When I try to plot data with trick_qp after a realtime sim run, the first step, opening the RUN directory, fails with a Java stack trace. The list of variables in the left pane has entries starting with "JOB_" If I delete the log_frame* and log_timeline* files in the RUN directory, then restart trick_qp, I am able to plot. If I disable frame logging (comment out "trick.frame_log_on()"), and re-run the sim, this also avoids the problem. Is this a bug or a feature?

**Comment by alexlin0** [comment]
Can you post the stack trace?  I am unable to recreate the problem here.

**Comment by alexlin0** [comment]
OBE, probably fixed...maybe.
