### ISSUE TITLE
no dyn varible in the  Data Recording editor help 

### ISSUE THREAD

**Issue by AiveHacker** [nasa/trick#364]
when is open trick-dre & trick window pops up and as by your trick tutorial i follow every step but why my DRE not showing dyn variable in the variable panels
![screenshot from 2016-12-09 12-18-38](https://cloud.githubusercontent.com/assets/11796112/21040240/aea37330-be09-11e6-92c0-b5ce2207984a.png)

**Comment by alexlin0** [comment]
Hi.  Can you run the following command in your simulation directory

`trick-sie dyn`

What is the output?  Does it find a lot of variable names with "dyn" or does it return an error?

**Comment by CTLaChance** [comment]
This issue has stagnated and does not require any changes to Trick. Closing for now.
