### ISSUE TITLE
Create a Python module for variable server communication

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#365]
Several groups have written Python utilities for communicating with a sim via the variable server. We should provide such a utility directly in Trick instead, similar to VariableServerConnection.java.

- We are best positioned to create a correct and robust implementation
- By providing one authoritative API, we eliminate disparate versions across various groups, reducing replication of effort
- By maintaining the API ourselves, we're less likely to break users when we change the underlying protocol

**Comment by ezcrues** [comment]
Hi Derek,

I agree.  We also have a C implementation.  It would be nice to provide a number of language implementations that are provided and supported by the Trick team.

Zack
*******************************************************************
* Edwin Z. Crues, PhD.           | Phone:  281.483.2902           *
* Mail Code: ER7                 | Mobile: 832.341.9023           *
* 2101 NASA Parkway              | FAX:    281.244.6116           *
* NASA Johnson Space Center      | Email:  edwin.z.crues@nasa.gov *
* Houston, Texas 77058, USA      |                                *
*******************************************************************

**Comment by lordmundi** [comment]
also want to upvote this.  We've been trying to maintain our own
implementations.  Would love to see one for python.  Would also love one
for Tcl.  :)

FG
