### ISSUE TITLE
Event messages not printing

### ISSUE THREAD

**Issue by danielmatz** [nasa/Trick#38]
Messages aren't being printed when an event fires.  This worked in Trick 10.  I do have the following in my input deck:

```
trick.set_event_info_msg_on()
```

**Comment by alexlin0** [comment]
What kind of event doesn't print?

During my testing, when I turn the flag on, my python events do print a message.  There are some inconsistencies in the application of the set_event_info_msg_on flag.  The flag only applies to non-read events created in python.  I can extend the set_event_info_msg_on flag to apply to all events regardless of their origin or kind, but I'm curious what kind of events you are using.
