### ISSUE TITLE
trick-dre application should support index expansion like trick-tv

### ISSUE THREAD

**Issue by doylewb** [nasa/trick#381]
The DRE Java application does not fully support arrays. Example variable array
`Sim.SensorData[0-5].Speed`

Saved to DR file as:
`drg[DR_GROUP_ID].add_variable("Sim.SensorData.Speed")`

Rejected by Trick
`Could not find Data Record variable Sim.SensorData.Speed`

Manually editing to fix DR file negates purpose of DRE.
`drg[DR_GROUP_ID].add_variable("Sim.SensorData[0].Speed")`

Ideal for DRE to prompt for array indexes similar to TV or at worst log the whole array.

**Comment by jmpenn** [comment]
trick-dre now has the capability to expand arrayed variables like trick-tv.
