### ISSUE TITLE
If a user adds "-I/usr/include" to TRICK_CFLAGS/TRICK_CXXFLAGS, bad things happen.

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#384]
If a user adds "-I/usr/include" to TRICK_CFLAGS/TRICK_CXXFLAGS, bad things happen.  Observed in 15.3.dev, need to see if also a problem in 17.

**Comment by jmpenn** [comment]
Added to trick_sims/Cannon/SIM_cannon_numeric/S_overrides.mk like so:

TRICK_CFLAGS += -I/usr/include -I../models
TRICK_CXXFLAGS += -I/usr/include -I../models

Built and ran the sim. No bad things appeared to happen.
