### ISSUE TITLE
Variable Server Not Updating Values When Pointer Changes

### ISSUE THREAD

**Issue by keithvetter** [nasa/trick#389]
This is an issue in Trick 15.  There is no problem in Trick 17.

The problem report was:
Anything called from the Trick Variable server with a pointer where the pointer changes, does not update.  This is causing several of our Robo/Dyn displays (and possibly other subsystem displays) to be incorrect.  Thomas found that the issue is resolved in Trick 17.

**Comment by dbankieris** [comment]
Closing as `WON'T FIX`. Upgrade to 17!
