### ISSUE TITLE
Using ccache seems to work but prints warnings

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#390]
I set TRICK_CC="ccache cc" and TRICK_CPPC="ccache c++" and trick to compile a sim.  It worked but there are some warnings about incorrect arguments to ccache.

**Comment by iamthad** [comment]
I've used ccache a different way: I change the absolute paths to the compilers in config_user.mk to relative paths, then I use a directory of ccache symlinks as described [in the manual](https://ccache.samba.org/manual.html#_run_modes), which I prepend to my path.

If at any time I want to not use ccache, I simply remove that directory from my path.

I haven't had any incorrect argument warnings this way.

**Comment by alexlin0** [comment]
Thanks for the info.  ccache will work with both methods now.

**Comment by iamthad** [comment]
Also useful: swig comes with a fork of ccache, so if you symlink ccache-swig to a link named swig, it'll also be cached. I don't know if it works via the prefix method.
