### ISSUE TITLE
make install fails without er7_utils

### ISSUE THREAD

**Issue by bitblit11** [nasa/Trick#4]
I had no problems building Trick on Fedora 21 until I ran sudo make install.  The makefile is looking for er7_utils.  Recommend either include er7_utils, or remove the dependency from the makefile.

**Comment by alexlin0** [comment]
Thanks for the feedback.  I will remove the er7_utils dependency from the make install rule.

**Comment by bitblit11** [comment]
Thanks.  I'll check it tonight and close the issue if it checks out.
