### ISSUE TITLE
SWIG does not take -MP argument everwhere.

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#400]
The commit 2e4c3286a3e211ada7fb992b0ecff12d99536b64 with no associated issue breaks compiles on RH6.  The SWIG version on that platform does not take the -MP option.

**Comment by dbankieris** [comment]
Looks like it's only available as of SWIG 2.0, which is approaching seven years old. Would you like me to update `configure` to require this version or revert this commit?
