### ISSUE TITLE
Loading A Checkpoint Core Dumps

### ISSUE THREAD

**Issue by keithvetter** [nasa/trick#403]
I took the $TRICK_HOME/trick_sims/Ball/SIM_ball_L2 and tried loading a checkpoint.  I tried reloading directly in the input file with a trick.load_checkpoint(<filename>) python statement and also tried loading a checkpoint using the sim control panel.  In both cases, I get a core dump and many error messages.  Here is the full output:

[kvetter@Rerun SIM_ball_L2]$ ./S_main_Linux_4.8_x86_64.exe RUN_realtime/input.py
/users/kvetter/dev/trick/bin/trick-simcontrol   Rerun.trick.gov 33574 &
|L   1|2017/03/29,15:13:33|Rerun.trick.gov| |T 0|0.000000| Freeze ON. Simulation time holding at 0.000000 seconds.
|L   1|2017/03/29,15:13:45|Rerun.trick.gov| |T 0|0.000000| Load checkpoint file /users/kvetter/dev/trick_sims/Ball/SIM_ball_L2/RUN_realtime/chkpnt_2.12.
Checkpoint Agent input_parser PARSE-ERROR line=216 : syntax error
Checkpoint Agent ERROR: Invalid reference: "ERROR"
Checkpoint Agent ERROR: Reference type is hosed.
Please report this error to the Trick Developement Team.
Checkpoint Agent input_parser PARSE-ERROR line=315 : syntax error
MemoryManager:ERROR:Couldn't find function "io_src_sizeof_managed()". dlerror= ./S_main_Linux_4.8_x86_64.exe: undefined symbol: io_src_sizeof_managed

MemoryManager:ERROR:size of type "managed" not found.

MemoryManager:ERROR:get_type_attributes failed for type: managed

MemoryManager:ERROR:Declaration "managed memory" failed.

Checkpoint Agent ERROR: Declaration failed.
Checkpoint Agent ERROR: 1 invalid declaration(s) and 0 invalid assignment(s).
Checkpoint Agent ERROR: Checkpoint restore failed.
MemoryManager:ERROR:Checkpoint restore failed.

Finished loading checkpoint file.  Calling restart jobs.

 ALERT: MessageTCDevice.cpp:223: Trying to write to a NULL device

 ALERT: tc_disconnect.c:20: Trying to disconnect a NULL device
Floating exception (core dumped)

**Comment by jmpenn** [comment]
The problem here is that $TRICK_HOME/include/trick/MessageTCDevice.hh doesn't have a Trick header. This is what caused the original problem. The second problem is the attempt to load a checkpoint that contained an un-addressed error.

It turns out that there are 22 header files in Trick that don't have Trick headers. They each need headers.

**Comment by jmpenn** [comment]
Commit message should be "Add Trick headers to include files without headers."

**Comment by jmpenn** [comment]
Updating the headers fixed the problem. Now the dumped checkpoint isn't broken, so it does core when reloaded.
