### ISSUE TITLE
Tutorial - Trick-ICG Command Not Found When Using Trick-CP on Tutorial

### ISSUE THREAD

**Issue by Archetype90** [nasa/trick#405]
I have worked through the tutorial, and on the final step, when using trick-CP to compile the simulation I am getting the following output - 

```
xxx@xxx-VirtualBox:~/trick_sims/SIM_cannon_analytic$ trick-CP
Building with the following compilation flags:
TRICK_CFLAGS   = -g -Wall -Wmissing-prototypes -Wextra -Wshadow -Imodels
TRICK_CXXFLAGS = -g -Wall -Wextra -Wshadow -Imodels
Running    ICG
make: /home/Trick/bin/trick-ICG: Command not found
make: *** No rule to make target `/home/Trick/share/trick/swig/swig_double.py', needed by `trick/swig_double.py'.  Stop.
```

The ICG file does not exist in the Trick/bin directory. I see no ICG file in this repository and there was no mention of the ICG file in the tutorial. But, the lack of any existing issues regarding this makes me believe I have done something wrong. Can anyone point me in the right direction? 

Edit: Quick note, that I do see the trick/share/man/man1/trick-ICG.1 file in the repo, but nothing else.

**Comment by jmpenn** [comment]
If the build and installation of Trick were successful
(see: https://github.com/nasa/Trick/wiki/Installing-Trick ), the bin directory should resemble the following:

anvil:~ penn$ ls $TRICK_HOME/bin

trick-CP		trick-gte		trick-mtv		trick-trk2ascii
trick-ICG		trick-gxplot		trick-qp		trick-trk2csv
trick-config		trick-jxplot		trick-sie		trick-tv
trick-dp		trick-killsim		trick-simcontrol	trick-version
trick-dre		trick-mm		trick-sniffer

Does your installation contain everything shown here?

**Comment by Archetype90** [comment]
The installation appeared to be successful - I did not notice any obvious errors during the configure, make, or install. The contents of my bin (pasted below) has everything you listed **except** trick-ICG, which is where my problem exists.

```
trick-config  trick-gte      trick-mm   trick-simcontrol  trick-version
trick-CP      trick-gxplot   trick-mtv  trick-sniffer
trick-dp      trick-jxplot   trick-qp   trick-trk2ascii
trick-dre     trick-killsim  trick-sie  trick-tv
```

**Comment by alexlin0** [comment]
Something has removed trick-ICG.  You would not have gotten this far without it.  I suggest running <code>make</code> in Trick's home directory again and see if trick-ICG returns.

**Comment by CTLaChance** [comment]
@alexlin0 Can this issue be removed?
