### ISSUE TITLE
make install incomplete

### ISSUE THREAD

**Issue by bitblit11** [nasa/trick#41]
make install copies the binaries to the install directory, but trick_dp fails to file gte.pm and terminates.  gte.pm is found in trick/bin/pm/gte.pm.  

Centos 6.6

What is the preferred deployment method?  Make install or set the path to the as built bin directory?  If preferred deployment is make install, recommend adding additional steps to satisfy runtime binaries.  If other method is preferred, recommend either updating the launch scripts or update installation instructions.

**Comment by alexlin0** [comment]
Historically Trick users have used Trick in the directory where it is compiled.  "Installing" Trick to /usr/local is new and not widely used.  I will be pushing a fix for trick_dp and other scripts that have the same problem.

**Comment by alexlin0** [comment]
Several recent changes in Trick have made Trick more make install friendly including moving all of Trick's code to standard directory names like creating a top level include directory to hold all of Trick's header files and creating a share directory to hold various install files for Trick.  Trick is equally happy staying in it's build directory and adding the built bin to the path or being installed in /usr/local.  All of Trick's executables have been tested after making install to /usr/local.

I'm closing this issue based on activity from other issues.
