### ISSUE TITLE
Trick View: Add option to hide search & tree panes

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#415]

**Comment by dbankieris** [comment]
We already attempt to do this via [JSplitPane.setOneTouchExpandable](https://docs.oracle.com/javase/7/docs/api/javax/swing/JSplitPane.html#setOneTouchExpandable(boolean)). However, the documentation notes that some look and feels may not support it. If we implement our own, we'll need to remove these calls to prevent inconsistencies.

**Comment by dbankieris** [comment]
Another option would be to set the look and feel to one we know supports this feature, but that's probably overkill. It's usually preferable to let the OS use its own L&F.

**Comment by CTLaChance** [comment]
Here is a branch that contains all of the work that I've currently done towards this enhancement:
https://github.com/nasa/trick/tree/HidePanesTV

There are still issues concerning the immediate display of toggled on panes. Will work on this more.
