### ISSUE TITLE
Monte Carlo dry run file cannot be used to drive monte carlo.

### ISSUE THREAD

**Issue by alexlin0** [nasa/Trick#43]
Monte Carlo dry run file cannot be used to drive monte carlo.  It's supposed to be able to do this.

**Comment by jmpenn** [comment]
My testing using SIM_cannon_integ indicates that a dry run file does in fact work to drive Monte Carlo.

I set  trick.mc_set_dry_run(1), and generated runs using trick.MonteVarRandom.GAUSSIAN.
Then a copied the resulting MONTE_RUN_TEST/monte_runs to "M_cannon_init_angle".
Then I read the monte values from "M_cannon_init_angle" trick.MonteVarFile. Seems to work fine.

Added the following to SIM_cannon_integ/RUN_test/input.py for testing:
########################
# Begin MonteCarlo Setup
########################
trick.mc_set_enabled(1)
trick.mc_set_num_runs(20)
#trick.mc_set_dry_run(1)

monte_var_src = 'file'

if monte_var_src == 'generated' :
    print "###############################"
    print " Generating Monte Carlo Values "
    print "###############################"
    var0=trick.MonteVarRandom("dyn.cannon.init_angle", trick.MonteVarRandom.GAUSSIAN)
    var0.set_seed(1)
    var0.set_sigma(0.6667)
    var0.set_mu(0.6)
    var0.set_min(.3)
    var0.set_max(.9)
    trick_mc.mc.add_variable(var0)

elif monte_var_src == 'file' :
    print "#####################################################"
    print " Reading Monte Carlo values from M_cannon_init_angle."
    print "#####################################################"
    var0 = trick.MonteVarFile("dyn.cannon.init_angle","M_cannon_init_angle", 2)
    trick_mc.mc.add_variable(var0)

else :
    print "#######################"
    print " No Monte Carlo Values."
    print "#######################"

######################
# End MonteCarlo Setup
######################
