### ISSUE TITLE
More verbose error handling for failed ifstream instantiations

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#431]
One such example where I had to modify Trick source to see the true error was in this block:

```
void Trick::MonteVarFile::set_file_name(std::string in_file_name) {
    delete input_file_stream;

    input_file_stream = new std::ifstream(in_file_name.c_str(), std::ifstream::in);
    if (input_file_stream->fail()) {
        std::stringstream string_stream;
        string_stream << "Trick:MonteVarFile the input file \"" << in_file_name <<  "\" failed to open";
        exec_terminate_with_return(-1, __FILE__, __LINE__, string_stream.str().c_str());
    }
    this->file_name = in_file_name;
}
```
The error message that results from this, `"file failed to open"` provides no details of the issue in question.  In our case, file permissions were fine, I was stumped for a long time until I finally went in and added this:

```
std::cerr << "Error: " << strerror(errno);
```

At which point, the true error message was exposed, in our case it's "Error: Too many open files".  It would be helpful if all failed stream checks would provide the `errno` information so that a user doesn't have to change the source code to see the specific cause.

**Comment by jmpenn** [comment]
Agree. It needs to be fixed.

**Comment by jmpenn** [comment]
"Make failed ifstream error message more informative." d7e3aa4b5cbde1c4322888740d0a71b2d00e2c62
