### ISSUE TITLE
Sim objects using uniform initialization syntax fail to compile

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#443]
Consider SIM_ball_L1's `S_define`

If line 91 is changed from
```c++
        ballSimObject() : state() , force() {
```
to
```c++
        ballSimObject() : state{} , force() {
```
which is valid C++11, the sim won't compile, with errors like the following:
```
Compiling  build/data/tfleming/.local/src/git/trick/trick_sims/Ball/SIM_ball_L1/io_S_source.cpp
In file included from build/data/tfleming/.local/src/git/trick/trick_sims/Ball/SIM_ball_L1/io_S_source.cpp:19:0:
/data/tfleming/.local/src/git/trick/trick_sims/Ball/SIM_ball_L1/S_source.hh:859:2: error: expected unqualified-id before ‘,’ token
  , force() {
  ^
/data/tfleming/.local/src/git/trick/trick_sims/Ball/SIM_ball_L1/S_source.hh: In constructor ‘ballSimObject::ballSimObject()’:
/data/tfleming/.local/src/git/trick/trick_sims/Ball/SIM_ball_L1/S_source.hh:856:5: error: expected ‘{’ before ‘public’
     public:
     ^
```

The relevant lines in S_source.hh are
```c++
    ballSimObject() : state{}

    public:
        virtual int call_function( Trick::JobData * curr_job ) ;
        virtual double call_function_double( Trick::JobData * curr_job ) ;
 , force() {
```

It's clear that CP thinks the braced-initializer is the constructor's body!

------------------------------------------

While this example isn't the most exciting, uniform initializers in the class initialization list can be very useful, e.g. when initializing a `const` aggregate class member.

The presence of an identifier immediately before the braces should prevent those braces as being considered the body of the constructor.

**Comment by alexlin0** [comment]
This may not be an easy thing to fix.  We use regular expressions to mach only a tiny percentage of c++ syntax while parsing the S_define.  Large shortcuts are in place when looking for things like constructors. 
 A curly brace in the initializer list makes finding the start of the constructor a lot harder with a simple regular expression.

**Comment by alexlin0** [comment]
Only SWIG 3.0 and above understands list initializer syntax out of the box.  I did not look for any command line argument flags to use with SWIG 2.0 and lower.

**Comment by iamthad** [comment]
SWIG 3.0's big feature was C++11 syntax support. I suspect 2.0 might not be able to handle the initializer lists.
