### ISSUE TITLE
Make the filenames of Trick's binaries consistent.

### ISSUE THREAD

**Issue by CTLaChance** [nasa/trick#449]
Currently there are two binary files in Trick/bin, trick-CP and trick-ICG, that contain capital letters. Every other binary files does not. The case convention for binary files should be consistent, regardless of what is chosen.

**Comment by lordmundi** [comment]
were binaries renamed?  i didn't see any commits attached to this.

**Comment by CTLaChance** [comment]
No, binaries were not renamed. It was a foolish suggestion after a temporary lapse in judgement and I have seen the error of my ways.

**Comment by lordmundi** [comment]
Great. Thanks.

FG
