### ISSUE TITLE
The Trick variable server is incorrectly using 224.3.14.15 as a multicast address.

### ISSUE THREAD

**Issue by jmpenn** [nasa/trick#452]
The Trick variable server is incorrectly using 224.3.14.15 as a multicast address. 

This is in a reserved range (between Nasdaqmdfeeds and London Stock Exchange) within 
AD-HOC Block II (224.3.0.0-224.4.255.255 (224.3/16, 224.4/16))
which may be **GLOBALLY** routed.

Trick should be using an address in the range 239.0.0.0 - 239.255.255.255 (Administratively Scoped), or better yet, 239.255.0.0 - 239.255.255.255 (Site-Local Scope), both of which are **NOT GLOBALLY** routed.

From CISCO SYSTEMS GUIDELINES FOR ENTERPRISE IP MULTICAST ADDRESS ALLOCATION:
"... the IANA has reserved the range of 239.0.0.0- 239.255.255.255 as Administratively Scoped addresses for use in private multicast domains."

Refs:
https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml
http://www.cisco.com/c/dam/en/us/support/docs/ip/ip-multicast/ipmlt_wp.pdf

Also see:
https://stackoverflow.com/questions/236231/how-do-i-choose-a-multicast-address-for-my-applications-use

**Comment by jmpenn** [comment]
The last three octets for of the multicast address, together with the port number represent the number PI &#03C0; . Presumably, this was to make it easier to remember. 

So,

**Comment by jmpenn** [comment]
Address is hardcoded in the following three files:
• trick_source/java/src/trick/simcontrol/SimControlApplication.java
• trick_source/java/src/trick/sniffer/SimulationSniffer.java
• trick_source/sim_services/VariableServer/VariableServerListenThread.cpp

**Comment by dbankieris** [comment]
Alex resurrected the old address in 12c7dbd4cf84a7cd4fb746c34a385edf2d34ebd5. We definitely don't need to use two addresses unless we actually intend to phase out the old address. I am doubtful that we'll do this, so I propose reverting both 8414735 and 12c7dbd4cf84a7cd4fb746c34a385edf2d34ebd5.

**Comment by alexlin0** [comment]
I'm ok with this.
