### ISSUE TITLE
ICG handling of \brief in comments differs on Linux and Mac

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#453]
On Linux, a comment such as the following is correctly parsed, and the correct units are determined:
```C++
double r; /**< \brief (m) Distance from CoM */
```
On the other hand, on Mac, the units are defaulted to 1, and the description field contains `(m) Distance from CoM`.

This appears to be another regular expression inconsistency.

**Comment by alexlin0** [comment]
bug confirmed.
