### ISSUE TITLE
Add summary of MC RUN exit statuses

### ISSUE THREAD

**Issue by danielmatz** [nasa/trick#481]
Apparently, when the `run_summary` file says `(0 errors)`, it doesn't mean that none of the RUNs returned a non-zero exit status.  It would be nice to have some kind of top level summary of how many RUNs returned a non-zero exit status, either in `run_summary` or elsewhere.

**Comment by CTLaChance** [comment]
When run_summary prints "0 errors", it is printing the number of runs that did not return with the "COMPLETE" exit status. 

Every run that returns with the following will be added to a queue and summarized in the run_summary file.
- INCOMPLETE
- CORED
- TIMEDOUT
- NO_PERM
- BAD_INPUT
- UNKNOWN

Could you please elaborate as to how you're getting non-zero exit status runs that are not being accounted for?

**Comment by danielmatz** [comment]
I can't speak for everyone, but for us there is no case where a run could give a non-zero exit status and we'd think it was OK.  In our applications, a non-zero exit status would always mean that we hit some error condition and terminated the run early.  We wouldn't want the master to try running that case again, since it would just fail again.  But it would be nice to have an indication that some of the runs returned with non-zero exit statuses.  As it stands now, I'd have to go post-process my data or look at every RUN_*/stderr or something to figure out if they completed without error.

**Comment by dbankieris** [comment]
Method by which the `S_main` process returns a non-zero exit status:

1. Some code somewhere calls `exec_terminate_with_return` with some return value `foo`
2. `exec_terminate_with_return` throws an `ExecutiveException` containing `foo`
3. That exception is caught in `Executive::loop()` and `foo` is stored in the field `Executive::except_return`
4. `Executive::loop()` returns `0` to `master()` (defined in `trick_source/sim_services/mains/master.cpp`)
5. `master()` calls `Executive::shutdown()`
6. `Executive::shutdown()` calls all `shutdown` jobs
7. `Executive::shutdown()` returns `Executive::except_return` (which is `foo`) to `master()`
8. `master()` returns that value (`foo`) to `main()` (defined in `SIM_*/build/S_source.cpp`)
9. `main()` returns that value (`foo`) and the process terminates with that exit status

For Monte Carlos, we need to distinguish between process exit status and MonteRun::ExitStatus, which is an `enum` defined in `MonteCarlo.hh`. Only a `MonteRun::ExitStatus` is sent to the master, not the slave's process exit status. This is done either by the slave parent process or the slave child process. After a slave is spawned (the parent process), it continuously waits for runs to be dispatched to it from the master. When a new dispatch is received, it `fork`s itself and executes the run in a child process. If the child process segfaults or times out, the parent process relays that information to the master by sending it the appropriate `MonteRun::ExitStatus` value. However, if the child process proceeds to the point at which `shutdown` jobs are called (step 6 above), then the child process itself sends `MonteRun::COMPLETE` to the master via `MonteCarlo::shutdown()`. This is where we would need to check `Executive::except_return` and send a different `MonteRun::ExitStatus` to the master, indicating that the run completed, but with a non-zero process exit status. This would require a new enum value, for which I suggest `MonteRun::FAILED`. The master would need to count these separately from `MonteRun::COMPLETE` runs.

**Comment by dbankieris** [comment]
Better late than never, eh @danielmatz?
