### ISSUE TITLE
Make install fails to successfully install Trick.

### ISSUE THREAD

**Issue by CTLaChance** [nasa/trick#495]
Entering **sudo make install** causes the installation to fail with the following return statement:

```
cp -r bin include lib libexec share /usr/local
cp: cannot stat 'lib': No such file or directory
Makefile:346: recipe for target 'install' failed
make: *** [install] Error 1
```

Make install is trying to recursively copy the 'lib' directory to /usr/local when it doesn't exist. Adding an empty folder titled 'lib' fixes this issue.

**Comment by CTLaChance** [comment]
You cannot run **make install** without first compiling Trick via **make.**

This is a simple user error. My mistake.

**Comment by alexlin0** [comment]
Reopening to add an error message to the install rule stating that Trick must be compiled first.
