### ISSUE TITLE
The source release needs clang and all of the other development tools configured.

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#50]
Our release is going to be a tar.gz file now.  This will not include a pre-build ICG.  So that means everyone needs clang/llvm and we need to ensure the configure script sets that up.

**Comment by excaliburtb** [comment]
Looks like Trick now requires llvm 3.4 at a minimum.

**Comment by Sstewart26** [comment]
VariableServerConnection.java uses a new java feature "implements AutoCloseable" that is not available in OpenJDK 1.6 or 1.7.

**Comment by alexlin0** [comment]
Java 1.6 is no longer supported by Trick.  Autoacloseable is available in 1.7.  

Note: Oracle announced that there will be no more Oracle JDK 7 public releases.  1.7 is end of life.  In the future our java code may only work with 1.8 and above.

**Comment by alexlin0** [comment]
excaliburtb: I believe that the minimum clang//llvm version is 3.3 now, but I rarely test that far back.  3.4 may make ICG emit false errors, I recommend 3.6 or 3.5 these days.

**Comment by hchen99** [comment]
AutoCloseable should be available since 1.7 with OpenJDK as well.
