### ISSUE TITLE
Make dependencies on .d files sometimes cause spurious rebuilds

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#501]
Running `make` in an already-built sim directory sometimes rebuilds a bunch of files that haven't changed, nor have their dependencies.

Investigating using `make -d` shows that the files are being rebuilt due to their corresponding `.d` generated dependency file.

~~It doesn't make sense in general for a rule to have dependencies on its own output, but I think it works most of the time since the `.o` and `.d` files end up with timestamps in the right order.~~

I'm not sure what the factor is that causes the issue to appear only sometimes. I suspect it has to do with the size of the sim, NFS, or `ccache`. ~~Regardless, I think having the `.o` files depend on their `.d` files is a logical error that should be corrected, and it does prevent the issue from occurring.~~

EDIT: I’m re-evaluating my description of the above as a logical error in light of Derek’s comment.
EDIT2: My new recommendation is to make the dependency files order-only prerequisites, rather than standard prerequisites. See below.

**Comment by dbankieris** [comment]
I believe the approach of `.o` files depending on their `.d` files is actually [reccommended](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/). The behavior you're seeing could indeed be related to NFS and time stamps. That would be tough to track down.

**Comment by iamthad** [comment]
Huh, I must have looked at that article half a dozen times without noticing that.

Let me re-read that and re-evaluate.

**Comment by iamthad** [comment]
The reason for having the dependency files as prerequisites of the object files is described in the section on [Handling Deleted Dependency Files](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/#depdelete):
> if a user happens to delete dependency files without modifying any of the source files, make will not notice anything amiss... add[ing] the dependency file as a prerequisite to the target... solves the problem nicely: when `make` checks the target it will see the dependency file as a prerequisite and try to build that. If it doesn’t exist, it will be marked out of date since it has an empty recipe, which will force the object target to be rebuilt (creating a new dependency file).

The issue of spurious rebuilds caused by the dependency file is mentioned in the linked article, [under the explanation of `POSTCOMPILE`](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/#combine):

> it’s been reported that some versions of GCC may leave the object file *older* than the dependency file, which causes unnecessary rebuilds.

They handle the issue with their `POSTCOMPILE` rule.

I both problems could be solved by making the dependency file an [order-only prerequisite](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html) of the object file. That way a missing dependency file would still trigger a rebuild of the object, but the spurious rebuild behavior would not occur, since the dependency file’s timestamp would not be checked.
