### ISSUE TITLE
Compiling unit tests returns numerous unused parameter and deprecated conversion warnings.

### ISSUE THREAD

**Issue by CTLaChance** [nasa/trick#504]
They're just warnings, so it's not breaking compilation, but I want to fix them regardless.

**Comment by dbankieris** [comment]
All warnings must be eliminated! If you aren't sated after fixing unit test warnings, turn on all the `-W` compiler options, build Trick, and take care of those as well.

**Comment by CTLaChance** [comment]
Heck ya!

**Comment by CTLaChance** [comment]
I've merged a few small changes into the master, but I'm not 100% finished with warnings just yet. This merge removed many unused variable warnings, but not all of them. I will leave this issue open until all warnings have been addressed.
