### ISSUE TITLE
TRICK_FORCE_32BIT ineffective from S_overrides.mk

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#509]
`TRICK_FORCE_32BIT` is checked in `Makefile.common`, which is included by `SIM_*/makefile` before `S_overrides.mk`. It would be nice if modifying `TRICK_FORCE_32BIT` in `S_overrides.mk` was effective.

**Comment by iamthad** [comment]
Doesn't Trick have to be compiled as 32-bit in order to link to a 32-bit sim? If so, it can't be turned on and off for individual sims.

**Comment by dbankieris** [comment]
It does, but Trick generates separate 32-bit and 64-bit libraries (under `lib` and `lib64`). So you could toggle it for individual sims, but only if Trick had already been built in both modes.

**Comment by iamthad** [comment]
Ah, I see.

**Comment by alexlin0** [comment]
This should work now because we added a S_pre.mk that is read in before Makefile.common.
