### ISSUE TITLE
What's the deal with trick_source/java/test/resources/S_sie.resource?

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#517]
What's the deal with [`trick_source/java/test/resources/S_sie.resource`](https://github.com/nasa/trick/blob/master/trick_source/java/test/resources/S_sie.resource)?

This looks very different from the `S_sie.resource`s that are currently generated.

**Comment by dbankieris** [comment]
That `S_sie.resource` file is in a format from an older version of Trick. Looks like maybe it's an example file for testing the Java apps, but I'm not sure.

**Comment by dbankieris** [comment]
Quite right. This should be resolved as part of #521.

**Comment by spfennell** [comment]
The old S_sie.resource file will be removed when #580 has been addressed.
