### ISSUE TITLE
Question: Why changes in source code does not affect the result?

### ISSUE THREAD

**Issue by nkapliev** [nasa/trick#529]
Hello Trick community,

I am trying to fix some issues in Trick core. 
But after I change the code, recompile the project and rerun the tests it looks like I did not change anything.
I am using this sequences of actions:  
```
# change some code in trick_source/sim_services
make clean
./configure
make
make test
```

Is there any additional step that I should do to rebuild the project from scratch?
Is there any cached object files or anything else that could not be removed by `make clean`?

**Comment by dbankieris** [comment]
That should be sufficient. You could try the following to return the repository to a clean state:

```bash
git clean -xdf
```

Beware that this will delete all untracked and ignored files. If you've created any new files, you should stage or stash them first.

**Comment by nkapliev** [comment]
Nice! Thank you, it helped! 👍
