### ISSUE TITLE
Rename data_record_utilities.cpp to fit our naming convention for swig intf files

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#559]
There are no C bound functions that can be called in the input file for data recording groups.  It would be nice if there were functions that access the functions within the DataRecordDispatcher class

```c++
int data_record_group_add(group_instance);
int data_record_group_remove(name);
int data_record_group_remove_all_groups();
Trick::DataRecordGroup data_record_group_get(name);
int data_record_group_enable(name);
int data_record_group_disable(name);
int data_record_group_record_now(name);
```

**Comment by spfennell** [comment]
These functions already exist. Changing issue to change existing file to fit naming convention

**Comment by spfennell** [comment]
Actually, it looks like there is no convention. Closing the issue
