### ISSUE TITLE
ICG sometimes outputs attributes = 63

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#568]
ICG will sometimes output an attributes value of 63 (`0b00111111`) instead of 15 (`0b00001111`).

I believe this occurs because the code to duplicate the IO field to the checkpoint field ([`FieldDescription.cpp:275`](https://github.com/nasa/trick/blob/master/trick_source/codegen/Interface_Code_Gen/FieldDescription.cpp#L275)):
```cpp
    io |= (io << 2 ) ;
```
gets called when the checkpoint fields have already been populated.

EDIT:
<del>This appears to happen (at least) in cases where `FieldDescription::parseComment` is called again after the `if (comment.empty())` clause that assigns `io = 15` ([`FieldDescription.cpp:118`](https://github.com/nasa/trick/blob/master/trick_source/codegen/Interface_Code_Gen/FieldDescription.cpp#L118)) is run. </del>

EDIT 2:
The io field is set to 15 by default. `io |= (io << 2)` shouldn't be called in that case.

**Comment by alexlin0** [comment]
I've seen the 63.  I've taken a quick look at it but haven't figured out the exact circumstances causing it.  Although it is an incorrect, it should not affect simulation operations.   The io parameter is a bitfield and we don't use anything above the first 4 bits.
