### ISSUE TITLE
Documentation: "7.10.12 DRBinary Recording Format" information is out of date

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#57]
For instance, it references sys.exec.out.time, which doesn't exist anymore.

**Comment by alexlin0** [comment]
But sys.exec.out.time does exist in a sense.  We still use that variable name when writing out time to data recording files.  We don't have a variable in Trick that tracks sim time in seconds, we have to calculate it, might as well use the old name then to create a new name.  Saves us from having to change all of our plotting tools to look for multiple names to represent time.

**Comment by lordmundi** [comment]
Plus, we parse the trk and look for these variables. Anything that would
help keep 3rd party tools from breaking would be much appreciated.

FG

**Comment by alexlin0** [comment]
closing this issue without actions.
