### ISSUE TITLE
javac dependency not satisfied by installation instructions

### ISSUE THREAD

**Issue by bitblit11** [nasa/Trick#6]
I'm using Fedora 21.  Java 1.8.0 OpenJDK is in the Fedora 21 repository, not 1.7.0.  But either way, java-1.8.0-openjdk did not install the required javac executable.  I had to install java-1.8.0-openjdk-devel.  Recommend updating the wiki to include supported Linux distributions and versions and confirming that java-1.7.0-openjdk package installs javac or if it requires java-1.7.0-openjdk-devel as well.

**Comment by bitblit11** [comment]
It compiles with java-1.8.0-openjdk without any problems.  I haven't thoroughly tested each GUI, but the few I checked out seem to work just fine.

**Comment by alexlin0** [comment]
Interesting, you would think that with "development" in the name that it would have included the javac compiler.  I've made a note of it in our wiki.  Thanks.

We've done some testing with 1.8, as far as we know everything should work.

**Comment by ezcrues** [comment]
Alex,

We use 1.8 on the Macs and it seems to work well.

Zack

**Comment by hchen99** [comment]
If Java OpenJDK makes some parts of GUI working funny (people experienced having problems like not being able to select items from a drop-down list and etc. using OpenJDK), you may want to switch to Java JDK 8 from oracle.com.
