### ISSUE TITLE
Using data recording feature DR_Changes_Step causes SIGSEGV

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#619]
Setting the recording frequency of a data record group to trick.DR_Changes_Step causes a core dump.

**Comment by spfennell** [comment]
Is this related to[https://github.com/nasa/trick/commit/1e783fb49c683ecb249d5d8beb99fbdd97b3f40d]( https://github.com/nasa/trick/commit/1e783fb49c683ecb249d5d8beb99fbdd97b3f40d)?. Is the issue fixed? @alexlin0
