### ISSUE TITLE
QUESTION: Linking in external library

### ISSUE THREAD

**Issue by carefulguy** [nasa/trick#630]
I've tried to piece together references in the docs to linking in an external library without success.  Whatever I do, the library (built locally) cannot be found during linking.

Things I've tried:
- Adding the library location through TRICK_USER_LINK_LIBS += -L<dir> in S_overrides.mk
- Adding the same through the environment directly
- Adding the library directory through TRICK_EXEC_LINK_LIBS instead (the difference is unclear)
- Adding the library as a TRICK_LDFLAGS += -l<libname>
- Adding the library .so in the C header file LIBRARY_DEPENDENCIES 
- Tried both absolute and relative paths

My setup:
In S_Overrides.mk:
TRICK_USER_LINK_LIBS = -L<abs/path/to/my/lib>
TRICK_USER_LINK_LIBS += -l[libname]

In Header file:
LIBRARY_DEPENDENCIES:
   ((<full_libname_with_lib_prefix>.so))

After compiling, I get:
./S_main_Linux__x86_64.exe: error while loading shared libraries: <full_libname>.so: cannot open shared object file: No such file or directory

The library in question does appears in /build/S_library_list, oddly enough.

Any help is appreciated.  Thanks!

**Comment by iamthad** [comment]
If it’s a shared library it needs to be somewhere the dynamic linker can find it. Try setting the LD_LIBRARY_PATH environment variable to include the directory containing the .so file.

**Comment by carefulguy** [comment]
ah. Thanks Thad - that's exactly what I was missing.

**Comment by dbankieris** [comment]
While `LD_LIBRARY_PATH` is a convenient temporary development solution, you should not use it in "real" code.  
https://gms.tf/ld_library_path-considered-harmful.html  
http://xahlee.info/UnixResource_dir/_/ldpath.html

**Comment by carefulguy** [comment]
Luckily, none of my code is real
