### ISSUE TITLE
QUESTION: Is there a way to output an ephemeris file (such as SPK) directly from a Trick simulation?

### ISSUE THREAD

**Issue by samwalbert** [nasa/trick#634]
I know I can use the Trick data recorder to output whatever variables I want, but I am hoping to output a correctly formatted ephemeris file which can then be read by GMAT. The acceptable formats include SPK, STK, and Code500.

**Comment by dbankieris** [comment]
The built-in supported data recording formats are ASCII, HDF5, and Trick binary. However, the framework is extensible, so you could write you own `DataRecordGroup` subclass to output the desired format.
