### ISSUE TITLE
Executive/Makefile is copied into all er7_utils directories

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#637]
This caused 6e1829410054db461b9a58e3f55bef912a720e65 to break the build since the path to the top of Trick is different from the Executive directory vs the er7_utils directories.

@alexlin0 Is this copying behavior a relic from when er7_utils was a separate repository? Can we get rid of it and give er7_utils its own Makefile?

**Comment by alexlin0** [comment]
The copying of the makefile is a relic from whe the er7_utils was a sepearte repository.  I vote for giving the er7_utils directory a permanent makefile now.
