### ISSUE TITLE
Pre-integration and Post-integeration jobs not showing when echo-jobs is on.

### ISSUE THREAD

**Issue by jmpenn** [nasa/trick#642]
Rachel Borland said she is seeing this in Trick 13.5

**Comment by spfennell** [comment]
In the problem sim, integ-loop is echoing but pre-integeration, integration, and post-integration jobs are not echoing. We have not been able to reproduce this bug in 13.5 or 17. 3 with other sims.  Needs further investigation with that particular sim to fix the issue.

**Comment by spfennell** [comment]
I am closing this for now. May re-open after the sim has been transitioned to 17 and the issue persists
