### ISSUE TITLE
`configure --without-x` doesn't work

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#651]
I'd expect `configure --without-x` to allow Trick to be configured on a host that does not have the X windows headers or libraries. Instead, `configure` fails:
```
configure:4526: checking for X
configure:4704: result: disabled
configure:4720: error: could not find Xwindows development libraries and/or headers
```

While there are parts of Trick that require X (i.e. the data products GUI apps), the components necessary to run a sim don't need it. It would be valuable to be able to configure Trick on a completely headless system, without X headers or libraries installed.

**Comment by alexlin0** [comment]
I wrote a duplicate issue and worked it under that issue. #735
