### ISSUE TITLE
Invalid IO code for for templates with negative arguments

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#660]
Looks like we need more sanitizing of IO variable names. This is an issue for the [Eigen library](http://eigen.tuxfamily.org/index.php?title=Main_Page), which has negative default values for some template parameters.

foo.hh
```c++
// @trick_parse{everything}
template <int T> class Foo {}; 
```

S_define
```c++
#include "sim_objects/default_trick_sys.sm"
##include "foo.hh"

class Sandbox : public Trick::SimObject {

    public:

    Foo<-1> foo;

    Sandbox() {}

};

Sandbox sandbox;
```

output
```bash
build/class_map.cpp: In function ‘void populate_class_map()’:
build/class_map.cpp:90:44: error: expected initializer before ‘-’ token
     extern ATTRIBUTES  attrSandbox_foo_Foo_-1_[] ;
                                            ^
build/class_map.cpp:91:59: error: ‘attrSandbox_foo_Foo_’ was not declared in this scope
     class_attribute_map->add_attr("Sandbox_foo_Foo_-1_" , attrSandbox_foo_Foo_-1_) ;
                                                           ^
build/class_map.cpp:91:80: error: unable to find numeric literal operator ‘operator"" _’
     class_attribute_map->add_attr("Sandbox_foo_Foo_-1_" , attrSandbox_foo_Foo_-1_) ;
                                                                                ^
make: *** [build/class_map.o] Error 1
make: *** Waiting for unfinished jobs....
build/users/dbankier/trick/sims/SIM_negative_template_parameter/io_S_source.cpp:2057:32: error: expected initializer before ‘-’ token
 ATTRIBUTES attrSandbox_foo_Foo_-1_[] = {
                                ^
build/users/dbankier/trick/sims/SIM_negative_template_parameter/io_S_source.cpp:2182:12: error: expected ‘}’ at end of input
 } umSandbox;
            ^
make: *** [build/users/dbankier/trick/sims/SIM_negative_template_parameter/io_S_source.o] Error 1

```

**Comment by jeremypriest** [comment]
Seeing this issue on Trick 19.3.1... Any chance of an upcoming fix?

**Comment by spfennell** [comment]
@jeremypriest 

This fix I am adding might address some of your issues, but we encourage Trick users to exclude third-party libraries that cause compilation problems from the Trick build. Trick code generation/memory management is not C++ complete, and Eigen in particular has a lot of really complex code that can cause our code generators to fail. The libraries will still be compiled and linked in, they just won't be managed by trick and available to TV/the input processor. You can still point to the data and access it from your own pointers/wrapper functions. Here are some guides on how to exclude code from ICG/swig:

https://nasa.github.io/trick/howto_guides/How-To-Exclude-Code.html
https://nasa.github.io/trick/documentation/building_a_simulation/Making-the-Simulation.html#example-of-how-to-exclude-a-directory-from-icg-during-cp
https://nasa.github.io/trick/documentation/building_a_simulation/Model-Source-Code.html#excluding-header-file-code

**Comment by jeremypriest** [comment]
Hey Scott, this is super useful for a newbie to Trick like me. Much appreciate the pointers, and of course the quick fix!

**Comment by aadhi0319** [comment]
I was able to follow this discussion to disable the ICG for processing Eigen, but I am still confused as to how to see the Eigen vector in Python (maybe as a list). Can we add custom Swig templates to Trick?
