### ISSUE TITLE
llvm scan build or bear support enhancement

### ISSUE THREAD

**Issue by amishscientist** [nasa/trick#663]
It would be a nice enhancement to trick-CP if there was a way to break up the make portion form trick-CP that way you could run llvm build-scan ( https://clang-analyzer.llvm.org/scan-build.html ) make or bear ( https://github.com/rizsotto/Bear ) make to generate the build scan data or the llvm compilation data base in the bear case.  Mabye trick-CP --make 'build-scan -o ./'

**Comment by iamthad** [comment]
If I remember correctly, `bear trick-CP` does the right thing for me.

**Comment by amishscientist** [comment]
scan-build -o ./SCAN_BUILD/ trick-CP

scan-build: Removing directory './SCAN_BUILD/2018-08-29-132214-60756-1' because it contains no reports.
scan-build: No bugs found.

it complied but it put nothing in the scan build.  When I hacked trick to run it inside of trick-CP it had plenty to say about my sim.

**Comment by amishscientist** [comment]
The Good News:
So using my raspberry pi I down loaded the latest version of trick.  
Ran scan-build ./configure
Then Built trick
Then cd to SIM_Ball++_L1
Then scan-build -o ./Scan ../../bin/trick-CP 
It worked just fine. 
 
The Bad News:
scan-build: 84 bugs found.
scan-build: Run 'scan-view /home/pi/Projects/trick/trick_sims/SIM_Ball++_L1/Scan/2018-09-13-220016-9371-1' to examine bug reports.

The Not So Bad News:
All 84 bugs looked like they were in swig auto generated code
[SIM_Ball++_L1 - scan-build results.pdf](https://github.com/nasa/trick/files/2381788/SIM_Ball%2B%2B_L1.-.scan-build.results.pdf)
 code.
