### ISSUE TITLE
Trick scan-build report

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#671]
Scan-build (a static analyzer) reported some problems with the Trick code base that need to be investigated. A list of these problems are in the pdf below. I deleted rows that were generated from scanning swig code. Thank you Jon Borland for providing the report. 

Edit: added an index column
[scan-build-trick.pdf](https://github.com/nasa/trick/files/2397808/scan-build-trick.pdf)

**Comment by abrogley** [comment]
Have y'all tried cppcheck? A quick run on my end finds quite a few potential memory leaks and other issues. I can post the findings if you like.

**Comment by dbankieris** [comment]
We don't do code scanning of any type that I'm aware of. Definitely a weakness in our continuous integration.

**Comment by abrogley** [comment]
Here is cppcheck's findings as of commit fccf320 on nasa/trick:master.

(error) and (warning) findings are most significant.

[cppcheck_trick_full.txt](https://github.com/nasa/trick/files/2398734/cppcheck_trick_full.txt)

**Comment by alexlin0** [comment]
I was looking at the cppcheck list.  The first several errors are in the sim, SIM_leaks.  The purpose of this sim is to purposely leak memory.  Please leave those leaks. 😄

**Comment by abrogley** [comment]
There will be a lot of false positives like that. For instance I also noticed that cppcheck didn't know that TEST_F is a common test function so you can ignore those fake syntax errors too.

**Comment by amishscientist** [comment]
Just wondering which version of cpp check you were using?

**Comment by abrogley** [comment]
1.84

**Comment by amishscientist** [comment]
1.85 just came out today.  Another thing to check is the cppcheck addons.  If you have done the work to correctly configure cppcheck you might as well run the addons.

**Comment by abrogley** [comment]
I'll leave my setup scripts here, and let whoever wants to run with it give it a go.

Build 1.85:

```
git clone https://github.com/danmar/cppcheck
cd cppcheck
make SRCDIR=build CFGDIR=cfg CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function"
```

Run Cppcheck on Trick:
```
./cppcheck --enable=style -iio_src -iswig -f ../trick/trick_source &> cppcheck_trick.out
```

**Comment by amishscientist** [comment]
I normally use --enable=all -j $CPUToUse   --dump  ./foo

Using more then one core the -j option does turn off the unused function check. 
--dump makes the dump files that are needed for running the cppcheck addons.  The dump files are basicly cppchecks version of an AST.

Then to run a cppcheck addon you just 

python addon.py foo/*.dump

Here is the list of current addons https://github.com/danmar/cppcheck/tree/master/addons
I mainly use misra.py, cert.py, and threadsafety.py
