### ISSUE TITLE
Restore Makefile variables that grouped object code by directory

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#672]
I need the capability back where I only want to apply CXXFLAGS to object code in certain directories.  I could do this because we had makefile variables that listed object code by directory. When the makefile was redone, these intermediate variables were removed and I lost this capability.

**Comment by dbankieris** [comment]
Isn't that what `makefile_overrides` is for?

**Comment by dbankieris** [comment]
@alexlin0 Can I close this?

**Comment by alexlin0** [comment]
No
