### ISSUE TITLE
MonteVarFile.cpp:102:24: error: ‘nullptr’ was not declared in this scope

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#684]
On latest commit 587ce0aab5bc32c2afcca4274edec55481b1385b, configured with `./configure --without-hdf5` on CentOS 7.4, `gcc (GCC) 4.8.5 `, trick will not build:
```
MonteVarFile.cpp: In member function ‘virtual std::string Trick::MonteVarFile::get_next_value()’:
MonteVarFile.cpp:102:24: error: ‘nullptr’ was not declared in this scope
             temp_str = nullptr;
                        ^
```

**Comment by alexlin0** [comment]
The latest stable build is the latest release.  The master branch is never assumed to be stable.

**Comment by ddj116** [comment]
:+1: So regarding process, if I find a bug in an older version of Trick, say 13 or 15, would you prefer I try to replicate that bug at the last stable tag? I had assumed you'd want users attempting to replicate it on the bleeding edge to ensure it still exists, but I can change my process if y'all would prefer that.

**Comment by dbankieris** [comment]
@ddj116 I would prefer that you test on the latest commit.
@alexlin0 I would prefer that the latest commit always builds.

**Comment by alexlin0** [comment]
@dbankieris I too would prefer the latest commit always build, but do not want to put in extra infrastructure and process to ensure that.  I prefer a lightweight process that allows me to make simple changes without a lot of overhead.  It's not a perfect system, sometimes the build breaks, but we are usually quick to find and fix it.

@ddj116, it isn't the user's responsibility to determine if a bug on an older release is also present on the bleeding edge.  We do appreciate if you do.  On the commits page there is a check mark on the commits that have passed the continuous integration unit tests.

**Comment by ddj116** [comment]
Ahh, thanks -- yeah I knew there was a check mark somewhere but I couldn't find it.
