### ISSUE TITLE
Trickified classes are not in S_sie.resource

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#688]
@alexlin0 You [commented out](https://github.com/nasa/trick/commit/5285f1a72ee8d172acd7b698534549a4c3b64abd#diff-d989acac02c04330f5cc631b81ebc564R246) the logic for including Trickified classes in `S_sie.resource`. Explain yourself, sir!

**Comment by genti337** [comment]
Is this still an open issue?  I am working on a project with trickified libraries and cannot see the variables in the trickified library using `trick-sie`.

**Comment by dbankieris** [comment]
Still an issue, yes. I'll corner @alexlin0 and force repentance.
