### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [nasa/trick#69]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/nasa/trick/blob/11253dcfcb585cbd054b542e6665e2be80e64fbb/configure.ac#L2 "Configuration checks")?

**Comment by alexlin0** [comment]
Yes, I would.  Thanks for the suggestion.

**Comment by elfring** [comment]
Thanks for [your improvement of the build specification](https://github.com/nasa/trick/commit/9a32414be4d9d44a0a82f8a5ba21e0fb05759b97 "Reuse of AX_PTHREAD").
