### ISSUE TITLE
Trick events that produce a traceback should terminate the sim

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#693]
Currently, any trick event that produces a traceback of any kind does not terminate the simulation but does stop the execution of the python event block.  Consider this example, where I define 3 new trick events in `trick_sims/SIM_cannon_eulercromer`:

```
trick.add_read(0.0, """
print "First"
dyn.cannon.acc[0] = trick.attach_units( "d",1.0)
print "End First"
""")
trick.add_read(0.0, """
print "Second"
dyn.cannon.acc = 2.0
print "End Second"
""")
trick.add_read(0.0, """
print "Third"
dyn.cannon.acc[1] = [2.0, 3.0]
print "End Third"
""")

```

Here's the output for these three `add_read` statements:

```
First
Units specifications have different number of units_primitives.
|L   3|2018/11/05,15:00:47|0f1df6e90723| |T 0|0.000000| Memory Manager ERROR: Can't convert "d" to "M/s2".
Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: Units Conversion error in method swig_ref::__setitem__
Second
Traceback (most recent call last):
  File "<string>", line 3, in <module>
TypeError: Right hand side could not be converted to proper array type
Third
Cannot assign list to a scalar value
Traceback (most recent call last):
  File "<string>", line 3, in <module>
IndexError: Error in method swig_ref::__setitem__
... clipped ...
SIMULATION TERMINATED IN
  PROCESS: 0
  ROUTINE: Executive_loop_single_thread.cpp:93
  DIAGNOSTIC: Reached termination time

       SIMULATION START TIME:        0.000
        SIMULATION STOP TIME:        5.200
     SIMULATION ELAPSED TIME:        5.200
        ACTUAL CPU TIME USED:        0.036
       SIMULATION / CPU TIME:      146.281
     INITIALIZATION CPU TIME:        0.028
~/trick/trick_sims/SIM_cannon_eulercromer > echo $?
0
```

Notice that none of the `End *` prints are executed and the sim returns zero, indicating success.  As a trick user, this seems very intuitive.  Since the sim doesn't terminate and just continues on it's merry way as if the `add_read` logic was never executed in the first place, if the user doesn't see the traceback, they will never know there was a problem.  This is even more of an issue for monte-carlo users, where the output typically whizzes by quite quickly.

One workaround is to define `try/except/terminate` logic around every Trick event that the user creates, but this is painful and prone to error.  Are there legitimate use cases where the user would prefer the current behavior (non-fatal failure and ignore the remaining block)?  It seems like the "fail sim on event failure" would be much more useful to 99% of users, and that is what I'm requesting here.  Or, at least an option to turn it on.

**Comment by dbankieris** [comment]
A counter example would be someone like TS-21 who runs a training sim for 12 hours and then fires a malfunction with a typo. They probably don't want the sim to terminate in that case. @alexlin0 is amenable to an option that controls Trick's response, so long as it defaults to the current behavior for backward compatibility.

**Comment by excaliburtb** [comment]
We could at least capture the errors better via the try-except block around the string block with the error is sent to send_hs or something.

**Comment by alexlin0** [comment]
This exits with a non zero return value for me.  It is a little more typing, but I think it's pretty clean.
```python
    trick.add_read(0.0, """
try:
    print "First"
    dyn.cannon.acc[0] = trick.attach_units( "d",1.0)
    print "End First"
except Exception as e:
    trick.exec_terminate_with_return(1,"read_at_0.0",sys.exc_info()[2].tb_lineno,str(e))
""")
```
