### ISSUE TITLE
Java Bug Workaround: Java GUIs do not behave correctly with 3 displays

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#698]
GUI menus ('File', 'View', 'Actions', etc) cannot open and trigger an exception when on a third display. Ubuntu 18.04, java 9 and up. Related issue: [https://bugs.openjdk.java.net/browse/JDK-8204646](https://bugs.openjdk.java.net/browse/JDK-8204646)

This is a java bug, I'm creating an issue to keep an eye on it. If this is causing you problems, consider regressing to java version 8u171 or not using 3 displays.

**Comment by jmpenn** [comment]
Don't think this is the place for this kind of information, because can't do anything about.

**Comment by dbankieris** [comment]
It might be useful if someone experiences the problem and comes here looking for a related issue, but I'm going to close it since there's no action for us to take.

**Comment by spfennell** [comment]
Do we have a 'known issues' section on github or the wiki? If I don't post this here than someone else will, because on the surface it seems like an issue with the GUI.

**Comment by alexlin0** [comment]
Wd did have a section like that many years ago, but I don't think we have one now.  We might want to add one to the wiki.

**Comment by dbankieris** [comment]
GitHub's Issues is where known issues go :)

Creating and immediately closing an issue for problems we can't do anything about is an ok approach in my opinion.
