### ISSUE TITLE
Unit.hh missing from files_to_ICG.hh & sim_services.i

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#718]
```bash
MemoryManager:WARNING:(build/users/dbankier/trick/sims/SIM_sandbox/io_S_source.cpp:2090): Couldn't find an io_src_sizeof_ function for type Unit[io_src_sizeof_Unit()].

MemoryManager:WARNING:ATTRIBUTES for type "Unit" not found.

ERROR: Trick::MemoryManager::restore_stls called with name = sandbox.u and attr = NULL.
```

This isn't the first time Trick has complained about its own types. Shouldn't we ICG all of Trick's headers? Users should expect to be able to use any Trick-defined type without Memory Manager warnings.

**Comment by alexlin0** [comment]
Because some structures we don't have to parse.  This Unit class for instance, it is not normally a persistent instance.  Usually it is instantiated in a code block, used to make a conversion, and freed at the end of the code block.  Normally we don't need to know what is inside.
