### ISSUE TITLE
Investigate C11 Threads

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#720]
I'm sure we can convert to C11 Threads.  Should we?  Would it open the possibility of a native Windows port?

**Comment by iamthad** [comment]
Are you thinking C11 or C++11?

**Comment by spfennell** [comment]
Microsoft doesn't support C11 threads, only std::thread in <thread>.

**Comment by alexlin0** [comment]
I was leaning towards the C11 version because the calls look like direct replacement for the pthread calls we use.  But I'd also like to go with the more widely available version.  Going to the C++11 would be a little bit of work, but probably not too difficult.

**Comment by jmpenn** [comment]
It appears that C11 threads is being supported only very recently.

**GNU Support** 
Glibc 2.28 added support for ISO C threads (ISO/IEC 9899:2011), August 1 , 2018
According to glibc 2.28 release notes, it requires linking against
libpthreads.

So, they will apparently be supported by GCC 4.9 and beyond.

Centos 7.5 is distributed with gcc 4.8.5, and Glibc 2.17, and does not support <threads.h>

**LLVM Support**
For LLVM / Clang it seems a bit murkier. Haven’t yet been able to find a definitive answer.

Xcode version 9.3 does not support <threads.h>

**Testing For ISO C Thread Support**
If the macro constant __STDC_NO_THREADS__ is defined by the compiler, the header <threads.h> and all of the names listed here are not provided.

#ifdef __STDC_NO_THREADS__
#error  "No threading support"
#else
#include <threads.h>
#endif
int main( int argc, char* argv[]) { return 0; }

% c++ -std=c++11 ttst.cpp -o ttst

**Comment by alexlin0** [comment]
OK, sounds like we're sticking with POSIX threads for the foreseeable future.
