### ISSUE TITLE
Trick 15: convert_swig does not convert #includes without a / correctly

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#722]
`convert_swig` produces `.i` files from `.h` files. As part of that process, it turns `#include` statements in the `.h` files into `%import` statements in the `.i` files. The `.i` files are [always output](https://github.com/nasa/trick/blob/d7cb67363b33ae8f505b95bf513b8ac864c057c6/bin/convert_swig#L444) in a `swig` directory. However, the [line](https://github.com/nasa/trick/blob/d7cb67363b33ae8f505b95bf513b8ac864c057c6/bin/convert_swig#L418) handling `#include` paths that do not contain `include` or `/` does not prepend `swig` to the path. So `#include "Foo.hh"` becomes `%import "Foo.i"`, while it ought to be `%import "swig/Foo.i`". This doesn't produce an error because of our use of [`-ignoremissing`](https://github.com/nasa/trick/blob/f0537efb0fa3cb5c0c84e36b60f055c1d1c60d21/libexec/trick/make_makefile_swig#L234), which is necessary due to our use of [`-includeall`](https://github.com/nasa/trick/blob/f0537efb0fa3cb5c0c84e36b60f055c1d1c60d21/libexec/trick/make_makefile_swig#L234), the reason for which I don't remember.

This led to some strange behavior in RAMTARES where the SWIG-wrapper functions were modifying the [wrong memory locations](https://gitlab-fsl.jsc.nasa.gov/ramtares/ramtares/issues/287#note_175938) when assignments were made in the input file, and there was no indication that the intended assignment had failed.

More investigation and details to come next year.

@ddj116

**Comment by ddj116** [comment]
Thanks for the workaround I can use in the meantime!  Happy Christmas and Merry holidays!

**Comment by dbankieris** [comment]
The problem was actually a trailing whitespace in the `#include` line that Trick 13 wasn't trimming, which caused the [file-existence check](https://gitlab-fsl.jsc.nasa.gov/ramtares/trick/blob/5072d1faebaec9f7d3bb79042e55a233cf12fbe1/bin/convert_swig#L388) to fail when attempting to deduce the absolute path. Trick 17 properly [strips trailing whitespace](https://github.com/nasa/trick/blob/35b4cf7880526ca4147b75d5ab30be7a03182ccd/libexec/trick/convert_swig#L239).

**Comment by ddj116** [comment]
Thanks @dbankieris ! For the record, the one-line fix you recommended I have applied on our 13.2.1 franken-version of Trick:

![convert_swig_fix](https://user-images.githubusercontent.com/3249339/51950236-4d28f400-23f5-11e9-837d-72eb7cf5e4ae.png)

Sim built fine and it appears the regression deltas caused by the modification of the wrong memory addresses are gone, although some of the runs are still going so I'm not 100% on this yet.

**Comment by ddj116** [comment]
OK I'm 100% certain this has fixed my problem.  `CmdPayloads.i` now has the correct full path to other `%import`'ed `.i` files and the regression changes are gone.

Thanks again, if y'all concur that this is the correct approach long term I'll patch our version of trick with this one-line fix and move forward with my work.

**Comment by dbankieris** [comment]
Concurrence committed!
