### ISSUE TITLE
Trick embedded web server

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#730]
Add embedded web server support for the trick variable server
As suggested in Issue #678

**Comment by spfennell** [comment]
In very early development, here is a preview @lordmundi

![wsc](https://user-images.githubusercontent.com/19922011/52228849-044fc000-2879-11e9-8663-187c6ca2c235.png)

**Comment by lordmundi** [comment]
very very cool... make sure there is some RESTful interface somewhere to
get the current value of a variable... like a GET to
localhost:3000/vars/<varname>

i'm sure other interesting toplevel could be in there besides vars, such as
/jobs, /sim_info, /events, etc.

i'm sure more interesting API requests will be made later, like how to
schedule variables to show up over a websocket at some rate... but just
make sure that the simple stuff is simple!  :)

this is really great stuff!

FG

FG

**Comment by spfennell** [comment]
@lordmundi good suggestions. Currently the proxy server expects a socket.io connection which you can subscribe to, add variables, or send commands to the sim. HTTP/REST might be a little to slow for the kind of performance we'd want, but I'll definitely look into it. The socket.io API is designed to be user friendly if they want to create their own web clients.

**Comment by spfennell** [comment]
@lordmundi Ah, I see. I'll add it in. 

Thanks again

**Comment by ddelago** [comment]
@lordmundi That is exactly what I've been working on. I have it set up using NodeJs with the Express framework. Works exactly as intended using the REST interface. Like @spfennell said there are cons to using this method but it just makes things very simple if some client wants to fetch a page of variables from the server.

**Comment by spfennell** [comment]
I created a proxy server with node.js, be we have decided to re-engineer it in C/C++ as a part of Trick. This will be contained in the mongoose-based embedded web server (see issue #756)

**Comment by jmpenn** [comment]
#756
