### ISSUE TITLE
Trick MC runs the runs individually when a variable name is incorrect (13.5)

### ISSUE THREAD

**Issue by obei10** [nasa/trick#731]
Trick has a weird bug where the Monte Carlo creates an MC file, but does not create RUN directories underneath.  It instead runs the number of runs individually, overwriting the send_hs file it creates in the MONTE directory.  This occurs when a user fat fingers a variable name.  While, I agree it originally is user error, Trick should not be running this way without a warning message of some sort.  It is a red-herring when it comes to debugging what is going on.

**Comment by spfennell** [comment]
@obei10 it was fixed here in issue #269

**Comment by spfennell** [comment]
Commit numbers are 
[` [86b5158](/nasa/trick/commit/86b5158e84383271f030534e1607bf26b0b640e9)`](https://github.com/nasa/trick/commit/86b5158e84383271f030534e1607bf26b0b640e9)
[` [bc6cb58](/nasa/trick/commit/bc6cb589e3f30d445737d984c122a9dc49034024)`](https://github.com/nasa/trick/commit/bc6cb589e3f30d445737d984c122a9dc49034024)
[` [3a26192](/nasa/trick/commit/3a261929e81f5f55711381224e647056f1ab9b0f)`](https://github.com/nasa/trick/commit/3a261929e81f5f55711381224e647056f1ab9b0f)
[` [4de4bf0](/nasa/trick/commit/4de4bf0692c49fd60dbbc2b836e6b68120605033)`](https://github.com/nasa/trick/commit/4de4bf0692c49fd60dbbc2b836e6b68120605033)
