### ISSUE TITLE
Put Derek's warning in when maximum data record file size reached.

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#738]
When you hit the maximum data record file size, default 1Gb, then print a warning that the max was reached and how to fix it.

**Comment by dbankieris** [comment]
And print it at the bottom of the file itself, not in the terminal where no one will ever see it.

**Comment by iamthad** [comment]
What is the rationale for limiting the size by default?

**Comment by dbankieris** [comment]
Alex got tired of people accidentally leaving sims running overnight and filling up our filesystem servers.

**Comment by spfennell** [comment]
@dbankieris It looks like I ended up printing the error to std::cerr, maybe we had an in-person discussion about it and decided to go with that? Or maybe I just ignored your request to print at the end of file. Do you remember?

**Comment by dbankieris** [comment]
I do not. Maybe Alex vetoed me. I still think it belongs in the file.
