### ISSUE TITLE
Possible to display all sim variables through Trick Variable Server?

### ISSUE THREAD

**Issue by ddelago** [nasa/trick#757]
As the title says, is it possible to get all available variables from a running sim through the Trick Variable Server? Something like a "trick.get_all_variables()" command that will return a LIST of the variables that can then be retrieved by the client. Right now I believe that if a client wants to get a variable's value from the TVS they need to know of its existence beforehand.

**Comment by dbankieris** [comment]
The list is not directly available, but it can be constructed by applying [this algorithm](https://github.com/nasa/trick/wiki/S_sie.resource-Parsing-Algorithm) to the information in the `S_sie.resource` file, which can be obtained from the Variable Server via `trick.send_sie_resource()`. This is how Trick View constructs its Variable Tree through which you can browse all available variables.

**Comment by ddelago** [comment]
Perfect, thanks for your help @dbankieris
