### ISSUE TITLE
Corral Monte Carlo output

### ISSUE THREAD

**Issue by benkirk** [nasa/trick#763]
We have a cluster with a shared filesystem tuned for high bandwidth IO, that struggles with tiny files.  It's connected to 10,000+ compute cores, and Trick Monte Carlo run output file production rate has become a scalability limit.

Ideally what I'd like to do is

- Continue to have Master write the aggregated output to the shared filesystem, but
- have the slaves write their per-run data to a different (local per slave) filesystem.

Even better, have each slave run each job in `/dev/shm/...` (Linux), and clean up as it goes.

Perusing 
https://github.com/nasa/trick/wiki/UserGuide-Monte-Carlo
and specifically,
https://github.com/nasa/trick/blob/master/trick_source/sim_services/MonteCarlo/MonteCarlo_master_file_io.cpp
https://github.com/nasa/trick/blob/master/trick_source/sim_services/MonteCarlo/MonteCarlo_slave_init.cpp

this seems like it should not be too hard, or maybe already could work.

A couple questions then,

1. Can masters and slaves have their own `run_base_directories`,
2. Per-run slave cleanup would be nice, where would be the best place to implement that?

If I could set
```bash
master_run_directory=/home/benkirk/path/to/ANALYSIS
slave_run_directory=/dev/shm/ANALYSIS
```
I think things would work straight away (without the cleanup anyway).

Thanks

**Comment by benkirk** [comment]
Beautiful, it'll take us some time to test because one of our app developers is out out for a bit.

One point of clarification, will the slave create its directory if it doesn't exist like the current master code?  No problem, easy enough to add if not.

**Comment by dbankieris** [comment]
It will create the final directory in the path if it doesn't exist, but will not create any missing parent directories. Unfortunately, there is no equivalent of [`mkdir(1)`](http://man7.org/linux/man-pages/man1/mkdir.1.html)'s `-p` option in [`mkdir(2)`](https://linux.die.net/man/2/mkdir). This is the same behavior that the master [currently exhibits](https://github.com/nasa/trick/issues/478).
