### ISSUE TITLE
Possible to check if a Sim is frozen through the Trick Variable Server?

### ISSUE THREAD

**Issue by ddelago** [nasa/trick#764]
There are commands to freeze and run a trick sim through the Trick Variable Server. Is there a command to check the status of a sim to tell if it is frozen or not?

**Comment by dbankieris** [comment]
In C we have [`Executive::get_mode`](https://github.com/nasa/trick/blob/3364cd3836751934c817c1bbad88377c8812e212/include/trick/Executive.hh#L373) and [`exec_get_mode`](https://github.com/nasa/trick/blob/3364cd3836751934c817c1bbad88377c8812e212/include/trick/exec_proto.h#L24).

Over the Variable Server, you can query `trick_sys.sched.mode`. The type is [`SIM_MODE`](https://github.com/nasa/trick/blob/3364cd3836751934c817c1bbad88377c8812e212/include/trick/sim_mode.h#L26), and Freeze corresponds to `1`.

**Comment by spfennell** [comment]
To elaborate (I typed this while dbankieris was responding):

The variable trick_sys.sched.mode is a variable that will return an integer that indicates if the sim is frozen or not. 

```
Initialization = 0
Freeze = 1 
Step = 4
Run = 5 
Exit = 6
```

So the if the following commands return 1, the sim is frozen:

```
trick.var_add("trick_sys.sched.mode")
trick.var_send()
trick.var_clear()
```

**Comment by ddelago** [comment]
Thank you!
