### ISSUE TITLE
Avoid std::endl

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#766]
[`std::endl`] inserts a newline into a [`std::ostream`], but it also flushes the stream. Flushing the stream is a costly operation, generally requiring a system call, and rarely necessary.

`std::endl` is frequently used throughout Trick's code wherever a newline is needed. Replacing it with a newline character is a simple change with a large potential performance improvement.

When `std::endl` follows a string literal, it's easiest to add a newline character to the end of the literal. For example,
```cpp
std::cout << "hello world!" << std::endl;
```
can become
```cpp
std::cout << "hello world!\n";
```
The opposite applies if it precedes a string literal.

In other cases, `std::endl` can just be replaced with the character literal `'\n'`. This is *slightly* faster than a single-character string literal.
So, prefer replacing
```cpp
std::string a = "foo";
std::string b = "bar";
std::cout << a << std::endl << b;
```
with 
```cpp
std::string a = "foo";
std::string b = "bar";
std::cout << a << '\n' << b;
```
rather than
```cpp
std::string a = "foo";
std::string b = "bar";
std::cout << a << "\n" << b;
```

[`std::endl`]: https://en.cppreference.com/w/cpp/io/manip/endl
[`std::ostream`]: https://en.cppreference.com/w/cpp/io/basic_ostream

**Comment by jmpenn** [comment]
In the case of realtime, non-error messages, such as JSON, variable
server messages, etc., I think you make a good point. We should want the
best performance we can achieve.

In the case of error messages, which should be emitted rarely, I doubt it
makes much of a difference. It’s also important to flush the messages ASAP.
Because there are a lot of error-conditions to check, std:endl could occur in
many many places that are very rarely, if ever called.

We’ll look at these changes on a case by case basis.

Thanks

**Comment by iamthad** [comment]
For error messages, remember that `std::cerr` is unbuffered by default and doesn't require flushing. I agree they are lower priority.

I have a changeset for SIE that I will make a PR for shortly. It reduces system calls in the sie_resource writing functions dramatically.

**Comment by jmpenn** [comment]
```Your recent JSON feature may be a prime candidate for eliminating endl.```

I agree, and already have, as a result of your issue.  :)

**Comment by jmpenn** [comment]
```I have a changeset for SIE that I will make a PR for shortly. It reduces system calls in the sie_resource writing functions dramatically.```

Have you measured the performance difference?

**Comment by iamthad** [comment]
For `SIM_parachute`, running `./S_main* sie` runs ~3x as fast. It was calling `write` ~14000 times.

I yet haven't tested it on any larger sims.

**Comment by jmpenn** [comment]
Wow! That's a bigger difference than I would have expected!

**Comment by jmpenn** [comment]
I think that pretty much does it!
