### ISSUE TITLE
Miscellaneous Python Trick Variable Server Bugs/Questions

### ISSUE THREAD

**Issue by nmerlene** [nasa/trick#777]
As the title suggests, I have a few miscellaneous questions regarding `variable_server.py`:

* As a follow-on to #759, is the intent to support both Python 2.x and Python 3.x?  If so, I think the following changes might need to be made for Python 3.x:

First, since Python 3.x replaces `basestring` with `str`, either replace all occurrences of `str` with `basestring` (if possible) or add the following block to the top of the module:

```python
try:
    basestring
except NameError:
    basestring = str
```

Additionally, since Python 3.x replaces `itertools.izip` with `zip`, change `import itertools` to the following block (and change calls of `itertools.izip` to `zip`):

```python
try:
    from itertools import izip as zip
except ImportError:
    pass
```

Not the most elegant looking solutions, but I think they'll enable Python 3.x compatibility without having to depend on a package like `six`.

* Another question I have is regarding `VariableServer.send_on_copy`.  Is `send_on_copy` supposed to be calling `trick.var_set_copy_mode` under the hood?  Or should it be calling `trick.var_set_write_mode` instead?

Thanks!

**Comment by dbankieris** [comment]
Good catches, thanks!
