### ISSUE TITLE
Most includes in SIM_*/makefile should not be optional

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#790]
* include build/Makefile_S_define
* include build/Makefile_src
* include build/Makefile_src_deps
* include build/Makefile_io_src
* include build/Makefile_swig
* include build/Makefile_swig_deps

We `-include` the above files in `SIM_*/makefile`. We have rules to make each of them, but the `-` makes the inclusion optional, which causes the build **not to fail** if any of those files fail to be generated. `build/Makefile_ICG` shouldn't be optional either, but it's built by ICG along with `Makefile_io_src`, and make has only [limited support](https://www.cmcrossroads.com/article/rules-multiple-outputs-gnu-make) for specifying rules that produce multiple targets.

**Comment by dbankieris** [comment]
Make reports the initially-missing files before generating them. Unfortunately, there's no want to disable that diagnostic. Annoying, but not enough to revert this commit.

```
makefile:107: build/Makefile_S_define: No such file or directory
makefile:108: build/Makefile_src: No such file or directory
makefile:109: build/Makefile_src_deps: No such file or directory
makefile:110: build/Makefile_io_src: No such file or directory
makefile:111: build/Makefile_swig: No such file or directory
makefile:112: build/Makefile_swig_deps: No such file or directory
```

**Comment by alexlin0** [comment]
I believe this is annoying enough to revert the commit.  People are going to be asking us about these warning messages.

**Comment by dbankieris** [comment]
The only way to remove the warnings is to use `-include`, which can result in a faulty build process. The warnings are only emitted during the first build. I'd rather answer questions about a build that's working than one that isn't.

https://stackoverflow.com/questions/43920369/suppress-make-warning-from-not-yet-built-include-without-suppressing-error
https://stackoverflow.com/questions/24771737/include-generated-makefile-without-warning-message

**Comment by alexlin0** [comment]
Create a build fault where this is useful.  Otherwise you are polluting all sim builds with false error messages.

**Comment by dbankieris** [comment]
`git diff trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp`

```diff
-    makefile_io_src.open("build/Makefile_io_src") ;
+    makefile_io_src.open("build/Makefile_io_srcs") ;
```
This causes make to enter an infinite loop.

With `-include`:
```bash
Running    ICG
Writing    Makefile_src
Running    ICG
Writing    Makefile_src
Running    ICG
Writing    Makefile_src
Running    ICG
Writing    Makefile_src
```

With `include`:
```bash
makefile:110: build/Makefile_io_src: No such file or directory
Running    ICG
Writing    Makefile_src
makefile:110: build/Makefile_io_src: No such file or directory
Running    ICG
Writing    Makefile_src
makefile:110: build/Makefile_io_src: No such file or directory
Running    ICG
Writing    Makefile_src
```

**Comment by dbankieris** [comment]
Here's the behavior if ICG crashes with a `SEGFAULT` do to a null pointer dereference, which could happen in some corner case that we fail to test.

```diff
+    *(NULL);
```

`-include`
```bash
Finished   S_define
Writing    S_source.c
Writing    Default_data
Writing    Makefile_swig
Running    ICG
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/models/io_BallState.cpp
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/models/io_BallForce.cpp
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/models/io_Ball.cpp
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/io_S_source.cpp
Running    ICG
Trick Build Process Complete
```

`include`
```bash
Finished   S_define
Writing    S_source.c
Writing    Default_data
Writing    Makefile_swig
Running    ICG
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/models/io_BallState.cpp
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/models/io_BallForce.cpp
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/models/io_Ball.cpp
Writing    build/users/dbankier/trick/trick/trick_sims/SIM_Ball++_L1/io_S_source.cpp
make: *** [build/Makefile_io_src] Error 139
```

While the error message is not particularly helpful to the user, it's better than "Trick Build Process Complete", and _is_ useful to us when they report it.

**Comment by dbankieris** [comment]
Another example: `make_makefile_swig` writes both `build/Makefile_swig` and `trick/__init__.py`. If the script dies after completing `Makefile_swig` but before completing `__init__.py`, the build will complete but fail to run when using `-include`. In contrast, `include` causes the build to fail as soon as `make_makefile_swig` does.

`-include`
```bash
Traceback (most recent call last):
  File "RUN_test/input.py", line 55, in <module>
    main()
  File "RUN_test/input.py", line 7, in main
    drg0 = trick.DRAscii("Ball")
AttributeError: 'module' object has no attribute 'DRAscii'
```

`include`
```bash
Writing    Makefile_swig
Could not open trick/__init__.py for writing at /users/dbankier/trick/trick/libexec/trick/make_makefile_swig line 300, <> line 4.
make: *** [build/Makefile_swig] Error 13
```

**Comment by dbankieris** [comment]
```make
-include foo 
all:
        @echo "Success"!
foo:
        @not-a-command
```

```bash
dbankier@peanut:make make
make: not-a-command: Command not found
Success!
```


```make
include foo 
all:
        @echo "Success"!
foo:
        @not-a-command
```

```bash
dbankier@peanut:make make
Makefile:1: foo: No such file or directory
make: not-a-command: Command not found
make: *** [foo] Error 127
```

**Comment by dbankieris** [comment]
Another consideration: because `-` causes the build not to fail even if the generation of any makefile fails, make's exit status is `0`, which would cause continuous integration to falsely report a successful build.

**Comment by alexlin0** [comment]
I saw that when someone includes a header file in the S_define that does not exist, a zero exit status is returned after an error message is printed.  This is the first user induced error that we should return take care of.  I withdraw my objection and will live with the warnings.
