### ISSUE TITLE
Increment the major release number!

### ISSUE THREAD

**Issue by alexlin0** [nasa/Trick#8]
Going open source is a big milestone.  Increment the major release number to mark the joyous occasion.

**Comment by ezcrues** [comment]
So does that mean Trick 15?

Sent from my iPhone

On Mar 4, 2015, at 3:28 PM, Alex Lin <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #8<https://github.com/nasa/Trick/issues/8> via dbaf7e8<https://github.com/nasa/Trick/commit/dbaf7e8ea33fc04e5ef19ab8a7c7e5df30b314ca>.

**Comment by alexlin0** [comment]
Yes!
