### ISSUE TITLE
Private Data is visable to be updated and viewed in Trick TV

### ISSUE THREAD

**Issue by miltondean** [nasa/trick#806]
Using Trick 17.4.0, it appears that attributes located in the Private section of a header file are available via Trick TV for viewing and updating without the:
 friend class InputProcessor ;
 friend void init_attr<class_name>() ;
that the Trick User's Guide states is required to access private data (Look under section Model Source Code).  In trick 13.5, private data was not available by default.

**Comment by alexlin0** [comment]
This is by design.  Our goal is to deprecate the requirement of the friends.  In 17.x most private data can be accessed without the friends, but there are cases where they cannot be accessed correctly.  Because of this, we have not announced that it is safe to remove all of the friend statements.

**Comment by miltondean** [comment]
Thanks Alex,

I was not sure if that was by design or not.  Thanks for letting me know.   The only suggestion I have is to update the user’s guide wrt ICG now processing private and protected data and add that when using SWIG, only the public data is accessible.
Evidently we had some developers move items into private when they knew IGC would not be able to resolve them.  Now that ICG attempts to resolve private/protected data, we will need to NO_ICG around them or ** them.

I have one other request.  Can we get the Trick 17 user’s guide in a PDF file.  I know you gave Jim Lodden a copy of Trick 13.1 several years ago.  I sure make searching and reading a whole lot easier in the pdf form.


Milton Dean
All-Points Logistics LLC
OrionSim Software Development
milton.w.dean@lmco.com<mailto:milton.w.dean@lmco.com>
(281) 333 – 6070  (desk)
(281) 235 – 5687  (cell)

**Comment by dbankieris** [comment]
I've updated the [user guide](https://github.com/nasa/trick/wiki/Model-Source-Code#public-protected-and-private-access). As for a pdf, GitHub doesn't have an option for that unfortunately. A brief Googling reveals several tools for converting wikis to pdfs, but they each seem to have their own shortcomings. Let us know if you find something that works well.
