### ISSUE TITLE
Issue with Trick 17.4 now requiring trick comment header in order to process smart comments.

### ISSUE THREAD

**Issue by miltondean** [nasa/trick#808]
The Trick User's guide states: "Comment Header

_The Trick comment header, which is optional,_ begins with /* PURPOSE:. Within the Trick comment header, the PROGRAMMERS, REFERENCES, ASSUMPTIONS AND LIMITATIONS and ICG are optional entries. Since parentheses, (), are used to delineate fields within the comment header, parentheses are not allowed as characters within the comment fields. Any other formatted comments may appear before and/or after the Trick comment header."

In trick 13.5, header files that did not have the optional trick comment header would still have the trick smart comments processed (i.e., units defined in smart comments would be processed and assigned for the attributes).  In trick 17.4, this does not appear to be occurring.   Now all of the attributes in the header file have attributes of (1).

**Comment by alexlin0** [comment]
The correct behavior is what you are seeing in 17.4.  We're not going to fix the behavior seen in 13.5.  Sorry for any problems this has caused.  In Trick 17, ICG prints warnings for any header files it parses that is missing a Trick comment header.

**Comment by miltondean** [comment]
Thanks Alex.

That makes sense.  We plan on updating our header files to include the trick comment header with our updated Trick 17 OrionSim project.

Milton
