### ISSUE TITLE
Memory Manager tests still require libtrick.a to be linked in.

### ISSUE THREAD

**Issue by jmpenn** [nasa/trick#81]

**Comment by jmpenn** [comment]
The gcc linker searches a library only once per occurrence on the command line to resolve symbols.
So, if the libraries have circular dependencies, which we currently, unfortunately have, the libraries have to be listed twice.
clang is fine with libraries listed only once where there are circular dependencies.

**Comment by dbankieris** [comment]
I believe the preferred solution is to use --start-group and --end-group rather than repeat libraries. See http://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking
