### ISSUE TITLE
Unable to change var cycle

### ISSUE THREAD

**Issue by Volstn1** [nasa/trick#813]
Trick.var_cycle(rate) is having seemingly no effect on the rate the variables are sent. No matter the value the rate is set to they are sent at 10 Hertz. I have ensured the copy mode is set to scheduled and the software frame is sufficiently low. Is there something I am missing to adjust the cycle rate?

**Comment by spfennell** [comment]
Hi @Volstn1. My guess is that you are trying to set the cycle rate from the wrong variable server client or from the sim/input file. trick.var_cycle(double rate) is a command that is sent from the client to the variable server via a TCP connection, and the rate is changed for that specific client.

There is an example of sending commands in the Trick Tutorial [here](https://github.com/nasa/trick/wiki/TutVariableServer#a-simple-variable-server-client). If this is not your problem, can you tell me a little bit more about what kind of client you are sending commands from?

**Comment by Volstn1** [comment]
Thank you for your quick response, I am sending the command over a TCP connection and have had no issues with the other commands I am sending. I have a C# script that connects to the Trick cannonball_analytic sim from the tutorial via TCP/IP socket and sends commands such as write binary, pause, unpause, adding variables, set copy mode, and set var cycle. Is the var cycle viewable in Trick view? I assumed it was cycle_period, however, this is always 0.0  and cycle_period_set is false. Also is the order the command is sent relevant?

**Comment by Volstn1** [comment]
I was able to resolve the issue, it was a problem with the scope on my end. Thank you so much for your help!
