### ISSUE TITLE
QUESTION: How to contribute to code?

### ISSUE THREAD

**Issue by nogurenn** [nasa/trick#821]
Where should I start as a developer looking to contribute?

**Comment by jmpenn** [comment]
How familiar with Trick are you? 
Have you done the Trick Tutorial? If you haven't, I would suggest doing that first.
Have you written your own simulation to model something you're interested in?

Once you've done that, then ask yourself: Is there an update or modification that would be useful to me, and other simulation developers? If you think there is then submit it as a merge request and we'll go from there.
