### ISSUE TITLE
Array Initialization Optimization Investigation

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#832]
There is a rumor that initializing an array all at once is 10 times slower than initializing one cell at a time. Investigate and fix

**Comment by esduran** [comment]
I am curious about where this rumor stems from and perhaps more context in what types of arrays and the scenario?

If initializing a C-style array to default values, doing something like `int arr[10] = {0}` will zero-initialize all the elements. In C++, one can do `int arr[10] = {}` to zero-initialize the array. A static array of the following, `static int myArray[10];` will default initialize all elements to zero.

If you are using C++11 and newer, you can utilize [std::array](https://en.cppreference.com/w/cpp/container/array). This afford you the same initialization rules as above with the additional benefits of being able to use the STL. So if you want to fill the array with values returned from a function, you can use [std::generate](https://en.cppreference.com/w/cpp/algorithm/generate) or [std::fill](https://en.cppreference.com/w/cpp/algorithm/fill) to set the elements to a specific value. Granted, default initializing or zero initializing should be much faster. 

Using [compiler-explorer ](https://godbolt.org/), the assembly produced by default initializing and using a for loop to initialize the elements results in the same level of assembly code with -O3 optimization turned on. It looks like the compiler is smart enough to just optimize that. Without optimization of -O3 turned on though, using a default initializer list `int arr[10] = {}` produces less assembly. Another good test would be to use [quick-bench](http://quick-bench.com/) to get a rough estimate on performance.

Hope I helped in some way!

**Comment by spfennell** [comment]
My tests showed this was true for small arrays, but for large arrays initializing one element at a time was much slower.

**Comment by iamthad** [comment]
Is it possible the original rumor was talking about initializing arrays from Python, rather than directly in compiled code?

**Comment by spfennell** [comment]
I wasn't specific enough in the original issue. This is a problem with load from checkpoint. It has to do with how we parse checkpoints and allocate memory within trick's checkpoint and memory manager classes.

**Comment by miltondean** [comment]
I think the rumor is talking about initializing arrays from Python and not from compiled code.  We uncovered this by trying to see if we could speed up our initialization (which we use SWIG generated python to initialize non zero data in our classes).  When we have arrays (or array rows) defined with more than one value ('Sim.Orion_1.Dyn.AeroModel.State.Cap.Cev.CmAero.T_Body_from_SrFrame[0] = [-1.0,0.0,0.0]) it takes more runtime to process that statement vs creating more python statements and just supplying one item in each statement (Sim.Orion_1.Dyn.AeroModel.State.Cap.Cev.CmAero.T_Body_from_SrFrame[0][0] = -1.0
Sim.Orion_1.Dyn.AeroModel.State.Cap.Cev.CmAero.T_Body_from_SrFrame[0][0] = 0.0
Sim.Orion_1.Dyn.AeroModel.State.Cap.Cev.CmAero.T_Body_from_SrFrame[0][0] = 0.0).
