### ISSUE TITLE
DataRecordGroup double freeing

### ISSUE THREAD

**Issue by rachelo** [nasa/trick#84]
DataRecordGroup is double freeing drb->buffer resulting in this core-dump:

*** glibc detected *** 
/users/gturner/repos/antares_auto/antares/cev/sims/SIM_em1/S_main_Linux_4.4_x86_64.exe: 
double free or corruption (fasttop): 0x000000000eede5a0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x33f5a75e66]
/users/gturner/repos/antares_auto/antares/cev/sims/SIM_em1/S_main_Linux_4.4_x86_64.exe(_ZN5Trick16DataRecordBufferD1Ev+0x2a)[0x48752c8] 

The offending code:

DataRecordGroup.cpp:
(lines 619-634)

    for (jj = 0; jj < change_buffer.size() ; jj++) {
        drb = change_buffer[jj] ;

        if ( drb->buffer ) {
            free(drb->buffer) ;
        }
        if ( drb->last_value ) {
            free(drb->last_value) ;
        }
        if ( drb->ref ) {
            if ( drb->ref->reference ) {
                free(drb->ref->reference) ;
            }
            free(drb->ref) ;
        }
        delete drb ; (a free is occurring here)

And
(47-49)
Trick::DataRecordBuffer::~DataRecordBuffer() {
    if ( buffer ) {
        free(buffer) ;

**Comment by alexlin0** [comment]
We found this a while back.  It was fixed between 13.5.0 and 15.0.0.

If you want to fix the issue locally without having to upgrade all of Trick change the for loop  that you show above to read:

```
     for (jj = 0; jj < change_buffer.size() ; jj++) {
        delete change_buffer[jj] ;
    }
```
