### ISSUE TITLE
Using -O for monte-carlo hangs the sim forever

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#848]
I was able to replicate on b457746d61713957f8eb26453343af84721b2df8

```
trick/trick_sims/Cannon/SIM_monte > ./S_main_Linux_4.8_x86_64.exe RUN_test/gauss.py -O foobar
Units converted from [d] to [degree] RUN_test/gauss.py:65
Units converted from [d] to [degree] RUN_test/gauss.py:66
Units converted from [rev/s] to [revolution/s] RUN_test/gauss.py:67
 |T 0|0.000000| Monte: Spawning Slave localhost:1 :
/bin/sh -c 'cd trick/trick_sims/Cannon/SIM_monte; ./S_main_*.exe RUN_test/gauss.py --monte_host blade04-fsl.jsc.nasa.gov --monte_sync_port 34439 --monte_client_id 1 -O ' &

ERROR: No directory specified after -O or -OO argument
```

This appears to work fine in normal runs, it's just in monte-carlo.

**Comment by ddj116** [comment]
Any update on this? We've got users working around this issue with various hacks for the time being.

**Comment by spfennell** [comment]
@ddj116 Should work now. There was a small bug that was introduced where the slave_output_directory was not getting initialized if the user provided an input directory.

**Comment by ddj116** [comment]
Thanks, will give it a shot in our sim and report back.

**Comment by ddj116** [comment]
On commit d978cdf4c6f89b182925fd7337783d681b956e1a I was able to redirect via `-O` in both our specific use case and in the example listed above.  I'll move our project up to point to the latest state of trick to get this fix.  Thanks!
