### ISSUE TITLE
No rule for template *.hpp files

### ISSUE THREAD

**Issue by ajfear** [nasa/trick#85]
If a header file containing a template class with the hpp extension is included in a model header file, the compiler will fail with a "No rule to make '${PATH}/io_source/io_<file>.hppcpp' needed by ${PATH}/object_*/io_<file>.hppo" 

In addition, if there is no #ifndef SWIG wrapper around the include for the template hpp and a make clean is performed, a "rm -rf" is done on the include directory with the template hpp file.

**Comment by alexlin0** [comment]
I fixed this here in the development version of trick.  I am going to guess that you aren't able to use the bleeding edge.  It may be easier for now to change the extension of your file until you are able to use a released version with this fix.

On a related note: That nasty rm -rf in your include directory is not possible in the more recent development versions anymore.
