### ISSUE TITLE
Don't use realpath in PrintAttributes.cpp

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#857]
@dbankieris Need to use almostRealPath instead of realpath in all ICG code.  Here is why.

Given a file
```
/path/to/fileA.h
```
A common practice is to create a symbolic link to this file like this
```
/another/path/to/file.A -> /path/to/fileA.h
```
Then people exclude their linked directory
```
TRICK_EXCLUDE = /another/path/to
```
If you use realpath /another/path/to/fileA.h resolves to /path/to/fileA.h and is not excluded.  almostRealPath does not follow symbolic links if it is the last piece of the path so /another/path/to/fileA.h resolves to /another/path/to/fileA.h and is properly excluded.

**Comment by dbankieris** [comment]
This change was in error. As users may add either `/path/to` or `/another/path/to` to any of the exclusion variables, we must check both the `realPath` and `almostRealPath`, which is what the code was doing. I'll add a unit test for both cases for all exclusion variables.
