### ISSUE TITLE
Trick Units misbehaving in Trick TV

### ISSUE THREAD

**Issue by miltondean** [nasa/trick#858]
I suspect some of the conversion logic in Trick TV is not taking into account the new unit names that were added in Trick 17.  I have a few examples:
  In trick TV, When I bring  up variable with units (m2), I can choose different Units to convert to (pm2, nm2,cm2,...).  When I bring up a variable with units (m^2), I am note given any such list.  
 Likewise when I bring up a variable with units (ms), I can choose different time units to convert to.  When I select a parameter with units (millisecond), again it does not give me any alternate units to convert to.  {Side note on time conversions: If you select the time in the pick list with the 'd', it will produce the following messages:
|Variable Server: [Sim.Orion_1.CEV.itsSmModel.itssPDEModel[0].State.currTime] old-style units converted from [d] to [degree]
ut_get_converter(): Units not convertible
| Variable Server: [Sim.Orion_1.CEV.itsSmModel.itssPDEModel[0].State.currTime] cannot convert units from [s] to [degree]  NOTE: the new unit for days appears to be day[s], even though when using the trick-units it specifies  Days: d, day[s].}
When I select units in trick TV for V/amp, I get a Select  Units pop up box, but it only allows me to select an alternate value for V.  It has a pick bar for second value, but nothing to pick in that list.
When I select unit in trick TV for K/s, I get a Select Units pop up box, but it only allows me to select an alternate value for 's'.  It has a pick bar for the first value, but nothing to pick in that list.

I did  not try to see if the (m^2) or the (milliseconds) units allow you to convert in DR logging files, or allow you to use the trick.attach_units to display or use alternate values, but I suspect those conversions might also be effected.

**Comment by dbankieris** [comment]
Related to #262. How shameful that I've neglected this for so long!

**Comment by miltondean** [comment]
It seems to me that trick should be accepting all of the different unit types from udunits and then it should convert all of the alternate compatible names to use only one version that would be used by the trick sim (i.e., used in the S_sie.resource file).  We use trick to query on what type of unit a parameter is.  Then when we copy that value to another value (which we have also determined what type of units it was defined as), we will raise an error if the units don't match.  So with the current Trick implementation if you use (radian) as a unit, that is inserted into S_sie.resource and if you use (rad) that is also inserted into t he S_sie.resource file.  When we try and compare a value with units (rad) vs an value with units (radian), that miscompares.  I think accepting all the udunits and then instead of allowing all of  the aliases for a specific unit to be used in S_sie.resource, you should think about replacing all of the compatible aliases with just one term.  So radian, randians, rad (which are all valid) would get replaced with (rad) in S_sie.resource.

**Comment by miltondean** [comment]
I  have been doing a little more investigation into this matter.  
1)  In map_trick_units_to_udunits.cpp a few valid udunits unit names have been hijacked and converted to alternate udunits names so that there is a somewhat backward compatibility.   While most of the units that were hijacked are not used very often (if ever),  some are. (List of valid udunits that were redefined> d=day, as=atto second, am=atto meter, mt=milli ton, oz=ounce, F=farad, C=coulomb, R=roentgen, TNT= 4.184 MJ /kg (unit of energy), gal =cm/s^2 (unit of acceleration). 
The main problem here is 'd' cannot be used for day in Trick17, so we are forced to use 'day'.  In udunits 'oz' and 'floz' are equivalent, but trick17 replaces oz with ozf (ounce-force) for backward compatibility so we can only use 'floz' for ounce in trick17.
2) The trick-units command displays a list of some common units, but this list has some discrepancies like 'd' for days, but 'd' gets hijacked by trick17 to be degree, so the correct unit is 'day'.  Also 'm' is meters, but trick-units command also states 'm' is minutes (which is incorrect) as 'min' is the correct term as trick TV will only process 'min'.   Hours should be 'hr' as Trick TV cannot process 'h' or 'hour'.  Microseconds should be 'us' as Trick TV will not recognize 'microseconds' or 'μs'.
3)  Trick TV will only process 'rad' (not 'radian'), 'degree', 'revolution', 'arcsecond', 'arcminute'.  Udunits has other aliases for these, but Trick TV does not recognize them.
4) Trick TV will only process 'A' (not 'amp' or 'ampere').  'kw*hr' (not 'kW.h'), 'W*hr' (not 'W.h'), 'degK', 'degF', 'degC', and 'degR' as the other variants did not work in Trick TV.  I could go on and on, but I think you get the idea.
5) units_conv.c in the trick_utils code still has some units in it which are not in the udunits set (sl, pr, nr, etc).  This member also documents the trick units in Doxygen which were the ones for Trick13.

FYI,
I found this web page that actually list most of the udunits units.
https://ncics.org/portfolio/other-resources/udunits2/

**Comment by dbankieris** [comment]
The full list of units and aliases is derived from [a collection of xml files ](https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2.html#Database). Trick View should parse those to obtain valid conversions, but I haven't been able to figure it out.

**Comment by matthewjessick** [comment]
This issue drives me to distraction. There are 93 occurrences of "radian" in JEOD 3.4, including things I really really want to translate on output like ref frames, and body rates.   Best wishes!

**Comment by TG9541** [comment]
@miltondean I reckon that most engineers (and most scientific communities) use the SI system. `m` for "miniutes" instead of "meter" doesn't bode well for the usefulness of Trick outside of the American engineering community.
