### ISSUE TITLE
Can not compile the sample

### ISSUE THREAD

**Issue by gaozheyuan1** [nasa/trick#89]
Hi everyone
   I am new to this project, I've compiled everything and when I was trying the samples I encountered this error:

 trick-CP 
Parsing S_define...
Could not find S_define LIBRARY_DEPENDENCY cannon/aero/src/cannon_init_aero.c
Could not find S_define LIBRARY_DEPENDENCY cannon/aero/src/cannon_force_gravity.c
Could not find S_define LIBRARY_DEPENDENCY cannon/aero/src/cannon_force_drag.c
Could not find S_define LIBRARY_DEPENDENCY cannon/aero/src/cannon_force_lift.c
Could not find S_define LIBRARY_DEPENDENCY cannon/aero/src/cannon_force_cross.c
Could not find S_define LIBRARY_DEPENDENCY cannon/aero/src/cannon_collect
....

could not find cannon/aero/include/cannon_aero.h

It looks like I didn't set some environment variables, does anyone know what's issue of this problem?

**Comment by alexlin0** [comment]
Hi there,

I'm working on the code that looks for library dependencies and have broken it temporarily.  I am working to fix it and hopefully will be able to check in code later today.
