### ISSUE TITLE
Trick's SIGCHLD handler conflicts with pandas and other python packages

### ISSUE THREAD

**Issue by DavidHammen** [nasa/trick#909]
Pandas adapts itself to the machine at hand, performing-specific actions based on the result of a calling platform.machine(). This call to platform.machine() eventually results in a call to os.popen("uname -p 2>/dev/null"). The pseudo IO device returned by that call is later closed, and this close fails because Trick's SIGCHLD signal handler has already eaten the signal.

Any package that tailors itself to the machine at hand via a call to platform.machine or os.uname is at risk of not working in a Trick environment.

**Comment by alexlin0** [comment]
Trick should provide a way to turn on/off the SIGCHLD signal handler like it does the other signal types.

Another possible thing Trick could do is only activate SIGCHLD handler when it expects a child to exit.

**Comment by alexlin0** [comment]
Another report has come in where SIGCHLD is affecting simulation execution.   This come from our friends at KSC.
