### ISSUE TITLE
Trick vs Xcode 11

### ISSUE THREAD

**Issue by DavidHammen** [nasa/trick#922]
As of Xcode 10, there is no such thing as /usr/include on a Mac, at least without contortions. As of Xcode 11, those contortions are no longer available. As Apple noted on https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624 , emphasis mine,

> However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. As a workaround, an extra package is provided which will install the headers to the base system. **In a future release, this package will no longer be provided.** You can find this package at:
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

I have Xcode 11.3, and that package is indeed no longer provided.

**Comment by spfennell** [comment]
David, thanks for spotting this. As a quick workaround, can you try using CMake to build trick instead of autotools configure? Another mac user found that this worked for them. Regardless, we will still provide a fix for this.

**Comment by DavidHammen** [comment]
@spfennell - OSX Catalina (10.15) and Xcode 11.3 don't ship with llvm_config, presumably because llvm_config does not jibe with the new development configuration scheme.

**Comment by spfennell** [comment]
@DavidHammen we use a macOS container hosted by MacStadium to test our Catalina/XCode 11 build. It currently has XCode 11.1 installed by default, as well as homebrew.

I think you may need to install llvm with homebrew.

These are the dependencies we install with homebrew:
```
brew cask install xquartz
brew install llvm swig udunits openmotif
```

As a result, here is where ./configure finds our dependencies (without installing a header package). 

```
checking for llvm-config... /usr/local/opt/llvm/bin/llvm-config
checking for /usr/local/Cellar/llvm/9.0.0_1/include/clang/Basic/LLVM.h... yes
checking for /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMSupport.a... yes
checking for clang... /usr/local/Cellar/llvm/9.0.0_1/bin/clang
```
Is this information helpful?

**Comment by spfennell** [comment]
@DavidHammen did this resolve your issue?
