### ISSUE TITLE
OS version numbers.

### ISSUE THREAD

**Issue by FRPutnamJr** [nasa/trick#925]
Does Trick have to run on the OS version numbers outlined in the install documentation? i.e. Fedora 24. Fedora is at version 31 now. What about the Package Dependencies version numbers?

**Comment by spfennell** [comment]
Trick has been tested up to Fedora 30, it is very likely that it will run on Fedora 31. 

The package dependencies are mostly minimum versions. The default version for your package manager will work with trick, we do all of our testing and continuous integration with the default versions provided by each package manager. 

I will create a new issue to update the install instructions with this information.

**Comment by FRPutnamJr** [comment]
Scott,

Thanks for getting back so quickly. I will try it with Fedora 31.

 

Regards,

Frank Putnam, Jr.
