### ISSUE TITLE
Java library downloads require https now

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#926]
We are using http to download the java libs in libexec/trick/java/lib/makefile.  Change these to https.

**Comment by spfennell** [comment]
https://support.sonatype.com/hc/en-us/articles/360041287334

**Comment by spfennell** [comment]
If you don't want to update your release, you can edit ${TRICK_HOME}/libexec/trick/java/lib/Makefile and change all occurences of "http" to "https". run "make clean" in ${TRICK_HOME}/libexec/trick/java/lib to remove all of the jar files, then "make" again from the top level directory.

**Comment by spfennell** [comment]
UPDATE: 19.0.1 and 17.5.1 have been released to fix this issue.
