### ISSUE TITLE
Trick compilation terminated.

### ISSUE THREAD

**Issue by FRPutnamJr** [nasa/trick#930]
The compiler seems to have a problem with object_Linux_9_x86_64/FieldVisitor.o. Any suggestions?

![Trick_make_error-2](https://user-images.githubusercontent.com/27035740/72481021-c8c6b100-37be-11ea-86ca-f016d97b3227.PNG)

**Comment by spfennell** [comment]
Hmm we haven't run into that error on our Fedora 31 build. Make sure you 'make clean' after you've updated your trick version and build from scratch. I'm not sure how to reproduce this bug.

**Comment by spfennell** [comment]
A google search of "killed signal terminated program cc1plus" suggests you might not have enough memory allocated for your VM https://bitcointalk.org/index.php?topic=304389.msg3258944#msg3258944

**Comment by FRPutnamJr** [comment]
Thanks Scott.

The problem is related to the size of the memory and disk space. I am starting from scratch and resizing the virtual machine.

 

Regards,

Frank Putnam, Jr.

**Comment by FRPutnamJr** [comment]
That worked.
