### ISSUE TITLE
Incorrect documentation.

### ISSUE THREAD

**Issue by FRPutnamJr** [nasa/trick#934]
FYI:
On page "https://nasa.github.io/trick/tutorial/ATutRecordingData"
under the heading "Running The Simulation And Recording Data"
the instructions say to add the following line to the top of "RUN_test/input.py":
execfile("Modified_data/cannon.dr")

When I received an error message I reviewed the input.py files in the trick_sims directory to find that the line should have been: "exec(open("Modified_data/data_record.dr").read())".

**Comment by spfennell** [comment]
Thanks!

**Comment by spfennell** [comment]
@FRPutnamJr however, if you follow the instructions carefully we actually suggest  you name the dr file cannon.dr, so it would be ```exec(open("Modified_data/cannon.dr").read())```

**Comment by FRPutnamJr** [comment]
Yes, you are correct. That's what I get for COPY/PASTE without reviewing the outcome.
