### ISSUE TITLE
TrickView can no longer mass convert units

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#940]

**Comment by dbankieris** [comment]
@spfennell Did we talk about that new set units field? I only just noticed it today! This was already possible by selecting multiple 
variables and changing a units field. Now I wonder why there aren't set value and set format fields as well.

**Comment by spfennell** [comment]
@dbankieris  There was a bug in the loop (a misplaced break statement) that did not allow for changing units field on multiple variables. I thought this was the default behavior so I added a set units field. Now that it is no longer necessary, I can remove it.

Would you prefer to remove the set units field, or add a set value and set format field?

**Comment by dbankieris** [comment]
I would prefer to remove the set units field. The less busy the GUI is, the better!

**Comment by spfennell** [comment]
Will do
