### ISSUE TITLE
Consider using clang to generate the S_sie.resource file

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#947]
The last step in the build process is to generate `S_sie.resource`. Currently, we have to run the sim to execute the `inti_attr` functions to build the memory manager map which we traverse to generate `S_sie.resource`. Running the sim necessarily instantiates all top level sim objects (and all their recursively contained objects), which runs their constructors. This is problematic if you're using [RAII](https://en.cppreference.com/w/cpp/language/raii) to manage your resource allocation with your constructors and destructors. For instance, ROS `NodeHandle`s cannot be instantiated until `ros::init` is called, which requires `roscore` (a separate process) to be running. This means you have to run `roscore` to compile your sim or defer all of your `NodeHandle` instantiations to initialization jobs, which means they have to be pointers now, and that's no good! Other common RAII tasks in the constructor are connecting to databases, opening files, etc. All stuff you don't want to do when you compile the sim. Clang is already writing the `init_attr` functions. Let's cut out the middle man and have it write `S_sie.resource` itself!

**Comment by dbankieris** [comment]
@spfennell Did you say this was done?

**Comment by spfennell** [comment]
> @spfennell Did you say this was done?

@dbankieris This is not done. The ICG side is complete, however I am still working on getting parse_s_define.pm to add top level objects to the Sie_resource file, and also the runtime code for dynamic allocations needs to be modified to append to the S_sie.resource file instead of regenerating it.
