### ISSUE TITLE
Memory leadership in data serializations checkpoint

### ISSUE THREAD

**Issue by GrigoriPerelmanIsBetterNewton** [nasa/trick#95]
Greetings!

I have copied trick and learned most of code recently in last winter.  I found issue however in memory leadership related to checkpoint system.

I get Trick failure when loading ASCII checkpoint (Unicode better) in more recently versions of simulation binary.  This I find unusual because serialization problem has typical solution we learn for university entrance exam.  Please see link with more information:

http://stackoverflow.com/questions/447898/what-is-object-serialization

I can force branch make change then request pull yes?

**Comment by jmpenn** [comment]
Can you provide more details about the problem you found?
In which Trick release did you see the problem?
What are the symptoms of the problem?
What error messages did you see?

You're certainly welcome to fork the project and make any modifications you'd like.
If you think you have changes that would be generally useful to the
Trick community, please send a pull request and we'll take a look to 
see whether we'd like incorporate them.

Thanks,
John Penn
