### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [nasa/trick#955]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [Delta](https://github.com/nasa/trick/blob/f78a7ac8d60c937ad1ae462138942b8f47c2e1ae/trick_source/data_products/Log/Delta.cpp#L12)
- [differentialDriveControllerTest](https://github.com/nasa/trick/blob/34dcffa7f79cd66df02c57ac808097c243d99f41/trick_sims/SIM_wheelbot/models/Control/test/DifferentialDriveControllerTest.cpp#L15)

**Comment by jmpenn** [comment]
I can't say that I see the value.

**Comment by elfring** [comment]
Do you care for [current C++ guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-owner "Guidelines for smart pointer usage")?
