### ISSUE TITLE
issue with ./configure on mac with 10.15.*

### ISSUE THREAD

**Issue by grahamannett** [nasa/trick#971]
I got trick to configure and build a few months/weeks ago when I was on a lower mac version (I don't remember having issues and did one of the tutorials).  I've recently upgraded my mac to 10.15.3 and ./configure seems to exit and not work due to an issue with X11/Intrinsic.h:

```
checking X11/Intrinsic.h usability... no
checking X11/Intrinsic.h presence... yes
configure: WARNING: X11/Intrinsic.h: present but cannot be compiled
configure: WARNING: X11/Intrinsic.h:     check for missing prerequisite headers?
configure: WARNING: X11/Intrinsic.h: see the Autoconf documentation
configure: WARNING: X11/Intrinsic.h:     section "Present But Cannot Be Compiled"
configure: WARNING: X11/Intrinsic.h: proceeding with the compiler's result
```

I tried a fair amount of opts for the configure but what finally got it to work (so far I have been going through the tutorial again) is configure with something like 
`./configure --x-includes=/opt/X11/include/ --x-libraries=/opt/X11/lib/`

and changing configure something like 
https://github.com/grahamannett/trick/commit/75ebadaf7e6f144678a44f471e0b15f5e0200de6

I'm not sure if this is fine, but everything seems to compile and install correctly with that, is that worth merging in or would it create other issues?

**Comment by spfennell** [comment]
Hi @grahamannett, 

Our tests on macOS 10.15.3 are passing. Try this:
Make sure XCode is up to date (our tests pass on XCode 11.3.1)

Re-run this command:
`xcode-select --install`

Make sure xquartz is installed and up to date
`brew cask install xquartz`

Then make clean and try to configure with the unmodified configure script.

Please let me know if this fixes the issue.

The test environment we use is here: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

That environment already has XCode and xcode-select (command line tools) installed.

The script we run in that environment to get trick to compile is here:
```
brew cask install xquartz
brew install llvm swig udunits openmotif maven
./configure
make
```

**Comment by grahamannett** [comment]
tried this last night and again just now with the latest commit, still get the error and ./configure exits.  Im on Xcode Version 11.4, not sure if thats the issue (doesn't seem like it since it has to do with X11?) but exits early.   Everything seems to work fine though if I change the configure so maybe it is just my computer.

**Comment by spfennell** [comment]
I do not think this is your computer. I think this has to do with macOS putting the header files in an unconventional place. Formerly in 10.14 they had a pkg that you could use to put the headers in a place where trick could find them, but that pkg does not exist on 10.15. We should adjust trick, not force users to go searching for headers and manually installing them in usr/include

**Comment by spfennell** [comment]
We may need to add some things like this: https://apple.stackexchange.com/a/363263

**Comment by alexlin0** [comment]
I added "xcrun --show-sdk-path" in some of the makefiles in data_products to handle the include files no longer being in /usr/include.  This may be needed in the configure script as well now.

**Comment by spfennell** [comment]
@alexlin0 @grahamannett 
I clean installed Catalina 10.15.4 and XCode 11.4 on my personal mac (it needed an upgrade) and I did not run into this issue. The autoconf documentation suggests that you might be missing a dependency for X11/Intrinsic.h. 
I would need to look directly at your environment to make any progress on this issue

**Comment by spfennell** [comment]
perhaps try uninstalling and reinstalling xquartz

**Comment by grahamannett** [comment]
@spfennell just tried again and completely uninstalled all associated packages from brew and reinstalled them.  still same problem.  if you are saying it works with 11.4 and latest 10.15.* it is probably just something misconfigured on my end but I am unable to figure to figure out exactly what as everything runs just fine if I comment out that line in configure.

**Comment by shabbychef** [comment]
The incantation has changed to `brew install --cask xquartz`, I believe.
