### ISSUE TITLE
CMake on macOS finds compilers that do not include system headers

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#979]
All of the compiler links in /usr/bin (c++, cc, gcc, g++) are configured to include the C system headers in 
``` `xcrun --show-sdk-path`/usr/include```
or  in my case 
```/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include```.

However CMake by default finds other compilers in the xcode toolchain directories that don't include these headers.

Somehow trick compiles just fine, but when we compile a sim it breaks down.

@jmpenn @alexlin0 @dbankieris 
I would like your opinion on this. 

Option 1.
Should we require mac users to configure the compilers? 
```cmake -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DCMAKE_C_COMPILER=cc```
or 
```cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_C_COMPILER=gcc```
(doesn't matter which alias you choose, its all clang)

Option 2.
we can add -isystem$(shell xcrun --show-sdk-path)/usr/include
to our makefile variables for all invocations of the compiler. 

Option 3.
We could also ask the user to copy their system headers to /usr/include. I have not tested this. 

Option 4.
Set the compiler in CMakeLists.txt. CMake documentation says to avoid this behavior. One of the reasons to avoid is that CMake will still find and test the other compiler before executing any of your CMakeLists.txt code, wasting time. I'm sure there are probably other reasons they say to avoid this as well.

Please tell me what you think.

**Comment by dbankieris** [comment]
1. Not a big fan of this one. I generally prefer solutions that don't require any user action.
1. This is my preferred solution if there are no negative side effects. Are we sure the compilers all include the same headers? Is there a reason the additional compilers found by CMake don't include any headers?
1. Strongly opposed. Many users will not have sufficient permission to do this, and package mangers should be the only ones mucking around in `/usr`.
1. People probably don't build Trick very frequently, so wasting time is not a strong argument in my opinion, but I agree that there are likely other reasons to avoid this. For instance, we ought to use whatever compiler the user has configured as the default.

**Comment by alexlin0** [comment]
None of the above.  Is there no way to tell cmake the search path order when looking for the compiler?  There has to be.

**Comment by alexlin0** [comment]
Try using this in the cmake file.  Replace the project line with this block.

```

project(trick NONE)
if(CMAKE_SYSTEM_NAME MATCHES Darwin)
    if ( (NOT DEFINED CMAKE_C_COMPILER) AND (NOT DEFINED ENV{CC}))
        set(CMAKE_C_COMPILER /usr/bin/cc)
    endif()
    if ( (NOT DEFINED CMAKE_CXX_COMPILER) AND (NOT DEFINED ENV{CXX}))
        set(CMAKE_CXX_COMPILER /usr/bin/c++)
    endif()
endif()
enable_language(C)
enable_language(CXX)
```

**Comment by spfennell** [comment]
> Try using this in the cmake file. Replace the project line with this block.
> 
> ```
> 
> project(trick NONE)
> if(CMAKE_SYSTEM_NAME MATCHES Darwin)
>     if ( (NOT DEFINED CMAKE_C_COMPILER) AND (NOT DEFINED ENV{CC}))
>         set(CMAKE_C_COMPILER /usr/bin/cc)
>     endif()
>     if ( (NOT DEFINED CMAKE_CXX_COMPILER) AND (NOT DEFINED ENV{CXX}))
>         set(CMAKE_CXX_COMPILER /usr/bin/c++)
>     endif()
> endif()
> enable_language(C)
> enable_language(CXX)
> ```

This works, the only thing I would like to add is 
``` 
...
if(CMAKE_SYSTEM_NAME MATCHES Darwin)
    if (NOT DEFINED C...    AND (EXISTS /usr/bin/cc))
        set(CMAKE_C_COMPILER /usr/bin/cc)
    endif()
    if ( (NOT DEFINED C...  AND (EXISTS /usr/bin/c++))
        set(CMAKE_CXX_COMPILER /usr/bin/c++)
    endif()
endif()
...
```

Thanks for finding that solution @alexlin0
